from __future__ import annotations


OWNER_CALLABLE_RECEIPT_SURFACE = "owner_callable_adapter_receipt"
OWNER_CALLABLE_RECEIPT_STUDY_LATEST_SURFACE = "owner_callable_adapter_receipt_study_latest"
LEGACY_EXECUTION_SURFACE = "default_executor_dispatch_execution"
LEGACY_EXECUTION_STUDY_LATEST_SURFACE = "default_executor_dispatch_execution_study_latest"
ACCEPTED_EXECUTION_SURFACES = frozenset({OWNER_CALLABLE_RECEIPT_SURFACE, LEGACY_EXECUTION_SURFACE})
ACCEPTED_EXECUTION_LATEST_SURFACES = frozenset(
    {OWNER_CALLABLE_RECEIPT_STUDY_LATEST_SURFACE, LEGACY_EXECUTION_STUDY_LATEST_SURFACE}
)


__all__ = [
    "ACCEPTED_EXECUTION_LATEST_SURFACES",
    "ACCEPTED_EXECUTION_SURFACES",
    "LEGACY_EXECUTION_STUDY_LATEST_SURFACE",
    "LEGACY_EXECUTION_SURFACE",
    "OWNER_CALLABLE_RECEIPT_STUDY_LATEST_SURFACE",
    "OWNER_CALLABLE_RECEIPT_SURFACE",
]
