from __future__ import annotations

from .layout_box_helpers import run_layout_qc_case

CASES = {
    'test_run_display_layout_qc_flags_compressed_observed_risk_spread_for_grouped_risk_summary': {'qc_profile': 'publication_survival_curve', 'layout_sidecar': {'template_id': 'time_to_event_risk_group_summary', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.18, 'y0': 0.92, 'x1': 0.34, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.02, 'y0': 0.2, 'x1': 0.06, 'y1': 0.72}, {'box_id': 'panel_right_x_axis_title', 'box_type': 'subplot_x_axis_title', 'x0': 0.6, 'y0': 0.92, 'x1': 0.76, 'y1': 0.97}, {'box_id': 'panel_right_y_axis_title', 'box_type': 'subplot_y_axis_title', 'x0': 0.5, 'y0': 0.2, 'x1': 0.54, 'y1': 0.72}, {'box_id': 'panel_left_title', 'box_type': 'panel_title', 'x0': 0.16, 'y0': 0.11, 'x1': 0.34, 'y1': 0.15}, {'box_id': 'panel_right_title', 'box_type': 'panel_title', 'x0': 0.58, 'y0': 0.11, 'x1': 0.8, 'y1': 0.15}, {'box_id': 'panel_label_A', 'box_type': 'panel_label', 'x0': 0.11, 'y0': 0.8, 'x1': 0.14, 'y1': 0.85}, {'box_id': 'panel_label_B', 'box_type': 'panel_label', 'x0': 0.55, 'y0': 0.8, 'x1': 0.58, 'y1': 0.85}], 'panel_boxes': [{'box_id': 'panel_left', 'box_type': 'panel', 'x0': 0.1, 'y0': 0.16, 'x1': 0.44, 'y1': 0.86}, {'box_id': 'panel_right', 'box_type': 'panel', 'x0': 0.54, 'y0': 0.16, 'x1': 0.88, 'y1': 0.86}], 'guide_boxes': [], 'metrics': {'risk_group_summaries': [{'label': 'Low risk', 'sample_size': 80, 'events_5y': 2, 'mean_predicted_risk_5y': 0.02, 'observed_km_risk_5y': 0.02}, {'label': 'Intermediate risk', 'sample_size': 80, 'events_5y': 6, 'mean_predicted_risk_5y': 0.03, 'observed_km_risk_5y': 0.024}, {'label': 'High risk', 'sample_size': 80, 'events_5y': 10, 'mean_predicted_risk_5y': 0.04, 'observed_km_risk_5y': 0.028}]}, 'render_context': {'readability_override': {}}}, 'status': 'fail', 'rule_ids': ['observed_risk_spread_not_readable']},
    'test_run_display_layout_qc_flags_compressed_predicted_risk_spread_for_grouped_risk_summary': {'qc_profile': 'publication_survival_curve', 'layout_sidecar': {'template_id': 'time_to_event_risk_group_summary', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.18, 'y0': 0.92, 'x1': 0.34, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.02, 'y0': 0.2, 'x1': 0.06, 'y1': 0.72}, {'box_id': 'panel_right_x_axis_title', 'box_type': 'subplot_x_axis_title', 'x0': 0.6, 'y0': 0.92, 'x1': 0.76, 'y1': 0.97}, {'box_id': 'panel_right_y_axis_title', 'box_type': 'subplot_y_axis_title', 'x0': 0.5, 'y0': 0.2, 'x1': 0.54, 'y1': 0.72}, {'box_id': 'panel_left_title', 'box_type': 'panel_title', 'x0': 0.16, 'y0': 0.11, 'x1': 0.34, 'y1': 0.15}, {'box_id': 'panel_right_title', 'box_type': 'panel_title', 'x0': 0.58, 'y0': 0.11, 'x1': 0.8, 'y1': 0.15}, {'box_id': 'panel_label_A', 'box_type': 'panel_label', 'x0': 0.11, 'y0': 0.8, 'x1': 0.14, 'y1': 0.85}, {'box_id': 'panel_label_B', 'box_type': 'panel_label', 'x0': 0.55, 'y0': 0.8, 'x1': 0.58, 'y1': 0.85}], 'panel_boxes': [{'box_id': 'panel_left', 'box_type': 'panel', 'x0': 0.1, 'y0': 0.16, 'x1': 0.44, 'y1': 0.86}, {'box_id': 'panel_right', 'box_type': 'panel', 'x0': 0.54, 'y0': 0.16, 'x1': 0.88, 'y1': 0.86}], 'guide_boxes': [], 'metrics': {'risk_group_summaries': [{'label': 'Low risk', 'sample_size': 80, 'events_5y': 2, 'mean_predicted_risk_5y': 0.04, 'observed_km_risk_5y': 0.01}, {'label': 'Intermediate risk', 'sample_size': 80, 'events_5y': 6, 'mean_predicted_risk_5y': 0.042, 'observed_km_risk_5y': 0.03}, {'label': 'High risk', 'sample_size': 80, 'events_5y': 10, 'mean_predicted_risk_5y': 0.044, 'observed_km_risk_5y': 0.05}]}, 'render_context': {'readability_override': {}}}, 'status': 'fail', 'rule_ids': ['predicted_risk_spread_not_readable']},
    'test_run_display_layout_qc_honors_readability_override_for_grouped_risk_summary': {'qc_profile': 'publication_survival_curve', 'layout_sidecar': {'template_id': 'time_to_event_risk_group_summary', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.18, 'y0': 0.92, 'x1': 0.34, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.02, 'y0': 0.2, 'x1': 0.06, 'y1': 0.72}, {'box_id': 'panel_right_x_axis_title', 'box_type': 'subplot_x_axis_title', 'x0': 0.6, 'y0': 0.92, 'x1': 0.76, 'y1': 0.97}, {'box_id': 'panel_right_y_axis_title', 'box_type': 'subplot_y_axis_title', 'x0': 0.5, 'y0': 0.2, 'x1': 0.54, 'y1': 0.72}, {'box_id': 'panel_left_title', 'box_type': 'panel_title', 'x0': 0.16, 'y0': 0.11, 'x1': 0.34, 'y1': 0.15}, {'box_id': 'panel_right_title', 'box_type': 'panel_title', 'x0': 0.58, 'y0': 0.11, 'x1': 0.8, 'y1': 0.15}, {'box_id': 'panel_label_A', 'box_type': 'panel_label', 'x0': 0.11, 'y0': 0.8, 'x1': 0.14, 'y1': 0.85}, {'box_id': 'panel_label_B', 'box_type': 'panel_label', 'x0': 0.55, 'y0': 0.8, 'x1': 0.58, 'y1': 0.85}], 'panel_boxes': [{'box_id': 'panel_left', 'box_type': 'panel', 'x0': 0.1, 'y0': 0.16, 'x1': 0.44, 'y1': 0.86}, {'box_id': 'panel_right', 'box_type': 'panel', 'x0': 0.54, 'y0': 0.16, 'x1': 0.88, 'y1': 0.86}], 'guide_boxes': [], 'metrics': {'risk_group_summaries': [{'label': 'Low risk', 'sample_size': 80, 'events_5y': 2, 'mean_predicted_risk_5y': 0.02, 'observed_km_risk_5y': 0.01}, {'label': 'Intermediate risk', 'sample_size': 80, 'events_5y': 6, 'mean_predicted_risk_5y': 0.026, 'observed_km_risk_5y': 0.03}, {'label': 'High risk', 'sample_size': 80, 'events_5y': 10, 'mean_predicted_risk_5y': 0.032, 'observed_km_risk_5y': 0.05}]}, 'render_context': {'readability_override': {'minimum_predicted_risk_spread': 0.02}}}, 'status': 'fail', 'rule_ids': ['predicted_risk_spread_not_readable']},
    'test_run_display_layout_qc_fails_when_decision_curve_series_lengths_mismatch': {'qc_profile': 'publication_decision_curve', 'layout_sidecar': {'template_id': 'time_to_event_decision_curve', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'title', 'box_type': 'title', 'x0': 0.1, 'y0': 0.02, 'x1': 0.6, 'y1': 0.08}, {'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.32, 'y0': 0.92, 'x1': 0.62, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.01, 'y0': 0.24, 'x1': 0.06, 'y1': 0.7}], 'panel_boxes': [{'box_id': 'panel', 'box_type': 'panel', 'x0': 0.1, 'y0': 0.16, 'x1': 0.74, 'y1': 0.88}], 'guide_boxes': [{'box_id': 'legend', 'box_type': 'legend', 'x0': 0.78, 'y0': 0.28, 'x1': 0.96, 'y1': 0.46}], 'metrics': {'series': [{'label': '24-month horizon', 'x': [0.05, 0.2, 0.4], 'y': [0.16, 0.12]}], 'reference_line': {'x': [0.05, 0.45], 'y': [0.0, 0.0]}}}, 'status': 'fail', 'rule_ids': ['series_length_mismatch']},
    'test_run_display_layout_qc_fails_when_decision_curve_treated_fraction_panel_is_missing': {'qc_profile': 'publication_decision_curve', 'layout_sidecar': {'template_id': 'time_to_event_decision_curve', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'title', 'box_type': 'title', 'x0': 0.1, 'y0': 0.02, 'x1': 0.6, 'y1': 0.08}, {'box_id': 'panel_a_x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.18, 'y0': 0.88, 'x1': 0.36, 'y1': 0.92}, {'box_id': 'panel_a_y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.01, 'y0': 0.24, 'x1': 0.06, 'y1': 0.7}], 'panel_boxes': [{'box_id': 'panel_a', 'box_type': 'panel', 'x0': 0.1, 'y0': 0.16, 'x1': 0.46, 'y1': 0.82}], 'guide_boxes': [{'box_id': 'legend', 'box_type': 'legend', 'x0': 0.72, 'y0': 0.1, 'x1': 0.94, 'y1': 0.16}], 'metrics': {'series': [{'label': 'Model', 'x': [0.5, 1.0, 2.0], 'y': [0.03, 0.02, 0.01]}], 'reference_line': {'x': [0.5, 2.0], 'y': [0.0, 0.0]}, 'treated_fraction_series': {'label': 'Model', 'x': [0.5, 1.0, 2.0], 'y': [40.0, 20.0, 5.0]}}}, 'status': 'fail', 'rule_ids': ['treated_fraction_panel_missing']},
    'test_run_display_layout_qc_requires_structured_time_horizon_for_time_dependent_roc': {'qc_profile': 'publication_evidence_curve', 'layout_sidecar': {'template_id': 'time_dependent_roc_horizon', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.3, 'y0': 0.92, 'x1': 0.62, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.01, 'y0': 0.24, 'x1': 0.06, 'y1': 0.7}], 'panel_boxes': [{'box_id': 'panel', 'box_type': 'panel', 'x0': 0.1, 'y0': 0.16, 'x1': 0.74, 'y1': 0.88}], 'guide_boxes': [{'box_id': 'legend', 'box_type': 'legend', 'x0': 0.78, 'y0': 0.28, 'x1': 0.96, 'y1': 0.46}], 'metrics': {'title': 'Time-dependent ROC at 24 months', 'caption': 'Horizon-specific discrimination of the locked survival model at 24 months.', 'series': [{'label': '24-month horizon', 'x': [0.0, 0.25, 1.0], 'y': [0.0, 0.8, 1.0]}], 'reference_line': {'label': 'Chance', 'x': [0.0, 1.0], 'y': [0.0, 1.0]}}}, 'status': 'fail', 'rule_ids': ['time_horizon_months_missing']},
    'test_run_display_layout_qc_passes_for_time_dependent_roc_comparison_panel': {'qc_profile': 'publication_evidence_curve', 'layout_sidecar': {'template_id': 'time_dependent_roc_comparison_panel', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'title', 'box_type': 'title', 'x0': 0.18, 'y0': 0.02, 'x1': 0.82, 'y1': 0.08}, {'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.36, 'y0': 0.93, 'x1': 0.64, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.01, 'y0': 0.22, 'x1': 0.05, 'y1': 0.74}, {'box_id': 'panel_title_A', 'box_type': 'panel_title', 'x0': 0.14, 'y0': 0.1, 'x1': 0.34, 'y1': 0.14}, {'box_id': 'panel_title_B', 'box_type': 'panel_title', 'x0': 0.56, 'y0': 0.1, 'x1': 0.8, 'y1': 0.14}, {'box_id': 'panel_label_A', 'box_type': 'panel_label', 'x0': 0.11, 'y0': 0.79, 'x1': 0.14, 'y1': 0.84}, {'box_id': 'panel_label_B', 'box_type': 'panel_label', 'x0': 0.53, 'y0': 0.79, 'x1': 0.56, 'y1': 0.84}], 'panel_boxes': [{'box_id': 'panel_A', 'box_type': 'panel', 'x0': 0.1, 'y0': 0.22, 'x1': 0.43, 'y1': 0.86}, {'box_id': 'panel_B', 'box_type': 'panel', 'x0': 0.52, 'y0': 0.22, 'x1': 0.85, 'y1': 0.86}], 'guide_boxes': [{'box_id': 'legend', 'box_type': 'legend', 'x0': 0.28, 'y0': 0.03, 'x1': 0.67, 'y1': 0.12}], 'metrics': {'panels': [{'panel_id': 'overall_followup', 'panel_label': 'A', 'title': 'Overall follow-up', 'analysis_window_label': 'Overall follow-up', 'series': [{'label': 'Locked model', 'x': [0.0, 0.2, 0.5, 1.0], 'y': [0.0, 0.74, 0.88, 1.0]}, {'label': 'Clinical baseline', 'x': [0.0, 0.2, 0.5, 1.0], 'y': [0.0, 0.67, 0.82, 1.0]}], 'reference_line': {'label': 'Chance', 'x': [0.0, 1.0], 'y': [0.0, 1.0]}}, {'panel_id': 'first_15_years', 'panel_label': 'B', 'title': 'First 15 years of follow-up', 'analysis_window_label': 'First 15 years of follow-up', 'time_horizon_months': 180, 'series': [{'label': 'Locked model', 'x': [0.0, 0.2, 0.5, 1.0], 'y': [0.0, 0.78, 0.9, 1.0]}, {'label': 'Clinical baseline', 'x': [0.0, 0.2, 0.5, 1.0], 'y': [0.0, 0.7, 0.84, 1.0]}], 'reference_line': {'label': 'Chance', 'x': [0.0, 1.0], 'y': [0.0, 1.0]}}]}}, 'status': 'pass'},
    'test_run_display_layout_qc_uses_sanitized_panel_label_tokens_for_time_dependent_roc_comparison_panel': {'qc_profile': 'publication_evidence_curve', 'layout_sidecar': {'template_id': 'time_dependent_roc_comparison_panel', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'title', 'box_type': 'title', 'x0': 0.18, 'y0': 0.02, 'x1': 0.82, 'y1': 0.08}, {'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.36, 'y0': 0.93, 'x1': 0.64, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.01, 'y0': 0.22, 'x1': 0.05, 'y1': 0.74}, {'box_id': 'panel_title_A_1', 'box_type': 'panel_title', 'x0': 0.14, 'y0': 0.1, 'x1': 0.34, 'y1': 0.14}, {'box_id': 'panel_title_B_2', 'box_type': 'panel_title', 'x0': 0.56, 'y0': 0.1, 'x1': 0.8, 'y1': 0.14}, {'box_id': 'panel_label_A_1', 'box_type': 'panel_label', 'x0': 0.11, 'y0': 0.79, 'x1': 0.14, 'y1': 0.84}, {'box_id': 'panel_label_B_2', 'box_type': 'panel_label', 'x0': 0.53, 'y0': 0.79, 'x1': 0.56, 'y1': 0.84}], 'panel_boxes': [{'box_id': 'panel_A_1', 'box_type': 'panel', 'x0': 0.1, 'y0': 0.22, 'x1': 0.43, 'y1': 0.86}, {'box_id': 'panel_B_2', 'box_type': 'panel', 'x0': 0.52, 'y0': 0.22, 'x1': 0.85, 'y1': 0.86}], 'guide_boxes': [{'box_id': 'legend', 'box_type': 'legend', 'x0': 0.28, 'y0': 0.03, 'x1': 0.67, 'y1': 0.12}], 'metrics': {'panels': [{'panel_id': 'overall_followup', 'panel_label': 'A-1', 'title': 'Overall follow-up', 'analysis_window_label': 'Overall follow-up', 'series': [{'label': 'Locked model', 'x': [0.0, 0.2, 0.5, 1.0], 'y': [0.0, 0.74, 0.88, 1.0]}, {'label': 'Clinical baseline', 'x': [0.0, 0.2, 0.5, 1.0], 'y': [0.0, 0.67, 0.82, 1.0]}]}, {'panel_id': 'first_15_years', 'panel_label': 'B 2', 'title': 'First 15 years of follow-up', 'analysis_window_label': 'First 15 years of follow-up', 'time_horizon_months': 180, 'series': [{'label': 'Locked model', 'x': [0.0, 0.2, 0.5, 1.0], 'y': [0.0, 0.78, 0.9, 1.0]}, {'label': 'Clinical baseline', 'x': [0.0, 0.2, 0.5, 1.0], 'y': [0.0, 0.7, 0.84, 1.0]}]}]}}, 'status': 'pass'},
    'test_run_display_layout_qc_uses_sanitized_panel_label_tokens_for_stratified_cumulative_incidence_panel': {'qc_profile': 'publication_survival_curve', 'layout_sidecar': {'template_id': 'time_to_event_stratified_cumulative_incidence_panel', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'title', 'box_type': 'title', 'x0': 0.18, 'y0': 0.02, 'x1': 0.82, 'y1': 0.08}, {'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.34, 'y0': 0.94, 'x1': 0.66, 'y1': 0.98}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.01, 'y0': 0.22, 'x1': 0.05, 'y1': 0.74}, {'box_id': 'panel_title_A_1', 'box_type': 'panel_title', 'x0': 0.12, 'y0': 0.1, 'x1': 0.28, 'y1': 0.14}, {'box_id': 'panel_title_B_2', 'box_type': 'panel_title', 'x0': 0.41, 'y0': 0.1, 'x1': 0.57, 'y1': 0.14}, {'box_id': 'panel_title_C_3', 'box_type': 'panel_title', 'x0': 0.7, 'y0': 0.1, 'x1': 0.86, 'y1': 0.14}, {'box_id': 'panel_label_A_1', 'box_type': 'panel_label', 'x0': 0.09, 'y0': 0.79, 'x1': 0.12, 'y1': 0.84}, {'box_id': 'panel_label_B_2', 'box_type': 'panel_label', 'x0': 0.38, 'y0': 0.79, 'x1': 0.41, 'y1': 0.84}, {'box_id': 'panel_label_C_3', 'box_type': 'panel_label', 'x0': 0.67, 'y0': 0.79, 'x1': 0.7, 'y1': 0.84}], 'panel_boxes': [{'box_id': 'panel_A_1', 'box_type': 'panel', 'x0': 0.08, 'y0': 0.22, 'x1': 0.31, 'y1': 0.86}, {'box_id': 'panel_B_2', 'box_type': 'panel', 'x0': 0.37, 'y0': 0.22, 'x1': 0.6, 'y1': 0.86}, {'box_id': 'panel_C_3', 'box_type': 'panel', 'x0': 0.66, 'y0': 0.22, 'x1': 0.89, 'y1': 0.86}], 'guide_boxes': [], 'metrics': {'panels': [{'panel_id': 'baseline_htn', 'panel_label': 'A-1', 'title': 'Baseline hypertension status', 'groups': [{'label': 'HTN-AI+', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.08, 0.18]}, {'label': 'HTN-AI−', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.03, 0.08]}]}, {'panel_id': 'age_band', 'panel_label': 'B 2', 'title': 'Age band', 'groups': [{'label': 'Older', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.1, 0.22]}, {'label': 'Younger', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.02, 0.06]}]}, {'panel_id': 'htn_ai_quintile', 'panel_label': 'C/3', 'title': 'HTN-AI quintile', 'groups': [{'label': 'Q1', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.01, 0.04]}, {'label': 'Q5', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.1, 0.24]}]}]}, 'render_context': {'readability_override': {}}}, 'status': 'pass'},
    'test_run_display_layout_qc_fails_when_time_dependent_roc_comparison_panel_horizon_is_invalid': {'qc_profile': 'publication_evidence_curve', 'layout_sidecar': {'template_id': 'time_dependent_roc_comparison_panel', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'title', 'box_type': 'title', 'x0': 0.18, 'y0': 0.02, 'x1': 0.82, 'y1': 0.08}, {'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.36, 'y0': 0.93, 'x1': 0.64, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.01, 'y0': 0.22, 'x1': 0.05, 'y1': 0.74}, {'box_id': 'panel_title_A', 'box_type': 'panel_title', 'x0': 0.14, 'y0': 0.1, 'x1': 0.34, 'y1': 0.14}, {'box_id': 'panel_title_B', 'box_type': 'panel_title', 'x0': 0.56, 'y0': 0.1, 'x1': 0.8, 'y1': 0.14}, {'box_id': 'panel_label_A', 'box_type': 'panel_label', 'x0': 0.11, 'y0': 0.79, 'x1': 0.14, 'y1': 0.84}, {'box_id': 'panel_label_B', 'box_type': 'panel_label', 'x0': 0.53, 'y0': 0.79, 'x1': 0.56, 'y1': 0.84}], 'panel_boxes': [{'box_id': 'panel_A', 'box_type': 'panel', 'x0': 0.1, 'y0': 0.22, 'x1': 0.43, 'y1': 0.86}, {'box_id': 'panel_B', 'box_type': 'panel', 'x0': 0.52, 'y0': 0.22, 'x1': 0.85, 'y1': 0.86}], 'guide_boxes': [{'box_id': 'legend', 'box_type': 'legend', 'x0': 0.28, 'y0': 0.03, 'x1': 0.67, 'y1': 0.12}], 'metrics': {'panels': [{'panel_id': 'overall_followup', 'panel_label': 'A', 'title': 'Overall follow-up', 'analysis_window_label': 'Overall follow-up', 'series': [{'label': 'Locked model', 'x': [0.0, 0.2, 0.5, 1.0], 'y': [0.0, 0.74, 0.88, 1.0]}, {'label': 'Clinical baseline', 'x': [0.0, 0.2, 0.5, 1.0], 'y': [0.0, 0.67, 0.82, 1.0]}], 'reference_line': {'label': 'Chance', 'x': [0.0, 1.0], 'y': [0.0, 1.0]}}, {'panel_id': 'first_15_years', 'panel_label': 'B', 'title': 'First 15 years of follow-up', 'analysis_window_label': 'First 15 years of follow-up', 'time_horizon_months': 0, 'series': [{'label': 'Locked model', 'x': [0.0, 0.2, 0.5, 1.0], 'y': [0.0, 0.78, 0.9, 1.0]}, {'label': 'Clinical baseline', 'x': [0.0, 0.2, 0.5, 1.0], 'y': [0.0, 0.7, 0.84, 1.0]}], 'reference_line': {'label': 'Chance', 'x': [0.0, 1.0], 'y': [0.0, 1.0]}}]}}, 'status': 'fail', 'rule_ids': ['panel_time_horizon_months_invalid']},
    'test_run_display_layout_qc_fails_when_risk_group_summary_panel_labels_are_missing': {'qc_profile': 'publication_survival_curve', 'layout_sidecar': {'template_id': 'time_to_event_risk_group_summary', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.18, 'y0': 0.92, 'x1': 0.34, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.02, 'y0': 0.2, 'x1': 0.06, 'y1': 0.72}, {'box_id': 'panel_right_x_axis_title', 'box_type': 'subplot_x_axis_title', 'x0': 0.6, 'y0': 0.92, 'x1': 0.76, 'y1': 0.97}, {'box_id': 'panel_right_y_axis_title', 'box_type': 'subplot_y_axis_title', 'x0': 0.5, 'y0': 0.2, 'x1': 0.54, 'y1': 0.72}, {'box_id': 'panel_left_title', 'box_type': 'panel_title', 'x0': 0.16, 'y0': 0.11, 'x1': 0.34, 'y1': 0.15}, {'box_id': 'panel_right_title', 'box_type': 'panel_title', 'x0': 0.58, 'y0': 0.11, 'x1': 0.8, 'y1': 0.15}], 'panel_boxes': [{'box_id': 'panel_left', 'box_type': 'panel', 'x0': 0.1, 'y0': 0.16, 'x1': 0.44, 'y1': 0.86}, {'box_id': 'panel_right', 'box_type': 'panel', 'x0': 0.54, 'y0': 0.16, 'x1': 0.88, 'y1': 0.86}], 'guide_boxes': [], 'metrics': {'risk_group_summaries': [{'label': 'Low risk', 'sample_size': 72, 'events_5y': 4, 'mean_predicted_risk_5y': 0.08, 'observed_km_risk_5y': 0.06}, {'label': 'High risk', 'sample_size': 48, 'events_5y': 19, 'mean_predicted_risk_5y': 0.31, 'observed_km_risk_5y': 0.35}]}, 'render_context': {'readability_override': {}}}, 'status': 'fail', 'rule_ids': ['missing_panel_label']},
    'test_run_display_layout_qc_passes_for_stratified_cumulative_incidence_panel': {'qc_profile': 'publication_survival_curve', 'layout_sidecar': {'template_id': 'time_to_event_stratified_cumulative_incidence_panel', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'title', 'box_type': 'title', 'x0': 0.18, 'y0': 0.02, 'x1': 0.82, 'y1': 0.08}, {'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.34, 'y0': 0.94, 'x1': 0.66, 'y1': 0.98}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.01, 'y0': 0.22, 'x1': 0.05, 'y1': 0.74}, {'box_id': 'panel_title_A', 'box_type': 'panel_title', 'x0': 0.12, 'y0': 0.1, 'x1': 0.28, 'y1': 0.14}, {'box_id': 'panel_title_B', 'box_type': 'panel_title', 'x0': 0.41, 'y0': 0.1, 'x1': 0.57, 'y1': 0.14}, {'box_id': 'panel_title_C', 'box_type': 'panel_title', 'x0': 0.7, 'y0': 0.1, 'x1': 0.86, 'y1': 0.14}, {'box_id': 'panel_label_A', 'box_type': 'panel_label', 'x0': 0.09, 'y0': 0.79, 'x1': 0.12, 'y1': 0.84}, {'box_id': 'panel_label_B', 'box_type': 'panel_label', 'x0': 0.38, 'y0': 0.79, 'x1': 0.41, 'y1': 0.84}, {'box_id': 'panel_label_C', 'box_type': 'panel_label', 'x0': 0.67, 'y0': 0.79, 'x1': 0.7, 'y1': 0.84}], 'panel_boxes': [{'box_id': 'panel_A', 'box_type': 'panel', 'x0': 0.08, 'y0': 0.22, 'x1': 0.31, 'y1': 0.86}, {'box_id': 'panel_B', 'box_type': 'panel', 'x0': 0.37, 'y0': 0.22, 'x1': 0.6, 'y1': 0.86}, {'box_id': 'panel_C', 'box_type': 'panel', 'x0': 0.66, 'y0': 0.22, 'x1': 0.89, 'y1': 0.86}], 'guide_boxes': [], 'metrics': {'panels': [{'panel_id': 'baseline_htn', 'panel_label': 'A', 'title': 'Baseline hypertension status', 'groups': [{'label': 'HTN-AI+', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.08, 0.18]}, {'label': 'HTN-AI−', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.03, 0.08]}]}, {'panel_id': 'age_band', 'panel_label': 'B', 'title': 'Age band', 'groups': [{'label': 'Older', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.1, 0.22]}, {'label': 'Younger', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.02, 0.06]}]}, {'panel_id': 'htn_ai_quintile', 'panel_label': 'C', 'title': 'HTN-AI quintile', 'groups': [{'label': 'Q1', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.01, 0.04]}, {'label': 'Q5', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.1, 0.24]}]}]}, 'render_context': {'readability_override': {}}}, 'status': 'pass'},
    'test_run_display_layout_qc_fails_when_stratified_cumulative_incidence_panel_labels_are_missing': {'qc_profile': 'publication_survival_curve', 'layout_sidecar': {'template_id': 'time_to_event_stratified_cumulative_incidence_panel', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'title', 'box_type': 'title', 'x0': 0.18, 'y0': 0.02, 'x1': 0.82, 'y1': 0.08}, {'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.34, 'y0': 0.94, 'x1': 0.66, 'y1': 0.98}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.01, 'y0': 0.22, 'x1': 0.05, 'y1': 0.74}, {'box_id': 'panel_title_A', 'box_type': 'panel_title', 'x0': 0.12, 'y0': 0.1, 'x1': 0.28, 'y1': 0.14}, {'box_id': 'panel_title_B', 'box_type': 'panel_title', 'x0': 0.41, 'y0': 0.1, 'x1': 0.57, 'y1': 0.14}, {'box_id': 'panel_title_C', 'box_type': 'panel_title', 'x0': 0.7, 'y0': 0.1, 'x1': 0.86, 'y1': 0.14}, {'box_id': 'panel_label_A', 'box_type': 'panel_label', 'x0': 0.09, 'y0': 0.79, 'x1': 0.12, 'y1': 0.84}, {'box_id': 'panel_label_B', 'box_type': 'panel_label', 'x0': 0.38, 'y0': 0.79, 'x1': 0.41, 'y1': 0.84}], 'panel_boxes': [{'box_id': 'panel_A', 'box_type': 'panel', 'x0': 0.08, 'y0': 0.22, 'x1': 0.31, 'y1': 0.86}, {'box_id': 'panel_B', 'box_type': 'panel', 'x0': 0.37, 'y0': 0.22, 'x1': 0.6, 'y1': 0.86}, {'box_id': 'panel_C', 'box_type': 'panel', 'x0': 0.66, 'y0': 0.22, 'x1': 0.89, 'y1': 0.86}], 'guide_boxes': [], 'metrics': {'panels': [{'panel_id': 'baseline_htn', 'panel_label': 'A', 'title': 'Baseline hypertension status', 'groups': [{'label': 'HTN-AI+', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.08, 0.18]}, {'label': 'HTN-AI−', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.03, 0.08]}]}, {'panel_id': 'age_band', 'panel_label': 'B', 'title': 'Age band', 'groups': [{'label': 'Older', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.1, 0.22]}, {'label': 'Younger', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.02, 0.06]}]}, {'panel_id': 'htn_ai_quintile', 'panel_label': 'C', 'title': 'HTN-AI quintile', 'groups': [{'label': 'Q1', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.01, 0.04]}, {'label': 'Q5', 'times': [0.0, 1.0, 2.0], 'values': [0.0, 0.1, 0.24]}]}]}, 'render_context': {'readability_override': {}}}, 'status': 'fail', 'rule_ids': ['missing_panel_label']},
    'test_run_display_layout_qc_fails_when_decision_curve_panel_label_anchor_drifts': {'qc_profile': 'publication_decision_curve', 'layout_sidecar': {'template_id': 'time_to_event_decision_curve', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'title', 'box_type': 'title', 'x0': 0.1, 'y0': 0.02, 'x1': 0.6, 'y1': 0.08}, {'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.16, 'y0': 0.92, 'x1': 0.34, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.02, 'y0': 0.2, 'x1': 0.06, 'y1': 0.72}, {'box_id': 'panel_right_x_axis_title', 'box_type': 'subplot_x_axis_title', 'x0': 0.62, 'y0': 0.92, 'x1': 0.8, 'y1': 0.97}, {'box_id': 'panel_right_y_axis_title', 'box_type': 'subplot_y_axis_title', 'x0': 0.54, 'y0': 0.2, 'x1': 0.58, 'y1': 0.72}, {'box_id': 'panel_left_title', 'box_type': 'panel_title', 'x0': 0.18, 'y0': 0.11, 'x1': 0.34, 'y1': 0.15}, {'box_id': 'panel_right_title', 'box_type': 'panel_title', 'x0': 0.62, 'y0': 0.11, 'x1': 0.8, 'y1': 0.15}, {'box_id': 'panel_label_A', 'box_type': 'panel_label', 'x0': 0.11, 'y0': 0.8, 'x1': 0.14, 'y1': 0.85}, {'box_id': 'panel_label_B', 'box_type': 'panel_label', 'x0': 0.74, 'y0': 0.64, 'x1': 0.77, 'y1': 0.69}], 'panel_boxes': [{'box_id': 'panel_left', 'box_type': 'panel', 'x0': 0.1, 'y0': 0.16, 'x1': 0.44, 'y1': 0.86}, {'box_id': 'panel_right', 'box_type': 'panel', 'x0': 0.56, 'y0': 0.16, 'x1': 0.9, 'y1': 0.86}], 'guide_boxes': [{'box_id': 'legend', 'box_type': 'legend', 'x0': 0.34, 'y0': 0.02, 'x1': 0.66, 'y1': 0.08}], 'metrics': {'series': [{'label': 'Model', 'x': [0.5, 1.0, 2.0], 'y': [0.03, 0.02, 0.01]}], 'reference_line': {'x': [0.5, 2.0], 'y': [0.0, 0.0]}, 'treated_fraction_series': {'label': 'Model', 'x': [0.5, 1.0, 2.0], 'y': [40.0, 20.0, 5.0]}}}, 'status': 'fail', 'rule_ids': ['panel_label_anchor_drift']},
    'test_run_display_layout_qc_fails_when_correlation_matrix_is_not_symmetric': {'qc_profile': 'publication_heatmap', 'layout_sidecar': {'template_id': 'correlation_heatmap', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.28, 'y0': 0.92, 'x1': 0.64, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.02, 'y0': 0.22, 'x1': 0.06, 'y1': 0.68}], 'panel_boxes': [{'box_id': 'panel', 'box_type': 'heatmap_tile_region', 'x0': 0.12, 'y0': 0.16, 'x1': 0.74, 'y1': 0.86}], 'guide_boxes': [{'box_id': 'colorbar', 'box_type': 'colorbar', 'x0': 0.8, 'y0': 0.18, 'x1': 0.9, 'y1': 0.82}], 'metrics': {'matrix_cells': [{'x': 'A', 'y': 'A', 'value': 1.0}, {'x': 'A', 'y': 'B', 'value': 0.42}, {'x': 'B', 'y': 'A', 'value': 0.31}, {'x': 'B', 'y': 'B', 'value': 1.0}]}}, 'status': 'fail', 'rule_ids': ['matrix_not_symmetric']},
    'test_run_display_layout_qc_fails_when_performance_heatmap_value_is_out_of_range': {'qc_profile': 'publication_heatmap', 'layout_sidecar': {'template_id': 'performance_heatmap', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.28, 'y0': 0.92, 'x1': 0.64, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.02, 'y0': 0.22, 'x1': 0.06, 'y1': 0.68}], 'panel_boxes': [{'box_id': 'panel', 'box_type': 'heatmap_tile_region', 'x0': 0.12, 'y0': 0.16, 'x1': 0.74, 'y1': 0.86}], 'guide_boxes': [{'box_id': 'colorbar', 'box_type': 'colorbar', 'x0': 0.8, 'y0': 0.18, 'x1': 0.9, 'y1': 0.82}], 'metrics': {'metric_name': 'AUC', 'matrix_cells': [{'x': 'All participants', 'y': 'Clinical baseline', 'value': 0.72}, {'x': 'All participants', 'y': 'Integrated model', 'value': 1.04}, {'x': 'APOE4 carriers', 'y': 'Clinical baseline', 'value': 0.68}, {'x': 'APOE4 carriers', 'y': 'Integrated model', 'value': 0.81}]}}, 'status': 'fail', 'rule_ids': ['performance_value_out_of_range']},
    'test_run_display_layout_qc_fails_when_confusion_matrix_row_fraction_does_not_sum_to_one': {'qc_profile': 'publication_heatmap', 'layout_sidecar': {'template_id': 'confusion_matrix_heatmap_binary', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'x_axis_title', 'box_type': 'x_axis_title', 'x0': 0.28, 'y0': 0.92, 'x1': 0.64, 'y1': 0.97}, {'box_id': 'y_axis_title', 'box_type': 'y_axis_title', 'x0': 0.02, 'y0': 0.22, 'x1': 0.06, 'y1': 0.68}], 'panel_boxes': [{'box_id': 'panel', 'box_type': 'heatmap_tile_region', 'x0': 0.12, 'y0': 0.16, 'x1': 0.74, 'y1': 0.86}], 'guide_boxes': [{'box_id': 'colorbar', 'box_type': 'colorbar', 'x0': 0.8, 'y0': 0.18, 'x1': 0.9, 'y1': 0.82}], 'metrics': {'metric_name': 'Observed proportion', 'normalization': 'row_fraction', 'matrix_cells': [{'x': 'Predicted negative', 'y': 'Observed negative', 'value': 0.81}, {'x': 'Predicted positive', 'y': 'Observed negative', 'value': 0.12}, {'x': 'Predicted negative', 'y': 'Observed positive', 'value': 0.21}, {'x': 'Predicted positive', 'y': 'Observed positive', 'value': 0.83}]}}, 'status': 'fail', 'rule_ids': ['confusion_row_sum_invalid']},
    'test_run_display_layout_qc_passes_for_pathway_enrichment_dotplot_panel': {'qc_profile': 'publication_pathway_enrichment_dotplot_panel', 'layout_sidecar': {'template_id': 'pathway_enrichment_dotplot_panel', 'device': {'x0': 0.0, 'y0': 0.0, 'x1': 1.0, 'y1': 1.0}, 'layout_boxes': [{'box_id': 'panel_title_A', 'box_type': 'panel_title', 'x0': 0.1, 'y0': 0.86, 'x1': 0.28, 'y1': 0.89}, {'box_id': 'panel_title_B', 'box_type': 'panel_title', 'x0': 0.52, 'y0': 0.86, 'x1': 0.68, 'y1': 0.89}, {'box_id': 'panel_label_A', 'box_type': 'panel_label', 'x0': 0.1, 'y0': 0.76, 'x1': 0.12, 'y1': 0.79}, {'box_id': 'panel_label_B', 'box_type': 'panel_label', 'x0': 0.52, 'y0': 0.76, 'x1': 0.54, 'y1': 0.79}, {'box_id': 'x_axis_title_A', 'box_type': 'subplot_x_axis_title', 'x0': 0.14, 'y0': 0.1, 'x1': 0.3, 'y1': 0.13}, {'box_id': 'x_axis_title_B', 'box_type': 'subplot_x_axis_title', 'x0': 0.56, 'y0': 0.1, 'x1': 0.72, 'y1': 0.13}, {'box_id': 'y_axis_title', 'box_type': 'subplot_y_axis_title', 'x0': 0.03, 'y0': 0.36, 'x1': 0.06, 'y1': 0.66}], 'panel_boxes': [{'box_id': 'panel_A', 'box_type': 'panel', 'x0': 0.1, 'y0': 0.18, 'x1': 0.42, 'y1': 0.8}, {'box_id': 'panel_B', 'box_type': 'panel', 'x0': 0.52, 'y0': 0.18, 'x1': 0.84, 'y1': 0.8}], 'guide_boxes': [{'box_id': 'legend', 'box_type': 'legend', 'x0': 0.26, 'y0': 0.02, 'x1': 0.56, 'y1': 0.08}, {'box_id': 'colorbar', 'box_type': 'colorbar', 'x0': 0.88, 'y0': 0.2, 'x1': 0.92, 'y1': 0.76}], 'metrics': {'effect_scale_label': 'Directionality score', 'size_scale_label': 'Gene count', 'pathway_labels': ['IFN response', 'EMT signaling', 'Cell cycle'], 'panels': [{'panel_id': 'transcriptome', 'panel_title': 'Transcriptome', 'panel_label': 'A', 'panel_box_id': 'panel_A', 'panel_label_box_id': 'panel_label_A', 'panel_title_box_id': 'panel_title_A', 'x_axis_title_box_id': 'x_axis_title_A', 'points': [{'pathway_label': 'IFN response', 'x': 0.28, 'y': 0.68, 'size_value': 34.0, 'effect_value': 0.91}, {'pathway_label': 'EMT signaling', 'x': 0.22, 'y': 0.5, 'size_value': 22.0, 'effect_value': 0.42}, {'pathway_label': 'Cell cycle', 'x': 0.31, 'y': 0.32, 'size_value': 29.0, 'effect_value': 0.76}]}, {'panel_id': 'proteome', 'panel_title': 'Proteome', 'panel_label': 'B', 'panel_box_id': 'panel_B', 'panel_label_box_id': 'panel_label_B', 'panel_title_box_id': 'panel_title_B', 'x_axis_title_box_id': 'x_axis_title_B', 'points': [{'pathway_label': 'IFN response', 'x': 0.64, 'y': 0.68, 'size_value': 26.0, 'effect_value': 0.64}, {'pathway_label': 'EMT signaling', 'x': 0.72, 'y': 0.5, 'size_value': 31.0, 'effect_value': 0.88}, {'pathway_label': 'Cell cycle', 'x': 0.61, 'y': 0.32, 'size_value': 19.0, 'effect_value': 0.37}]}]}}, 'status': 'pass', 'no_issues': True},
}

def test_run_display_layout_qc_flags_compressed_observed_risk_spread_for_grouped_risk_summary() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_flags_compressed_observed_risk_spread_for_grouped_risk_summary'])

def test_run_display_layout_qc_flags_compressed_predicted_risk_spread_for_grouped_risk_summary() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_flags_compressed_predicted_risk_spread_for_grouped_risk_summary'])

def test_run_display_layout_qc_honors_readability_override_for_grouped_risk_summary() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_honors_readability_override_for_grouped_risk_summary'])

def test_run_display_layout_qc_fails_when_decision_curve_series_lengths_mismatch() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_fails_when_decision_curve_series_lengths_mismatch'])

def test_run_display_layout_qc_fails_when_decision_curve_treated_fraction_panel_is_missing() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_fails_when_decision_curve_treated_fraction_panel_is_missing'])

def test_run_display_layout_qc_requires_structured_time_horizon_for_time_dependent_roc() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_requires_structured_time_horizon_for_time_dependent_roc'])

def test_run_display_layout_qc_passes_for_time_dependent_roc_comparison_panel() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_passes_for_time_dependent_roc_comparison_panel'])

def test_run_display_layout_qc_uses_sanitized_panel_label_tokens_for_time_dependent_roc_comparison_panel() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_uses_sanitized_panel_label_tokens_for_time_dependent_roc_comparison_panel'])

def test_run_display_layout_qc_uses_sanitized_panel_label_tokens_for_stratified_cumulative_incidence_panel() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_uses_sanitized_panel_label_tokens_for_stratified_cumulative_incidence_panel'])

def test_run_display_layout_qc_fails_when_time_dependent_roc_comparison_panel_horizon_is_invalid() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_fails_when_time_dependent_roc_comparison_panel_horizon_is_invalid'])

def test_run_display_layout_qc_fails_when_risk_group_summary_panel_labels_are_missing() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_fails_when_risk_group_summary_panel_labels_are_missing'])

def test_run_display_layout_qc_passes_for_stratified_cumulative_incidence_panel() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_passes_for_stratified_cumulative_incidence_panel'])

def test_run_display_layout_qc_fails_when_stratified_cumulative_incidence_panel_labels_are_missing() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_fails_when_stratified_cumulative_incidence_panel_labels_are_missing'])

def test_run_display_layout_qc_fails_when_decision_curve_panel_label_anchor_drifts() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_fails_when_decision_curve_panel_label_anchor_drifts'])

def test_run_display_layout_qc_fails_when_correlation_matrix_is_not_symmetric() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_fails_when_correlation_matrix_is_not_symmetric'])

def test_run_display_layout_qc_fails_when_performance_heatmap_value_is_out_of_range() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_fails_when_performance_heatmap_value_is_out_of_range'])

def test_run_display_layout_qc_fails_when_confusion_matrix_row_fraction_does_not_sum_to_one() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_fails_when_confusion_matrix_row_fraction_does_not_sum_to_one'])

def test_run_display_layout_qc_passes_for_pathway_enrichment_dotplot_panel() -> None:
    run_layout_qc_case(CASES['test_run_display_layout_qc_passes_for_pathway_enrichment_dotplot_panel'])
