from __future__ import annotations

from tests.paper_mission_authority_handler_v2_cases.currentness_and_selected_build_cases import *
from tests.paper_mission_authority_handler_v2_cases.generation_and_professional_quality_cases import *
from tests.paper_mission_authority_handler_v2_cases.revision_and_review_scope_cases import *
from tests.paper_mission_authority_handler_v2_cases.epistemic_currentness_cases import *
from tests.paper_mission_authority_handler_v2_cases.finalize_and_schema_cases import *
