from __future__ import annotations

from tests.test_provider_admission_current_control_cases.current_control_action_identity_cases import (
    test_current_control_provider_admission_rejects_queue_without_current_identity,
    test_current_control_provider_admission_rejects_root_action_queue_identity_under_typed_blocker,
    test_current_control_provider_admission_rejects_action_queue_self_identity_under_typed_blocker,
    test_current_control_provider_admission_uses_study_current_work_unit_identity,
    test_current_control_provider_admission_uses_study_current_action_when_top_level_queue_empty,
)
from tests.test_provider_admission_current_control_cases.current_control_transition_request_cases import (
    test_current_control_provider_admission_reads_transition_request_path_without_legacy_dispatch_ref,
    test_current_control_provider_admission_defaults_missing_carrier_to_transition_request_path,
)
from tests.test_provider_admission_current_control_cases.current_control_write_owner_cases import (
    test_current_control_provider_admission_allows_write_owner_gate_clearing_target,
    test_current_control_provider_admission_rejects_write_owner_gate_clearing_without_strong_identity,
    test_current_control_provider_admission_allows_write_quality_repair_from_study_current_action,
    test_provider_admission_candidate_never_promotes_provider_completion_to_domain_completion,
)
from tests.test_provider_admission_current_control_cases.current_identity_cases import (
    test_provider_admission_current_control_prefers_live_attempt_over_pending_candidate,
    test_provider_admission_current_control_uses_worker_liveness_as_running_gate,
    test_provider_admission_uses_explicit_action_queue_identity_over_stale_status_noise,
    test_provider_admission_uses_fresh_repair_progress_action_over_stale_current_control_study,
    test_provider_admission_rejects_same_fingerprint_with_stale_action_identity,
    test_provider_admission_execution_requires_current_identity_for_current_control_status,
)
from tests.test_provider_admission_current_control_cases.owner_gate_route_back_cases import (
    test_provider_admission_report_does_not_admit_owner_gate_route_back_without_explicit_allow,
)
from tests.test_provider_admission_current_control_cases.provider_admission_report_identity_cases import (
    test_provider_admission_report_accepts_record_only_owner_refs_closeout_without_top_level_fingerprint_when_currentness_matches,
    test_provider_admission_report_preserves_action_fingerprint_from_owner_route_basis,
    test_provider_admission_report_identity_prefers_identity_different_current_owner_action,
)
from tests.test_provider_admission_current_control_cases.queue_candidate_cases import (
    test_provider_admission_candidate_from_current_control_ai_reviewer_queue_cannot_self_clear_readiness_blocker,
    test_provider_admission_candidate_from_current_control_gate_clearing_queue_cannot_self_clear_stale_blocker,
    test_provider_admission_candidate_carries_top_level_work_unit_identity_from_transition_request,
)
