from __future__ import annotations

from .test_gate_clearing_batch_cases import shared as _shared

globals().update({
    name: value
    for name, value in vars(_shared).items()
    if not name.startswith('__')
})

from .test_gate_clearing_batch_cases.planning_and_replay import (
    annotations,
    test_submission_minimal_fingerprint_payload_ignores_materialized_submission_source_from_compile_report,
    test_submission_minimal_fingerprint_payload_uses_compile_report_resolver_for_recursive_manifest_path,
    test_execute_repair_units_treats_all_skipped_dependents_as_terminal_state,
    test_parse_json_object_from_cli_stdout_ignores_launcher_preamble,
    test_build_gate_clearing_batch_recommended_action_promotes_blocked_bounded_analysis,
    test_build_gate_clearing_batch_recommended_action_uses_managed_runtime_quest_root,
    test_build_gate_clearing_batch_recommended_action_uses_surface_blocker_details,
    test_build_gate_clearing_batch_recommended_action_promotes_bundle_stage_return_to_finalize,
    test_build_gate_clearing_batch_recommended_action_widens_bounded_analysis_to_submission_refresh,
    test_run_gate_clearing_batch_executes_parallel_units_then_replays_gate,
    test_run_gate_clearing_batch_waits_for_live_path_repair_before_display_refresh,
    test_run_gate_clearing_batch_executes_bundle_stage_submission_refresh_then_replays_gate,
    test_run_gate_clearing_batch_refreshes_stale_submission_minimal_authority_without_bundle_stage_override,
    test_run_gate_clearing_batch_replays_gate_when_stale_authority_signature_is_current,
    test_run_gate_clearing_batch_executes_bundle_stage_workspace_refresh_before_submission_replay,
    test_run_gate_clearing_batch_syncs_stale_submission_delivery_after_bundle_refresh,
    test_run_gate_clearing_batch_reuses_embedded_submission_delivery_sync_after_bundle_refresh,
)
from .test_gate_clearing_batch_cases.live_path_and_summary import (
    test_run_gate_clearing_batch_executes_delivery_refresh_fast_lane_for_stale_projection_only,
    test_run_gate_clearing_batch_skips_repair_units_when_unit_fingerprints_match_latest_record,
    test_run_gate_clearing_batch_skips_submission_refresh_only_when_inputs_match_and_previous_run_succeeded,
    test_run_gate_clearing_batch_reruns_submission_refresh_when_previous_matching_run_failed,
    test_run_gate_clearing_batch_reruns_delivery_sync_when_previous_matching_run_was_route_blocked,
    test_run_gate_clearing_batch_reruns_submission_refresh_when_quality_inputs_change,
    test_run_gate_clearing_batch_reruns_submission_refresh_when_submission_outputs_disappear,
    test_run_gate_clearing_batch_rebuilds_submission_minimal_when_delivery_surface_reports_missing_source,
    test_run_gate_clearing_batch_authorizes_submission_refresh_from_selected_work_unit,
)
from .test_gate_clearing_batch_cases.outer_loop_controller_action import (
    test_study_outer_loop_executes_gate_clearing_batch_controller_action,
)
from .test_gate_clearing_batch_cases.publication_work_unit_routing import (
    test_next_work_unit_filter_preserves_submission_refresh_dependency_closure,
    test_publication_work_units_compose_controller_owned_quality_repair_unit_for_mixed_surface_blockers,
    test_current_owner_work_units_do_not_pull_submission_materialization_into_gate_clearing,
    test_next_work_unit_limits_gate_clearing_batch_to_analysis_repair_without_submission_refresh,
    test_analysis_repair_keeps_submission_refresh_for_finalize_work_unit,
    test_current_controller_decision_work_unit_preempts_stale_publication_eval_selection,
    test_gate_clearing_batch_records_display_materialization_failure_refs,
    test_gate_clearing_batch_records_step_durations_with_monkeypatched_clock,
)
from .test_gate_clearing_batch_cases.startup_freshness_priority import (
    test_startup_freshness_work_unit_dominates_repairable_surface_without_eval_analysis_action,
)
from .test_gate_clearing_batch_cases.publication_work_unit_currentness import (
    test_gate_clearing_batch_treats_explicit_gate_specificity_as_platform_terminal,
    test_gate_clearing_batch_does_not_reuse_stale_explicit_analysis_when_current_gate_needs_specificity,
    test_publication_work_unit_selection_keeps_explicit_upstream_repair_ahead_of_delivery_redrive,
    test_publication_work_unit_selection_supersedes_gate_specificity_after_targets_are_complete,
    test_publication_gate_replay_selects_current_submission_authority_closure,
    test_clear_gate_replay_keeps_unsettled_authority_sync_open,
    test_clear_gate_replay_closes_settled_authority_sync,
    test_duplicate_closed_gate_batch_normalizes_stale_lifecycle,
    test_duplicate_authority_sync_batch_closes_when_current_gate_settles_delivery,
    test_duplicate_closed_batch_refreshes_when_ai_reviewer_quality_authority_changes,
)
from .test_gate_clearing_batch_cases.current_package_freshness import (
    test_current_authority_stale_delivery_syncs_then_closes_gate_replay,
    test_explicit_gate_specificity_does_not_block_actionable_stale_delivery_sync,
    test_blocked_delivery_sync_clears_stale_current_package_freshness_proof,
    test_pending_clean_paper_authority_cutover_blocks_gate_report_freshness_proof,
    test_skipped_matching_delivery_unit_without_result_does_not_write_freshness_proof,
    test_current_delivery_gate_report_writes_freshness_proof_without_resync,
    test_current_delivery_gate_report_without_rendered_pdf_does_not_write_freshness_proof,
    test_current_delivery_gate_report_without_clear_visual_audit_does_not_write_freshness_proof,
    test_current_delivery_gate_report_with_missing_paths_does_not_write_freshness_proof,
    test_current_delivery_gate_report_accepts_contract_backed_visual_audit_receipt,
    test_current_delivery_gate_report_with_stale_visual_audit_does_not_write_freshness_proof,
    test_gate_clearing_batch_prefers_replay_report_for_current_delivery_freshness,
    test_closed_gate_clearing_batch_backfills_missing_freshness_proof_from_replay_report,
    test_closed_gate_clearing_batch_rejects_embedded_proof_without_stable_proof_path,
)
from .test_gate_clearing_batch_cases.authority_settle_redrive import (
    test_authority_settle_redrive_syncs_delivery_without_recreating_package,
    test_authority_settle_redrive_syncs_delivery_for_bundle_stage_retry_without_delivery_status,
)
from .test_gate_clearing_batch_cases.submission_authority_sync import (
    test_run_gate_clearing_batch_refreshes_submission_hardening_without_live_path_repair,
    test_run_gate_clearing_batch_closes_submission_authority_sync_with_delivery_sync,
    test_run_gate_clearing_batch_redrives_delivery_sync_after_authority_settle_without_recreating_package,
    test_run_gate_clearing_batch_redrives_delivery_sync_for_mechanical_eval_id_drift,
    test_run_gate_clearing_batch_reruns_same_eval_after_failed_submission_hardening_batch,
)
from .test_gate_clearing_batch_cases.direct_migration_display_refresh import (
    test_run_gate_clearing_batch_rematerializes_stale_direct_migration_display_inputs_before_display_refresh,
    test_run_gate_clearing_batch_routes_historical_feature_shift_f5_payload_to_current_direct_migration_owner,
    test_run_gate_clearing_batch_blocks_legacy_f3_cumulative_incidence_payload_before_materialize,
    test_stale_time_to_event_grouped_payload_detection_does_not_require_retired_template_registry,
    test_run_gate_clearing_batch_allows_current_f3_payload_after_transport_sync,
)
from .test_gate_clearing_batch_cases.direct_migration_transportability_registry_sync import (
    test_run_gate_clearing_batch_direct_migration_waits_for_transportability_registry_sync,
    test_run_gate_clearing_batch_redrives_transportability_sync_when_previous_fingerprint_matches_but_f5_is_missing,
    test_run_gate_clearing_batch_cleanly_rematerializes_missing_transportability_f5_without_legacy_contract,
    test_run_gate_clearing_batch_redrives_direct_migration_after_transportability_sync_adds_f5,
)
from .test_gate_clearing_batch_cases.transport_sync_normalization import (
    test_run_gate_clearing_batch_blocks_f3_payload_rewritten_by_transport_sync,
    test_repair_paper_live_paths_canonicalizes_absolute_paths_from_old_worktree,
    test_repair_paper_live_paths_collapses_nested_study_paper_segments,
)
from .test_gate_clearing_batch_cases.display_materialization_failures import (
    test_display_materialization_missing_registry_records_blocking_artifact_ref,
    test_display_materialization_matching_input_failure_is_reused_as_blocked,
    test_display_materialization_fingerprint_uses_json_content_not_mtime,
    test_gate_clearing_batch_record_binds_source_work_unit_fingerprint,
)
