from __future__ import annotations

from tests.test_opl_standard_pack_cases.generated_interface_cases import (
    test_light_external_pattern_intake_projects_into_stage_surfaces_as_refs_only,
    test_opl_default_callers_project_mas_delete_authorization_without_becoming_authority,
    test_opl_generated_interfaces_compile_mas_standard_pack,
    test_opl_standard_scaffold_validates_mas_pack,
)
from tests.test_opl_standard_pack_cases.stage_contract_cases import (
    test_opl_standard_pack_declares_single_ordinary_default_stage,
    test_pack_compiler_input_declares_canonical_agent_identity,
)
