from __future__ import annotations

from tests.test_provider_admission_current_control_cases.current_control_arbiter_cases import (
    test_provider_admission_current_control_records_retained_pending_arbiter_decision,
    test_provider_admission_current_control_provider_readback_consumes_same_identity_transition_request,
    test_provider_admission_current_control_suppresses_candidate_blocked_by_paper_recovery_state,
    test_provider_admission_current_control_requires_execute_supervisor_decision,
)
from tests.test_provider_admission_current_control_cases.test_arbiter_decision_cases import (
    test_previous_global_terminal_consumed_readback_suppresses_same_identity_pending,
    test_provider_admission_current_control_records_accepted_closeout_arbiter_decision,
    test_provider_admission_current_control_records_running_identity_arbiter_decision,
    test_provider_admission_current_control_terminal_closeout_precedes_stale_live_projection,
)
from tests.test_provider_admission_current_control_cases.provider_admission_report_sync_cases import (
    test_provider_admission_report_suppresses_candidate_blocked_by_report_paper_recovery_state,
    test_provider_admission_report_retains_matching_current_action_candidate_over_stale_scan_blocker,
    test_provider_admission_report_sync_updates_managed_action_candidate_surface,
    test_provider_admission_report_sync_clears_stale_managed_action_pending_state,
    test_provider_admission_report_sync_consumes_terminal_readback_in_managed_action,
    test_provider_admission_report_sync_keeps_transition_request_out_of_managed_admission_surface,
)
from tests.test_provider_admission_current_control_cases.provider_admission_report_sync_cases_cases.transition_runtime_readback_cases import (
    test_provider_admission_current_control_runtime_health_live_attempt_suppresses_pending,
    test_provider_admission_current_control_runtime_health_live_attempt_suppresses_transition_request,
    test_provider_admission_report_refreshes_scanned_typed_blocker_without_candidates,
    test_provider_admission_report_sync_clears_domain_blocked_recovery_pending_state,
    test_provider_admission_report_sync_clears_pending_when_managed_action_is_running,
    test_provider_admission_report_sync_consumes_transition_request_after_terminal_closeout,
    test_provider_admission_report_sync_lifts_study_level_provider_readback_to_top_level,
    test_provider_admission_report_sync_preserves_non_advancing_transition_request,
)
from tests.test_provider_admission_current_control_cases.transition_request_consume_only_cases import (
    test_provider_admission_current_control_treats_mas_request_without_opl_readback_as_non_advancing,
    test_provider_admission_current_control_backfills_owner_from_transition_request,
    test_owner_receipt_current_work_unit_keeps_accepted_owner_gate_transition_request,
    test_provider_admission_current_control_treats_current_transition_authority_as_non_advancing,
    test_paper_recovery_successor_without_explicit_dispatch_fails_closed,
    test_provider_admission_current_control_consumes_opl_readback_inside_provider_identity,
)
from tests.test_provider_admission_current_control_cases.transition_request_consume_only_cases_cases.terminal_closeout_and_identity_cases import (
    test_provider_admission_current_control_consumes_terminal_closeout_currentness_for_same_request,
    test_provider_admission_current_control_keeps_same_tick_materialized_recovery_request_consume_only,
    test_provider_admission_current_control_rejects_mismatched_opl_readback_identity,
)
from tests.test_provider_admission_current_control_cases.transition_request_consume_only_cases_cases.test_request_only_dry_run_closeout import (
    test_dry_run_materialized_transition_request_waits_for_opl_readback,
    test_dry_run_transition_request_is_not_promoted_by_unconsumed_closeout_guard,
    test_request_only_successor_transition_candidate_carries_current_work_unit_stage_packet_ref,
    test_request_only_transition_waits_for_readback_across_owner_action_recovery_state,
)
