from __future__ import annotations

from tests.product_entry_cases.attention_queue_and_cockpit_base import (
    test_workspace_cockpit_marks_domain_diagnostic_commands_as_diagnostic_only,
    test_attention_queue_prefers_route_repair_focus_for_quality_blockers,
    test_attention_queue_uses_quality_execution_lane_for_generic_study_blocked,
    test_attention_queue_projects_manual_finishing_as_package_handoff_without_generic_blocker_wording,
    test_attention_queue_prefers_autonomy_contract_summary_for_runtime_recovery,
    test_attention_queue_prefers_gate_clearing_followthrough_for_quality_blockers,
    test_study_item_normalizes_gate_clearing_batch_followthrough_from_progress_payload,
    test_workspace_cockpit_summarizes_alerts_and_user_commands,
    test_workspace_cockpit_reads_study_progress_in_parallel_and_preserves_order,
    test_workspace_cockpit_markdown_prefers_shared_human_status_narration,
)
from tests.product_entry_cases.cockpit_status_and_entry_status_focus import (
    annotations,
    test_workspace_cockpit_projects_ai_first_operations_state_from_study_progress,
    test_workspace_cockpit_projects_autonomy_soak_and_quality_followthrough,
    test_workspace_cockpit_attention_queue_carries_runtime_control_pickup_and_gate,
    test_workspace_cockpit_projects_ai_first_cross_study_completion_runtime_state,
    test_workspace_cockpit_projects_gate_clearing_followthrough_into_attention_and_brief,
    test_workspace_cockpit_passes_through_medical_paper_readiness_from_study_progress,
    test_workspace_cockpit_uses_canonical_user_visible_progress_projection,
    test_workspace_cockpit_builds_medical_paper_readiness_projection_when_progress_lacks_it,
    test_workspace_cockpit_does_not_emit_action_cards_for_ready_medical_paper_readiness,
    test_workspace_cockpit_projects_v5_ops_health,
    test_product_entry_status_projects_workspace_v5_ops_health,
    test_workspace_cockpit_exposes_long_horizon_paper_operations_action_cards,
    test_product_entry_status_promotes_v2_action_cards_to_workflow_steps,
    test_workspace_cockpit_markdown_renders_v2_action_card_status_and_missing_reason,
    test_guarded_operator_action_dispatch_fails_closed_without_payload,
    test_guarded_operator_action_replays_duplicate_submit_without_rematerializing,
    test_guarded_operator_action_blocks_payload_drift_for_same_idempotency_key,
    test_guarded_operator_action_reconciles_missing_result_artifact_from_ledger,
    test_workspace_cockpit_isolates_single_study_progress_projection_error,
    test_workspace_cockpit_projects_quality_execution_lane_into_attention_and_brief,
    test_workspace_cockpit_markdown_prefers_human_facing_labels,
    test_workspace_cockpit_projects_operator_status_card_into_study_items_and_attention,
)
from tests.product_entry_cases.entry_status_focus_cases import (
    test_build_product_entry_status_uses_gate_clearing_followthrough_for_attention_brief,
    test_build_product_entry_status_uses_operator_status_card_for_now_summary,
    test_build_product_entry_status_uses_quality_review_followthrough_for_monitor_focus,
    test_build_product_entry_status_uses_same_line_route_truth_for_current_focus,
)
from tests.product_entry_cases.authority_operation_manifest import (
    test_product_entry_manifest_domain_commands_include_authority_operations,
    test_product_entry_manifest_schema_enum_matches_authority_command_catalog,
    test_domain_entry_command_contracts_match_authority_command_catalog,
)
from tests.product_entry_cases.manifest_launch_and_task_intake import (
    test_build_product_entry_manifest_projects_contract_bundle_with_product_entry_fields,
    test_build_product_entry_manifest_exposes_source_provenance_refs_for_opl_projection,
    test_build_product_entry_status_projects_contract_bundle_from_manifest,
    test_render_product_entry_status_markdown_prefers_human_facing_labels,
    test_submit_study_task_writes_durable_intake_and_updates_startup_brief_block,
    test_submit_study_task_projects_reviewer_revision_intake,
    test_submit_study_task_honors_explicit_reviewer_revision_kind_without_text_marker,
    test_submit_study_task_writes_structured_manual_hold_intake,
    test_build_product_entry_reuses_latest_task_intake_and_shared_handoff_envelope,
)
from tests.product_entry_cases.repo_shell_and_handoff_templates import (
    test_build_product_entry_manifest_projects_repo_shell_and_shared_handoff_templates,
    test_product_entry_progress_projection_defaults_to_next_action_envelope,
)
from tests.product_entry_cases.manifest_launch_and_task_intake_cases.launch_study_surfaces import (
    test_launch_study_markdown_prefers_human_facing_labels,
    test_launch_study_markdown_prefers_shared_human_status_narration,
    test_launch_study_packages_monitoring_progress_and_commands,
)
from tests.product_entry_cases.manifest_launch_and_task_intake_cases.test_explicit_wakeup import (
    test_launch_study_explicit_wakeup_records_truth_resume,
    test_launch_study_explicit_wakeup_releases_paused_runtime_gate,
    test_launch_study_rejects_unsupported_entry_mode_before_runtime_projection,
    test_launch_study_uses_formal_runtime_entry_mode_for_opl_handoff,
)
from tests.product_entry_cases.product_entry_preflight_and_task_submission import (
    annotations,
    test_build_product_entry_status_projects_product_entry_over_current_workspace_loop,
    test_workspace_cockpit_flags_supervision_owner_drift_even_when_study_progress_is_fresh,
    test_build_product_entry_status_preflight_blocks_on_workspace_supervision_owner_drift,
    test_validate_single_project_boundary_fails_closed_on_missing_roles,
    test_validate_single_project_boundary_fails_closed_on_missing_not_now,
    test_validate_capability_owner_boundary_rejects_pre_absorb_status,
    test_render_product_entry_status_markdown_hides_preview_raw_summary_keys,
    test_product_entry_manifest_fails_closed_on_invalid_user_interaction_contract_shape,
    test_startup_contract_appends_latest_task_intake_context,
    test_submit_study_task_projects_task_context_for_opl_runtime,
    test_submit_study_task_deduplicates_same_live_runtime_task_for_current_run,
    test_submit_study_task_deduplicates_same_live_runtime_task_across_run_attempts,
    test_submit_study_task_uses_managed_quest_id_for_opl_owner_route_ref,
    test_submit_study_task_requires_reactivation_for_stopped_reviewer_revision,
    test_submit_study_task_does_not_fall_back_to_private_queue_when_backend_chat_is_unavailable,
    test_product_entry_import_is_lightweight_for_manifest_discovery,
    test_build_product_entry_preflight_uses_shared_builder,
    test_build_product_entry_guardrails_uses_shared_builder,
    test_build_phase3_clearance_lane_uses_shared_builder,
    test_build_phase4_backend_deconstruction_uses_shared_builder,
    test_build_phase5_platform_target_uses_shared_builder,
    test_product_entry_manifest_uses_bounded_mainline_projection,
    test_build_product_entry_manifest_uses_shared_family_product_entry_orchestration,
)
from tests.product_entry_cases.product_entry_markdown_and_skill_catalog import (
    test_build_skill_catalog_projects_recommended_shell_and_direct_activation_hints,
)
from tests.product_entry_cases.paper_orchestra_operator_projection import (
    test_product_entry_surfaces_paper_orchestra_operator_projection_without_runtime_authority,
)
from tests.product_entry_cases.open_auto_research_projection import (
    test_product_entry_surfaces_workspace_open_auto_research_projection,
)
from tests.product_entry_cases.opl_current_control_state_handoff_projection import (
    test_workspace_cockpit_and_product_entry_surface_opl_current_control_state_handoff_dashboard,
)
from tests.product_entry_cases.delivery_inspection_visibility import (
    test_product_entry_surfaces_delivery_inspection_in_cockpit_and_entry_status,
    test_product_entry_labels_visible_delivery_projection_as_observability_only,
    test_product_entry_exposes_publication_inspection_package_operator_surface,
    test_product_entry_counts_layout_migration_even_when_stale_status_is_primary,
    test_product_entry_does_not_normalize_retired_delivery_projection_input,
)
from tests.product_entry_cases.action_catalog_parity import (
    annotations,
    test_mas_action_catalog_drives_cli_product_entry_skill_and_mcp_metadata,
    test_mas_action_catalog_exposes_study_state_matrix_for_opl_transition_runner,
    test_mas_action_catalog_projects_domain_handler_without_new_mcp_tool,
    test_mas_action_catalog_exposes_display_pack_agent_capability_as_grouped_mcp_runtime,
    test_mas_action_catalog_exposes_scientific_capability_registry_as_public_mcp_runtime,
    test_mas_action_catalog_exposes_publication_aftercare_plan_as_refs_only_surface,
    test_mas_action_catalog_exposes_lightweight_executor_receipt_as_descriptor_only_contract,
    test_product_entry_manifest_exposes_foundry_agent_product_positioning,
    test_product_entry_manifest_exposes_functional_consumer_boundary,
    test_product_entry_manifest_exposes_mas_family_stage_control_plane_descriptor,
    test_product_entry_manifest_exposes_provider_guarded_soak_read_model_with_typed_blockers,
    test_product_entry_manifest_exposes_real_paper_owner_payload_closeout,
    test_product_entry_guarded_apply_default_targets_ignore_noncanonical_paper_residue,
    test_product_entry_manifest_consumes_opl_production_proof_for_provider_availability,
    test_default_manifest_keeps_history_projection_out_of_current_surface,
    test_product_entry_manifest_exposes_provider_residency_typed_blocker,
    test_provider_residency_read_model_requires_all_opl_receipts,
    test_product_entry_manifest_omits_history_only_retirement_audit_surface,
    test_product_entry_manifest_exposes_publication_route_memory_descriptor,
    test_standard_domain_agent_skeleton_projects_quality_pack_locator_without_authority,
    test_manifest_exposes_body_free_workspace_runtime_evidence_receipt_with_typed_blocker,
    test_workspace_runtime_evidence_receipt_observes_mas_owner_receipt_refs,
)
from tests.product_entry_cases.functional_consumer_boundary import (
    test_product_entry_manifest_exposes_functional_consumer_boundary,
)
from tests.product_entry_cases.transition_spec_descriptor import (
    test_product_entry_manifest_exposes_domain_transition_spec_descriptor,
)
from tests.product_entry_cases.functional_closure_projection import (
    test_product_entry_manifest_projects_current_development_lines_closure,
)


def test_product_entry_manifest_exposes_paper_mission_default_entry(tmp_path):
    from med_autoscience.controllers.product_entry.manifest_surfaces import build_product_entry_manifest
    from med_autoscience.profiles import load_profile
    from tests.test_cli_cases.shared import write_profile

    profile_path = tmp_path / "profile.local.toml"
    write_profile(profile_path, workspace_root=tmp_path / "workspace")
    profile = load_profile(profile_path)

    manifest = build_product_entry_manifest(profile=profile, profile_ref=profile_path)

    paper_mission = manifest["medical_paper_product_entry"]
    assert paper_mission["default_action_intent"] == "paper_mission/start_or_resume"
    assert paper_mission["authority_boundary"]["writes_authority"] is False
    assert "paper-mission drive" in paper_mission["default_command"]
    assert paper_mission["drive_command"] == paper_mission["default_command"]
    assert "paper-mission inspect" in paper_mission["inspect_command"]
    assert "paper_mission" not in manifest["product_entry_shell"]
