from __future__ import annotations

import pytest

from tests.submission_minimal_cases.package_core_and_authority import *
from tests.submission_minimal_cases.direct_current_body_figure_catalog_filter import (
    test_create_submission_minimal_package_filters_nested_supplementary_figures_when_canonical_catalog_exists,
)
from tests.submission_minimal_cases.limitations_section import (
    test_general_medical_submission_markdown_preserves_limitations_section,
)
from tests.submission_minimal_cases.clean_migration_guard import (
    test_create_submission_minimal_package_blocks_pending_clean_paper_authority_cutover,
    test_create_submission_minimal_package_blocks_pending_cutover_for_runtime_paper_root,
)
from tests.submission_minimal_cases.frontiers_profile_and_sync import (
    test_create_submission_minimal_package_skips_missing_planned_table_entries,
    test_create_submission_minimal_package_syncs_study_delivery_when_context_is_available,
    test_create_submission_minimal_package_replays_post_materialization_sync_when_context_is_available,
    test_create_submission_minimal_package_frontiers_family_profile_creates_journal_specific_assets,
    test_create_submission_minimal_package_rejects_legacy_frontiers_profile,
    test_create_submission_minimal_package_frontiers_family_profile_preserves_reference_doc_parts,
    test_create_submission_minimal_package_frontiers_family_uses_figure_semantics_manifest_for_legends,
    test_create_submission_minimal_package_frontiers_family_syncs_into_study_family_package,
    test_create_submission_minimal_package_frontiers_family_uses_admin_gap_notes_not_prompt_placeholders,
    test_create_submission_minimal_package_builds_submission_facing_docx_for_current_draft_shape,
    test_create_submission_minimal_package_current_draft_falls_back_to_catalog_backed_figures,
    test_create_submission_minimal_package_uses_dict_figure_semantics_for_all_catalog_figures,
    test_create_submission_minimal_package_uses_catalog_backed_figures_when_main_figure_section_has_only_legends,
    test_create_submission_minimal_package_supports_short_f_figure_headings_from_review_manuscript,
    test_inspect_submission_source_markdown_counts_alt_text_inline_figures,
    test_inspect_submission_source_markdown_accepts_main_figures_alias,
)
from tests.submission_minimal_cases.source_markdown_and_materialized_refs import (
    test_inspect_submission_source_markdown_counts_short_f_headings_as_figures,
    test_inspect_submission_source_markdown_counts_independent_figure_legends_section,
    test_inspect_submission_source_markdown_treats_lowercase_figure_legends_as_separate_section,
    test_create_submission_minimal_package_supports_manuscript_shaped_draft_without_front_matter,
    test_create_submission_minimal_package_supports_front_matter_manuscript_shaped_draft,
    test_create_submission_minimal_package_keeps_submission_figure_legends_concise,
    test_figure_legend_merge_skips_near_duplicate_semantic_message,
    test_create_submission_minimal_package_skips_stale_panel_messages_for_single_panel_grouped_calibration,
    test_create_submission_minimal_package_copies_deferred_supplementary_figure_assets,
    test_create_submission_minimal_package_materializes_supplementary_tables_workbook,
    test_create_submission_minimal_package_preserves_top_level_figures_in_manuscript_shaped_draft,
    test_create_submission_minimal_package_strips_short_figure_id_from_image_alt_text,
    test_create_submission_minimal_package_orders_main_figures_by_figure_number,
    test_create_submission_minimal_package_splits_nested_tables_and_orders_by_table_number,
    test_create_submission_minimal_package_renders_extra_wide_tables_as_sideways_latex,
    test_create_submission_minimal_package_uses_catalog_markdown_for_long_measure_value_tables,
    test_create_submission_minimal_package_accepts_materialized_submission_source_from_compile_report,
    test_describe_submission_minimal_authority_accepts_materialized_submission_source_from_compile_report,
    test_create_submission_minimal_package_falls_back_when_compile_report_points_to_missing_submission_source,
)
from tests.submission_minimal_cases.v2_layout_and_legacy_cases import (
    test_describe_submission_minimal_authority_prefers_v2_manifest_over_stale_legacy_root,
    test_describe_submission_minimal_authority_reads_legacy_manifest_when_v2_manifest_is_absent,
    test_submission_minimal_v2_layout_records_source_contract_in_reproducibility_docs,
    test_submission_minimal_v2_layout_writes_reproducibility_lineage_bundle,
)

pytestmark = pytest.mark.submission_heavy
