from __future__ import annotations

from tests.test_provider_admission_current_control_cases.current_control_arbiter_cases import (
    test_provider_admission_current_control_records_retained_pending_arbiter_decision,
    test_provider_admission_current_control_provider_readback_consumes_same_identity_transition_request,
    test_provider_admission_current_control_suppresses_candidate_blocked_by_paper_recovery_state,
    test_provider_admission_current_control_requires_execute_supervisor_decision,
)
from tests.test_provider_admission_current_control_cases.provider_admission_report_sync_cases import (
    test_provider_admission_report_suppresses_candidate_blocked_by_report_paper_recovery_state,
    test_provider_admission_report_retains_matching_current_action_candidate_over_stale_scan_blocker,
    test_provider_admission_report_sync_updates_managed_action_candidate_surface,
    test_provider_admission_report_sync_clears_stale_managed_action_pending_state,
    test_provider_admission_report_sync_consumes_terminal_readback_in_managed_action,
    test_provider_admission_report_sync_keeps_transition_request_out_of_managed_admission_surface,
)
from tests.test_provider_admission_current_control_cases.transition_request_consume_only_cases import (
    test_provider_admission_current_control_treats_mas_request_without_opl_readback_as_non_advancing,
    test_provider_admission_current_control_backfills_owner_from_transition_request,
    test_owner_receipt_current_work_unit_keeps_accepted_owner_gate_transition_request,
    test_provider_admission_current_control_treats_current_transition_authority_as_non_advancing,
    test_paper_recovery_successor_without_explicit_dispatch_fails_closed,
    test_provider_admission_current_control_consumes_opl_readback_inside_provider_identity,
)
