from __future__ import annotations

from tests.display_layout_qc_cases.shared import *
from tests.display_layout_qc_cases.illustration_time_to_event_and_workflow_qc import (
    test_run_display_layout_qc_passes_for_valid_illustration_flow,
    test_run_display_layout_qc_fails_when_illustration_subfigure_semantics_are_missing,
    test_run_display_layout_qc_fails_when_structure_connectors_are_missing,
    test_run_display_layout_qc_fails_when_illustration_exclusion_overlaps_step,
    test_run_display_layout_qc_passes_for_participant_reporting_flow_without_ab_panels,
    test_run_display_layout_qc_fails_for_left_compressed_participant_flow,
    test_run_display_layout_qc_fails_participant_reporting_flow_when_connector_missing,
)
from tests.display_layout_qc_cases.baseline_transportability_and_risk_qc import (
    test_run_display_layout_qc_rejects_retired_python_data_shell_profiles,
    test_run_display_layout_qc_passes_for_center_transportability_governance_summary_panel,
    test_run_display_layout_qc_fails_without_calibration_governance_metrics,
    test_run_display_layout_qc_rejects_legacy_governance_cards_as_center_transportability_panel,
    test_run_display_layout_qc_rejects_legacy_decision_cells_as_center_transportability_panel,
    test_run_display_layout_qc_fails_when_calibration_governance_metric_leaves_panel,
    test_run_display_layout_qc_fails_for_overlapping_legend_and_panel,
    test_run_display_layout_qc_passes_for_valid_embedding_scatter,
    test_run_display_layout_qc_fails_when_curve_text_leaves_device,
    test_run_display_layout_qc_flags_unreadable_risk_separation,
    test_run_display_layout_qc_flags_non_monotonic_grouped_risk_summary,
    test_run_display_layout_qc_accepts_single_panel_dm002_grouped_calibration_variant,
    test_run_display_layout_qc_checks_grouped_risk_order_within_each_cohort,
    test_run_display_layout_qc_flags_compressed_event_count_spread_for_grouped_risk_summary,
)
from tests.display_layout_qc_cases.risk_decision_curve_and_omics_qc import (
    test_run_display_layout_qc_flags_compressed_observed_risk_spread_for_grouped_risk_summary,
    test_run_display_layout_qc_flags_compressed_predicted_risk_spread_for_grouped_risk_summary,
    test_run_display_layout_qc_honors_readability_override_for_grouped_risk_summary,
    test_run_display_layout_qc_fails_when_decision_curve_series_lengths_mismatch,
    test_run_display_layout_qc_fails_when_decision_curve_treated_fraction_panel_is_missing,
    test_run_display_layout_qc_requires_structured_time_horizon_for_time_dependent_roc,
    test_run_display_layout_qc_passes_for_time_dependent_roc_comparison_panel,
    test_run_display_layout_qc_uses_sanitized_panel_label_tokens_for_time_dependent_roc_comparison_panel,
    test_run_display_layout_qc_uses_sanitized_panel_label_tokens_for_stratified_cumulative_incidence_panel,
    test_run_display_layout_qc_fails_when_time_dependent_roc_comparison_panel_horizon_is_invalid,
    test_run_display_layout_qc_fails_when_risk_group_summary_panel_labels_are_missing,
    test_run_display_layout_qc_passes_for_stratified_cumulative_incidence_panel,
    test_run_display_layout_qc_fails_when_stratified_cumulative_incidence_panel_labels_are_missing,
    test_run_display_layout_qc_fails_when_decision_curve_panel_label_anchor_drifts,
    test_run_display_layout_qc_fails_when_correlation_matrix_is_not_symmetric,
    test_run_display_layout_qc_fails_when_performance_heatmap_value_is_out_of_range,
    test_run_display_layout_qc_fails_when_confusion_matrix_row_fraction_does_not_sum_to_one,
    test_run_display_layout_qc_passes_for_pathway_enrichment_dotplot_panel,
)
from tests.display_layout_qc_cases.omics_genomic_landscape_qc import (
    test_run_display_layout_qc_fails_when_pathway_enrichment_dotplot_scale_label_is_missing,
    test_run_display_layout_qc_passes_for_celltype_marker_dotplot_panel,
    test_run_display_layout_qc_fails_when_celltype_marker_dotplot_marker_labels_are_missing,
    test_run_display_layout_qc_passes_for_omics_volcano_panel,
    test_run_display_layout_qc_fails_when_omics_volcano_threshold_box_is_missing,
    test_run_display_layout_qc_passes_for_oncoplot_mutation_landscape_panel,
    test_run_display_layout_qc_passes_for_cnv_recurrence_summary_panel,
    test_run_display_layout_qc_passes_for_genomic_alteration_landscape_panel,
)
from tests.display_layout_qc_cases.genomic_consequence_and_pathway_qc import (
    test_run_display_layout_qc_passes_for_genomic_alteration_consequence_panel,
    test_run_display_layout_qc_fails_when_genomic_alteration_consequence_panel_drops_driver_coverage,
    test_run_display_layout_qc_passes_for_genomic_alteration_multiomic_consequence_panel,
    test_run_display_layout_qc_fails_when_multiomic_consequence_panel_uses_wrong_layer_ids,
    test_run_display_layout_qc_passes_for_genomic_alteration_pathway_integrated_composite_panel,
    test_run_display_layout_qc_fails_when_pathway_integrated_composite_panel_uses_wrong_pathway_layer_ids,
)
from tests.display_layout_qc_cases.generalizability_effect_and_heterogeneity_qc import (
    test_run_display_layout_qc_passes_for_generalizability_subgroup_composite_panel,
    test_run_display_layout_qc_passes_for_compact_effect_estimate_panel,
    test_run_display_layout_qc_fails_when_compact_effect_estimate_panel_row_order_drifts,
    test_run_display_layout_qc_passes_for_coefficient_path_panel,
    test_run_display_layout_qc_fails_when_coefficient_path_marker_leaves_path_panel,
    test_run_display_layout_qc_passes_for_broader_heterogeneity_summary_panel,
    test_run_display_layout_qc_fails_when_broader_heterogeneity_verdict_leaves_summary_panel,
)
from tests.display_layout_qc_cases.layout_qc_edge_cases import (
    test_run_display_layout_qc_fails_when_landmark_panel_window_is_not_forward,
)
