from __future__ import annotations

import importlib
import json
import os

import pytest

from med_autoscience.controllers.next_action_envelope import SURFACE_KIND
from tests.paper_mission_test_helpers import (
    _paper_mission_transaction_payload,
    _paper_mission_forbidden_write_guard,
    _write_submission_milestone_package,
)
from tests.profile_test_helpers import write_profile


@pytest.fixture(autouse=True)
def _disable_default_opl_live_probe(monkeypatch: pytest.MonkeyPatch, tmp_path) -> None:
    monkeypatch.setenv("OPL_BIN", str(tmp_path / "missing-opl"))


from tests.test_study_progress_mission_summary_cases.materialized_readback import annotations, test_artifact_first_mission_summary_prefers_materialized_paper_mission_run, test_materialized_mission_summary_does_not_let_opl_closeout_override_stage_outcome, test_typed_blocker_resolution_successor_supersedes_stale_wakeup_top_level, test_submission_authority_owner_gate_records_claim_gate_without_blocking_next_action, test_submission_authority_owner_gate_keeps_new_next_action_for_different_identity
from tests.test_study_progress_mission_summary_cases.next_action_stage_closure import (
    test_top_level_next_legal_action_prefers_canonical_runtime_readback_request,
    test_single_next_action_projection_does_not_accept_program_domain_transition_override,
    test_typed_blocker_successor_does_not_override_domain_transition_reviewer_action,
    test_new_reviewer_revision_intake_retire_stale_typed_blocker_resolution,
    test_top_level_next_legal_action_prefers_receipt_consumption_over_stage_replay,
    test_artifact_first_mission_summary_prefers_current_stage_closure_readback,
    test_paper_mission_run_nested_stage_closure_readback_keeps_terminalizer_fields,
)
