from __future__ import annotations

from tests.mcp_opl_current_control_state_handoff_cases.basic_projection import (
    test_study_progress_opl_current_control_state_handoff_projection_reads_developer_supervisor_mode,
    test_study_progress_opl_current_control_state_handoff_projection_preserves_string_why_not_applied,
    test_study_progress_opl_current_control_state_handoff_rejects_incomplete_top_level_provider_admission_candidate,
    test_study_progress_opl_current_control_state_handoff_merges_complete_top_level_provider_admission_readback,
    test_study_progress_opl_current_control_state_handoff_binds_root_readback_to_action_queue,
)
from tests.mcp_opl_current_control_state_handoff_cases.provider_admission_readback import (
    test_study_progress_opl_current_control_state_handoff_consumes_live_transition_log_readback,
    test_provider_admission_transition_log_readback_uses_current_transition_reader,
    test_study_progress_opl_current_control_state_handoff_consumes_provider_admission_with_matching_terminal_closeout,
    test_study_progress_opl_current_control_state_handoff_preserves_runtime_backed_admission_when_closeout_identity_is_not_bound,
    test_study_progress_opl_current_control_state_handoff_consumes_global_terminal_readback_action_queue,
    test_study_progress_opl_current_control_state_handoff_preserves_replayed_provider_admission_over_old_typed_blocker_closeout,
)
from tests.mcp_opl_current_control_state_handoff_cases.rendering import (
    test_mcp_compacts_and_renders_opl_current_control_state_handoff_dashboard,
    test_mcp_compacts_string_why_not_applied_as_single_reason,
    test_mcp_compacts_and_renders_latest_terminal_stage_log,
)
from tests.mcp_opl_current_control_state_handoff_cases.terminal_closeout import (
    test_study_progress_opl_current_control_state_handoff_consumes_matching_opl_terminal_attempt_closeout,
    test_study_progress_opl_current_control_state_handoff_consumes_request_wrapper_terminal_closeout,
    test_study_progress_opl_current_control_state_handoff_consumes_request_wrapper_domain_owner_closeout,
    test_study_progress_opl_current_control_state_handoff_uses_transition_request_for_terminal_probe,
    test_study_progress_opl_current_control_state_handoff_projects_top_level_transition_request_without_study_entry,
)
