from __future__ import annotations

from .test_study_runtime_typed_surface_cases import shared as _shared

globals().update({
    name: value
    for name, value in vars(_shared).items()
    if not name.startswith('__')
})

from .test_study_runtime_typed_surface_cases.status_type_cases import (
    test_study_runtime_types_reexports_status_surfaces_from_progress_projection,
    test_study_runtime_decision_facade_does_not_export_loader_helper,
    test_study_runtime_types_reexports_publication_supervisor_surface,
    test_study_runtime_types_reexports_execution_owner_guard_surface,
    test_study_runtime_types_reexports_pending_user_interaction_surface,
    test_study_runtime_types_reexports_continuation_state_surface,
    test_domain_status_projection_reexports_typed_surface_from_study_runtime_types,
    test_study_runtime_types_excludes_retired_execution_aggregate,
    test_study_runtime_reason_drops_legacy_med_deepscientist_only_owner_label,
    test_opl_runtime_owner_handoff_materialization_is_required_for_recovering_target,
    test_opl_runtime_owner_handoff_materialization_uses_runtime_health_recovery_target_for_strict_live_timeout,
    test_progress_projection_round_trips_through_typed_state,
    test_progress_projection_mapping_semantics_follow_serialized_payload,
    test_progress_projection_accepts_retrying_live_quest_state,
    test_progress_projection_accepts_failed_non_live_quest_state,
    test_progress_projection_core_key_assignment_uses_typed_normalization,
    test_progress_projection_normalizes_study_completion_contract_to_typed_state,
    test_progress_projection_rejects_unknown_decision_value,
    test_progress_projection_rejects_unknown_reason_value,
    test_progress_projection_rejects_unknown_quest_status_value,
    test_progress_projection_records_structured_runtime_extras,
    test_progress_projection_records_typed_completion_sync_and_audits,
    test_progress_projection_records_typed_preflight_and_recovery_extras,
    test_progress_projection_records_typed_publication_supervisor_state,
    test_progress_projection_records_typed_progress_projection,
    test_startup_context_sync_result_requires_echoed_startup_contract,
    test_startup_context_sync_result_requires_echoed_quest_id,
    test_progress_projection_records_typed_startup_hydration_reports,
    test_progress_projection_records_typed_startup_contract_validation,
    test_progress_projection_exposes_typed_gate_and_completion_accessors,
    test_progress_projection_records_runtime_artifacts_with_binding_existence,
    test_progress_projection_records_autonomous_runtime_notice_payload,
    test_progress_projection_records_execution_owner_guard_payload,
    test_progress_projection_records_pending_user_interaction_payload,
    test_progress_projection_records_continuation_state_payload,
    test_progress_projection_detects_blocked_hydration_refresh_candidate,
    test_progress_projection_detects_owner_route_ai_reviewer_reference_context_hydration_gap,
    test_runtime_binding_and_daemon_step_enums_remain_progress_projection_owned,
)
from .test_study_runtime_typed_surface_cases.runtime_health_decision_gate_cases import (
    test_runtime_health_diagnostic_recovery_hint_cannot_rewrite_status_without_opl_readback,
    test_runtime_health_recovery_decision_rejects_cross_identity_opl_readback,
    test_runtime_health_recovery_decision_rejects_top_level_opl_readback_claim,
    test_runtime_health_recovery_decision_requires_opl_current_control_readback,
    test_runtime_health_recovery_decision_requires_both_observability_and_route_reconciler_readback,
)
