from __future__ import annotations

from .core import InputSchemaContract, _template_ids_for_input_schema

_INPUT_SCHEMA_CONTRACTS_EFFECTS: tuple[InputSchemaContract, ...] = (
    InputSchemaContract(
        input_schema_id="forest_effect_inputs_v1",
        display_kind="evidence_figure",
        display_name="Forest Effect Plot",
        template_ids=_template_ids_for_input_schema("forest_effect_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "reference_value", "rows"),
        display_optional_fields=("paper_role",),
        collection_required_fields={"rows": ("label", "estimate", "lower", "upper")},
        additional_constraints=(
            "rows_must_be_non_empty",
            "effect_interval_must_bound_estimate",
            "effect_values_must_be_finite",
        ),
    ),
    InputSchemaContract(
        input_schema_id="compact_effect_estimate_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Compact Effect Estimate Panel",
        template_ids=_template_ids_for_input_schema("compact_effect_estimate_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "reference_value", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "rows"),
        },
        nested_collection_required_fields={
            "panels.rows": ("row_id", "row_label", "estimate", "lower", "upper"),
        },
        nested_collection_optional_fields={
            "panels.rows": ("support_n",),
        },
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_be_between_two_and_four",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "reference_value_must_be_finite",
            "panel_rows_must_be_non_empty",
            "panel_row_ids_must_be_unique_within_panel",
            "panel_row_labels_must_be_unique_within_panel",
            "panel_row_values_must_be_finite",
            "panel_row_intervals_must_wrap_estimate",
            "panel_row_support_n_must_be_positive_when_present",
            "panel_row_orders_must_match_across_panels",
        ),
    ),
    InputSchemaContract(
        input_schema_id="coefficient_path_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Coefficient Path Panel",
        template_ids=_template_ids_for_input_schema("coefficient_path_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "path_panel_title",
            "x_label",
            "reference_value",
            "step_legend_title",
            "steps",
            "coefficient_rows",
            "summary_panel_title",
            "summary_cards",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "steps": ("step_id", "step_label", "step_order"),
            "coefficient_rows": ("row_id", "row_label", "points"),
            "summary_cards": ("card_id", "label", "value"),
        },
        collection_optional_fields={
            "summary_cards": ("detail",),
        },
        nested_collection_required_fields={
            "coefficient_rows.points": ("step_id", "estimate", "lower", "upper"),
        },
        nested_collection_optional_fields={
            "coefficient_rows.points": ("support_n",),
        },
        additional_constraints=(
            "steps_must_contain_between_two_and_five_entries",
            "step_ids_must_be_unique",
            "step_orders_must_be_strictly_increasing",
            "reference_value_must_be_finite",
            "coefficient_rows_must_be_non_empty",
            "coefficient_row_ids_must_be_unique",
            "coefficient_row_labels_must_be_unique",
            "coefficient_points_must_cover_all_declared_steps_once",
            "coefficient_point_values_must_be_finite",
            "coefficient_point_intervals_must_wrap_estimate",
            "coefficient_point_support_n_must_be_positive_when_present",
            "summary_cards_must_contain_between_two_and_four_entries",
            "summary_card_ids_must_be_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="broader_heterogeneity_summary_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Broader Heterogeneity Summary Panel",
        template_ids=_template_ids_for_input_schema("broader_heterogeneity_summary_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "matrix_panel_title",
            "x_label",
            "reference_value",
            "slice_legend_title",
            "slices",
            "effect_rows",
            "summary_panel_title",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "slices": ("slice_id", "slice_label", "slice_kind", "slice_order"),
            "effect_rows": ("row_id", "row_label", "verdict", "slice_estimates"),
        },
        collection_optional_fields={
            "effect_rows": ("detail",),
        },
        nested_collection_required_fields={
            "effect_rows.slice_estimates": ("slice_id", "estimate", "lower", "upper"),
        },
        nested_collection_optional_fields={
            "effect_rows.slice_estimates": ("support_n",),
        },
        additional_constraints=(
            "slices_must_be_non_empty",
            "slice_count_must_be_between_two_and_five",
            "slice_ids_must_be_unique",
            "slice_labels_must_be_unique",
            "slice_orders_must_be_strictly_increasing",
            "slice_kinds_must_be_supported",
            "reference_value_must_be_finite",
            "effect_rows_must_be_non_empty",
            "effect_row_ids_must_be_unique",
            "effect_row_labels_must_be_unique",
            "effect_row_verdicts_must_be_supported",
            "effect_row_slice_estimates_must_be_non_empty",
            "effect_row_slice_estimates_must_cover_declared_slices_exactly_once",
            "effect_row_values_must_be_finite",
            "effect_row_intervals_must_wrap_estimate",
            "effect_row_support_n_must_be_positive_when_present",
            "effect_row_detail_must_be_non_empty_when_present",
        ),
    ),
    InputSchemaContract(
        input_schema_id="interaction_effect_summary_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Interaction Effect Summary Panel",
        template_ids=_template_ids_for_input_schema("interaction_effect_summary_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "estimate_panel_title",
            "x_label",
            "reference_value",
            "summary_panel_title",
            "modifiers",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "modifiers": (
                "modifier_id",
                "modifier_label",
                "interaction_estimate",
                "lower",
                "upper",
                "support_n",
                "favored_group_label",
                "interaction_p_value",
                "verdict",
            ),
        },
        additional_constraints=(
            "modifiers_must_be_non_empty",
            "modifier_count_must_be_between_two_and_six",
            "modifier_ids_must_be_unique",
            "modifier_labels_must_be_unique",
            "reference_value_must_be_finite",
            "interaction_estimates_must_be_finite",
            "interaction_intervals_must_wrap_estimate",
            "modifier_support_n_must_be_positive",
            "interaction_p_values_must_be_between_zero_and_one",
            "favored_group_labels_must_be_non_empty",
            "modifier_verdicts_must_use_controlled_vocabulary",
        ),
    ),
)
