from __future__ import annotations

from .core import InputSchemaContract, _template_ids_for_input_schema

_INPUT_SCHEMA_CONTRACTS_EXPLANATIONS: tuple[InputSchemaContract, ...] = (
    InputSchemaContract(
        input_schema_id="shap_summary_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Summary Beeswarm",
        template_ids=_template_ids_for_input_schema("shap_summary_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "rows"),
        display_optional_fields=("paper_role",),
        collection_required_fields={"rows": ("feature", "points")},
        nested_collection_required_fields={"rows.points": ("shap_value", "feature_value")},
        additional_constraints=(
            "rows_must_be_non_empty",
            "row_feature_must_be_non_empty",
            "row_points_must_be_non_empty",
            "shap_values_must_be_finite",
            "feature_values_must_be_finite",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_bar_importance_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Bar Importance Panel",
        template_ids=_template_ids_for_input_schema("shap_bar_importance_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "bars"),
        display_optional_fields=("paper_role",),
        collection_required_fields={"bars": ("rank", "feature", "importance_value")},
        additional_constraints=(
            "bars_must_be_non_empty",
            "bar_features_must_be_unique",
            "bar_ranks_must_be_strictly_increasing",
            "bar_importance_values_must_be_non_negative_finite",
            "bar_importance_values_must_be_sorted_descending_by_rank",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_multicohort_importance_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Multicohort Importance Panel",
        template_ids=_template_ids_for_input_schema("shap_multicohort_importance_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "cohort_label", "bars"),
        },
        nested_collection_required_fields={
            "panels.bars": ("rank", "feature", "importance_value"),
        },
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_not_exceed_three",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_cohort_labels_must_be_unique",
            "panel_bars_must_be_non_empty",
            "panel_bar_features_must_be_unique_within_panel",
            "panel_bar_ranks_must_be_strictly_increasing",
            "panel_bar_importance_values_must_be_non_negative_finite",
            "panel_bar_importance_values_must_be_sorted_descending_by_rank",
            "panel_feature_orders_must_match_across_panels",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_dependence_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Dependence Panel",
        template_ids=_template_ids_for_input_schema("shap_dependence_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "y_label", "colorbar_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "x_label", "feature", "interaction_feature", "points"),
        },
        nested_collection_required_fields={
            "panels.points": ("feature_value", "shap_value", "interaction_value"),
        },
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_features_must_be_unique",
            "panel_points_must_be_non_empty",
            "panel_point_values_must_be_finite",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_waterfall_local_explanation_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Waterfall Local Explanation Panel",
        template_ids=_template_ids_for_input_schema("shap_waterfall_local_explanation_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "case_label", "baseline_value", "predicted_value", "contributions"),
        },
        nested_collection_required_fields={"panels.contributions": ("feature", "shap_value")},
        nested_collection_optional_fields={"panels.contributions": ("feature_value_text",)},
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_not_exceed_three",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_case_labels_must_be_unique",
            "panel_values_must_be_finite",
            "panel_contributions_must_be_non_empty",
            "panel_contribution_features_must_be_unique_within_panel",
            "panel_contribution_values_must_be_finite_and_non_zero",
            "panel_prediction_value_must_equal_baseline_plus_contributions",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_force_like_summary_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Force-like Summary Panel",
        template_ids=_template_ids_for_input_schema("shap_force_like_summary_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "case_label", "baseline_value", "predicted_value", "contributions"),
        },
        nested_collection_required_fields={"panels.contributions": ("feature", "shap_value")},
        nested_collection_optional_fields={"panels.contributions": ("feature_value_text",)},
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_not_exceed_three",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_case_labels_must_be_unique",
            "panel_values_must_be_finite",
            "panel_contributions_must_be_non_empty",
            "panel_contribution_features_must_be_unique_within_panel",
            "panel_contribution_values_must_be_finite_and_non_zero",
            "panel_prediction_value_must_equal_baseline_plus_contributions",
            "panel_contributions_must_be_sorted_by_absolute_magnitude_descending",
        ),
    ),
)
