from __future__ import annotations

from .core import InputSchemaContract, _template_ids_for_input_schema

_INPUT_SCHEMA_CONTRACTS_OMICS: tuple[InputSchemaContract, ...] = (
    InputSchemaContract(
        input_schema_id="omics_volcano_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Omics Volcano Panel",
        template_ids=_template_ids_for_input_schema("omics_volcano_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "x_label",
            "y_label",
            "legend_title",
            "effect_threshold",
            "significance_threshold",
            "panel_order",
            "points",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panel_order": ("panel_id", "panel_title"),
            "points": ("panel_id", "feature_label", "effect_value", "significance_value", "regulation_class"),
        },
        collection_optional_fields={
            "points": ("label_text",),
        },
        additional_constraints=(
            "legend_title_must_be_non_empty",
            "effect_threshold_must_be_positive",
            "significance_threshold_must_be_positive",
            "panel_order_must_be_non_empty",
            "panel_order_count_must_be_at_most_two",
            "panel_ids_must_be_unique",
            "panel_titles_must_be_non_empty",
            "points_must_be_non_empty",
            "point_panel_ids_must_match_declared_panels",
            "each_declared_panel_must_contain_points",
            "point_feature_labels_must_be_unique_within_panel",
            "point_effect_values_must_be_finite",
            "point_significance_values_must_be_non_negative",
            "point_regulation_classes_must_use_supported_vocabulary",
            "point_label_text_must_be_non_empty_when_present",
        ),
    ),
    InputSchemaContract(
        input_schema_id="heatmap_group_comparison_inputs_v1",
        display_kind="evidence_figure",
        display_name="Heatmap Group Comparison",
        template_ids=_template_ids_for_input_schema("heatmap_group_comparison_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "y_label", "cells"),
        display_optional_fields=("paper_role",),
        collection_required_fields={"cells": ("x", "y", "value")},
        additional_constraints=(
            "cells_must_be_non_empty",
            "cell_coordinates_must_be_non_empty",
            "cell_values_must_be_finite",
        ),
    ),
    InputSchemaContract(
        input_schema_id="performance_heatmap_inputs_v1",
        display_kind="evidence_figure",
        display_name="Performance Heatmap",
        template_ids=_template_ids_for_input_schema("performance_heatmap_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "x_label",
            "y_label",
            "metric_name",
            "row_order",
            "column_order",
            "cells",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "row_order": ("label",),
            "column_order": ("label",),
            "cells": ("x", "y", "value"),
        },
        additional_constraints=(
            "metric_name_must_be_non_empty",
            "cells_must_be_non_empty",
            "cell_coordinates_must_be_non_empty",
            "cell_values_must_be_finite",
            "performance_values_must_be_finite_probability",
            "row_order_labels_must_be_unique",
            "column_order_labels_must_be_unique",
            "declared_row_labels_must_match_cell_rows",
            "declared_column_labels_must_match_cell_columns",
            "declared_heatmap_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="confusion_matrix_heatmap_binary_inputs_v1",
        display_kind="evidence_figure",
        display_name="Binary Confusion Matrix Heatmap",
        template_ids=_template_ids_for_input_schema("confusion_matrix_heatmap_binary_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "x_label",
            "y_label",
            "metric_name",
            "normalization",
            "row_order",
            "column_order",
            "cells",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "row_order": ("label",),
            "column_order": ("label",),
            "cells": ("x", "y", "value"),
        },
        additional_constraints=(
            "metric_name_must_be_non_empty",
            "normalization_must_use_supported_vocabulary",
            "cells_must_be_non_empty",
            "cell_coordinates_must_be_non_empty",
            "cell_values_must_be_finite",
            "confusion_matrix_values_must_be_finite_probability",
            "row_order_labels_must_be_unique",
            "column_order_labels_must_be_unique",
            "binary_confusion_matrix_must_have_exactly_two_row_labels",
            "binary_confusion_matrix_must_have_exactly_two_column_labels",
            "declared_row_labels_must_match_cell_rows",
            "declared_column_labels_must_match_cell_columns",
            "declared_heatmap_grid_must_be_complete_and_unique",
            "row_fraction_confusion_rows_must_sum_to_one_when_selected",
            "column_fraction_confusion_columns_must_sum_to_one_when_selected",
            "overall_fraction_confusion_matrix_must_sum_to_one_when_selected",
        ),
    ),
    InputSchemaContract(
        input_schema_id="correlation_heatmap_inputs_v1",
        display_kind="evidence_figure",
        display_name="Correlation Heatmap",
        template_ids=_template_ids_for_input_schema("correlation_heatmap_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "y_label", "cells"),
        display_optional_fields=("paper_role",),
        collection_required_fields={"cells": ("x", "y", "value")},
        additional_constraints=(
            "matrix_must_be_square",
            "matrix_must_include_diagonal",
            "matrix_must_be_symmetric",
        ),
    ),
    InputSchemaContract(
        input_schema_id="clustered_heatmap_inputs_v1",
        display_kind="evidence_figure",
        display_name="Clustered Heatmap",
        template_ids=_template_ids_for_input_schema("clustered_heatmap_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "x_label",
            "y_label",
            "row_order",
            "column_order",
            "cells",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "row_order": ("label",),
            "column_order": ("label",),
            "cells": ("x", "y", "value"),
        },
        additional_constraints=(
            "cells_must_be_non_empty",
            "cell_coordinates_must_be_non_empty",
            "cell_values_must_be_finite",
            "row_order_labels_must_be_unique",
            "column_order_labels_must_be_unique",
            "declared_row_labels_must_match_cell_rows",
            "declared_column_labels_must_match_cell_columns",
            "declared_heatmap_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="gsva_ssgsea_heatmap_inputs_v1",
        display_kind="evidence_figure",
        display_name="GSVA/ssGSEA Heatmap",
        template_ids=_template_ids_for_input_schema("gsva_ssgsea_heatmap_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "x_label",
            "y_label",
            "score_method",
            "row_order",
            "column_order",
            "cells",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "row_order": ("label",),
            "column_order": ("label",),
            "cells": ("x", "y", "value"),
        },
        additional_constraints=(
            "score_method_must_be_non_empty",
            "cells_must_be_non_empty",
            "cell_coordinates_must_be_non_empty",
            "cell_values_must_be_finite",
            "row_order_labels_must_be_unique",
            "column_order_labels_must_be_unique",
            "declared_row_labels_must_match_cell_rows",
            "declared_column_labels_must_match_cell_columns",
            "declared_heatmap_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="pathway_enrichment_dotplot_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Pathway Enrichment Dotplot Panel",
        template_ids=_template_ids_for_input_schema("pathway_enrichment_dotplot_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "x_label",
            "y_label",
            "effect_scale_label",
            "size_scale_label",
            "panel_order",
            "pathway_order",
            "points",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panel_order": ("panel_id", "panel_title"),
            "pathway_order": ("label",),
            "points": ("panel_id", "pathway_label", "x_value", "effect_value", "size_value"),
        },
        additional_constraints=(
            "effect_scale_label_must_be_non_empty",
            "size_scale_label_must_be_non_empty",
            "panel_order_must_be_non_empty",
            "panel_order_count_must_be_at_most_two",
            "panel_ids_must_be_unique",
            "panel_titles_must_be_non_empty",
            "pathway_order_labels_must_be_unique",
            "points_must_be_non_empty",
            "point_panel_ids_must_match_declared_panels",
            "point_pathway_labels_must_match_declared_pathways",
            "point_x_values_must_be_finite",
            "point_effect_values_must_be_finite",
            "point_size_values_must_be_non_negative",
            "declared_panel_pathway_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="celltype_marker_dotplot_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Cell-Type Marker Dotplot Panel",
        template_ids=_template_ids_for_input_schema("celltype_marker_dotplot_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "x_label",
            "y_label",
            "effect_scale_label",
            "size_scale_label",
            "panel_order",
            "celltype_order",
            "marker_order",
            "points",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panel_order": ("panel_id", "panel_title"),
            "celltype_order": ("label",),
            "marker_order": ("label",),
            "points": ("panel_id", "celltype_label", "marker_label", "effect_value", "size_value"),
        },
        additional_constraints=(
            "effect_scale_label_must_be_non_empty",
            "size_scale_label_must_be_non_empty",
            "panel_order_must_be_non_empty",
            "panel_order_count_must_be_at_most_two",
            "panel_ids_must_be_unique",
            "panel_titles_must_be_non_empty",
            "celltype_order_labels_must_be_unique",
            "marker_order_labels_must_be_unique",
            "points_must_be_non_empty",
            "point_panel_ids_must_match_declared_panels",
            "point_celltype_labels_must_match_declared_celltypes",
            "point_marker_labels_must_match_declared_markers",
            "point_effect_values_must_be_finite",
            "point_size_values_must_be_non_negative",
            "declared_panel_celltype_marker_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="oncoplot_mutation_landscape_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Oncoplot Mutation Landscape Panel",
        template_ids=_template_ids_for_input_schema("oncoplot_mutation_landscape_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "y_label",
            "burden_axis_label",
            "frequency_axis_label",
            "mutation_legend_title",
            "gene_order",
            "sample_order",
            "annotation_tracks",
            "mutation_records",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "gene_order": ("label",),
            "sample_order": ("sample_id",),
            "annotation_tracks": ("track_id", "track_label", "values"),
            "mutation_records": ("sample_id", "gene_label", "alteration_class"),
        },
        nested_collection_required_fields={
            "annotation_tracks.values": ("sample_id", "category_label"),
        },
        additional_constraints=(
            "y_label_must_be_non_empty",
            "burden_axis_label_must_be_non_empty",
            "frequency_axis_label_must_be_non_empty",
            "mutation_legend_title_must_be_non_empty",
            "gene_order_must_be_non_empty",
            "gene_order_labels_must_be_unique",
            "sample_order_must_be_non_empty",
            "sample_ids_must_be_unique",
            "annotation_tracks_must_be_non_empty",
            "annotation_track_count_must_be_at_most_three",
            "annotation_track_ids_must_be_unique",
            "annotation_track_labels_must_be_non_empty",
            "annotation_track_sample_coverage_must_match_declared_sample_order",
            "annotation_track_category_labels_must_be_non_empty",
            "mutation_records_must_be_non_empty",
            "mutation_sample_ids_must_match_declared_sample_order",
            "mutation_gene_labels_must_match_declared_gene_order",
            "mutation_sample_gene_coordinates_must_be_unique",
            "alteration_class_must_be_supported",
        ),
    ),
    InputSchemaContract(
        input_schema_id="cnv_recurrence_summary_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="CNV Recurrence Summary Panel",
        template_ids=_template_ids_for_input_schema("cnv_recurrence_summary_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "y_label",
            "burden_axis_label",
            "frequency_axis_label",
            "cnv_legend_title",
            "region_order",
            "sample_order",
            "annotation_tracks",
            "cnv_records",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "region_order": ("label",),
            "sample_order": ("sample_id",),
            "annotation_tracks": ("track_id", "track_label", "values"),
            "cnv_records": ("sample_id", "region_label", "cnv_state"),
        },
        nested_collection_required_fields={
            "annotation_tracks.values": ("sample_id", "category_label"),
        },
        additional_constraints=(
            "y_label_must_be_non_empty",
            "burden_axis_label_must_be_non_empty",
            "frequency_axis_label_must_be_non_empty",
            "cnv_legend_title_must_be_non_empty",
            "region_order_must_be_non_empty",
            "region_order_labels_must_be_unique",
            "sample_order_must_be_non_empty",
            "sample_ids_must_be_unique",
            "annotation_tracks_must_be_non_empty",
            "annotation_track_count_must_be_at_most_three",
            "annotation_track_ids_must_be_unique",
            "annotation_track_labels_must_be_non_empty",
            "annotation_track_sample_coverage_must_match_declared_sample_order",
            "annotation_track_category_labels_must_be_non_empty",
            "cnv_records_must_be_non_empty",
            "cnv_sample_ids_must_match_declared_sample_order",
            "cnv_region_labels_must_match_declared_region_order",
            "cnv_sample_region_coordinates_must_be_unique",
            "cnv_state_must_be_supported",
        ),
    ),
    InputSchemaContract(
        input_schema_id="genomic_alteration_landscape_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Genomic Alteration Landscape Panel",
        template_ids=_template_ids_for_input_schema("genomic_alteration_landscape_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "y_label",
            "burden_axis_label",
            "frequency_axis_label",
            "alteration_legend_title",
            "gene_order",
            "sample_order",
            "annotation_tracks",
            "alteration_records",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "gene_order": ("label",),
            "sample_order": ("sample_id",),
            "annotation_tracks": ("track_id", "track_label", "values"),
            "alteration_records": ("sample_id", "gene_label"),
        },
        nested_collection_required_fields={
            "annotation_tracks.values": ("sample_id", "category_label"),
        },
        additional_constraints=(
            "y_label_must_be_non_empty",
            "burden_axis_label_must_be_non_empty",
            "frequency_axis_label_must_be_non_empty",
            "alteration_legend_title_must_be_non_empty",
            "gene_order_must_be_non_empty",
            "gene_order_labels_must_be_unique",
            "sample_order_must_be_non_empty",
            "sample_ids_must_be_unique",
            "annotation_tracks_must_be_non_empty",
            "annotation_track_count_must_be_at_most_three",
            "annotation_track_ids_must_be_unique",
            "annotation_track_labels_must_be_non_empty",
            "annotation_track_sample_coverage_must_match_declared_sample_order",
            "annotation_track_category_labels_must_be_non_empty",
            "alteration_records_must_be_non_empty",
            "alteration_sample_ids_must_match_declared_sample_order",
            "alteration_gene_labels_must_match_declared_gene_order",
            "alteration_sample_gene_coordinates_must_be_unique",
            "alteration_record_must_define_mutation_or_cnv",
            "mutation_class_must_be_supported_when_present",
            "cnv_state_must_be_supported_when_present",
        ),
    ),
    InputSchemaContract(
        input_schema_id="genomic_alteration_consequence_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Genomic Alteration Consequence Panel",
        template_ids=_template_ids_for_input_schema("genomic_alteration_consequence_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "y_label",
            "burden_axis_label",
            "frequency_axis_label",
            "alteration_legend_title",
            "gene_order",
            "sample_order",
            "annotation_tracks",
            "alteration_records",
            "consequence_x_label",
            "consequence_y_label",
            "consequence_legend_title",
            "effect_threshold",
            "significance_threshold",
            "driver_gene_order",
            "consequence_panel_order",
            "consequence_points",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "gene_order": ("label",),
            "sample_order": ("sample_id",),
            "annotation_tracks": ("track_id", "track_label", "values"),
            "alteration_records": ("sample_id", "gene_label"),
            "driver_gene_order": ("label",),
            "consequence_panel_order": ("panel_id", "panel_title"),
            "consequence_points": ("panel_id", "gene_label", "effect_value", "significance_value", "regulation_class"),
        },
        nested_collection_required_fields={
            "annotation_tracks.values": ("sample_id", "category_label"),
        },
        additional_constraints=(
            "y_label_must_be_non_empty",
            "burden_axis_label_must_be_non_empty",
            "frequency_axis_label_must_be_non_empty",
            "alteration_legend_title_must_be_non_empty",
            "gene_order_must_be_non_empty",
            "gene_order_labels_must_be_unique",
            "sample_order_must_be_non_empty",
            "sample_ids_must_be_unique",
            "annotation_tracks_must_be_non_empty",
            "annotation_track_count_must_be_at_most_three",
            "annotation_track_ids_must_be_unique",
            "annotation_track_labels_must_be_non_empty",
            "annotation_track_sample_coverage_must_match_declared_sample_order",
            "annotation_track_category_labels_must_be_non_empty",
            "alteration_records_must_be_non_empty",
            "alteration_sample_ids_must_match_declared_sample_order",
            "alteration_gene_labels_must_match_declared_gene_order",
            "alteration_sample_gene_coordinates_must_be_unique",
            "alteration_record_must_define_mutation_or_cnv",
            "mutation_class_must_be_supported_when_present",
            "cnv_state_must_be_supported_when_present",
            "consequence_x_label_must_be_non_empty",
            "consequence_y_label_must_be_non_empty",
            "consequence_legend_title_must_be_non_empty",
            "effect_threshold_must_be_positive",
            "significance_threshold_must_be_positive",
            "driver_gene_order_must_be_non_empty",
            "driver_gene_labels_must_be_unique",
            "driver_gene_labels_must_be_subset_of_gene_order",
            "consequence_panel_order_must_be_non_empty",
            "consequence_panel_order_count_must_be_at_most_two",
            "consequence_panel_ids_must_be_unique",
            "consequence_panel_titles_must_be_non_empty",
            "consequence_points_must_be_non_empty",
            "consequence_point_panel_ids_must_match_declared_panels",
            "consequence_point_gene_labels_must_match_declared_driver_genes",
            "consequence_point_coordinates_must_be_complete_and_unique",
            "consequence_point_effect_values_must_be_finite",
            "consequence_point_significance_values_must_be_non_negative",
            "consequence_point_regulation_classes_must_use_supported_vocabulary",
        ),
    ),
    InputSchemaContract(
        input_schema_id="genomic_alteration_multiomic_consequence_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Genomic Alteration Multiomic Consequence Panel",
        template_ids=_template_ids_for_input_schema("genomic_alteration_multiomic_consequence_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "y_label",
            "burden_axis_label",
            "frequency_axis_label",
            "alteration_legend_title",
            "gene_order",
            "sample_order",
            "annotation_tracks",
            "alteration_records",
            "consequence_x_label",
            "consequence_y_label",
            "consequence_legend_title",
            "effect_threshold",
            "significance_threshold",
            "driver_gene_order",
            "consequence_panel_order",
            "consequence_points",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "gene_order": ("label",),
            "sample_order": ("sample_id",),
            "annotation_tracks": ("track_id", "track_label", "values"),
            "alteration_records": ("sample_id", "gene_label"),
            "driver_gene_order": ("label",),
            "consequence_panel_order": ("panel_id", "panel_title"),
            "consequence_points": ("panel_id", "gene_label", "effect_value", "significance_value", "regulation_class"),
        },
        nested_collection_required_fields={
            "annotation_tracks.values": ("sample_id", "category_label"),
        },
        additional_constraints=(
            "y_label_must_be_non_empty",
            "burden_axis_label_must_be_non_empty",
            "frequency_axis_label_must_be_non_empty",
            "alteration_legend_title_must_be_non_empty",
            "gene_order_must_be_non_empty",
            "gene_order_labels_must_be_unique",
            "sample_order_must_be_non_empty",
            "sample_ids_must_be_unique",
            "annotation_tracks_must_be_non_empty",
            "annotation_track_count_must_be_at_most_three",
            "annotation_track_ids_must_be_unique",
            "annotation_track_labels_must_be_non_empty",
            "annotation_track_sample_coverage_must_match_declared_sample_order",
            "annotation_track_category_labels_must_be_non_empty",
            "alteration_records_must_be_non_empty",
            "alteration_sample_ids_must_match_declared_sample_order",
            "alteration_gene_labels_must_match_declared_gene_order",
            "alteration_sample_gene_coordinates_must_be_unique",
            "alteration_record_must_define_mutation_or_cnv",
            "mutation_class_must_be_supported_when_present",
            "cnv_state_must_be_supported_when_present",
            "consequence_x_label_must_be_non_empty",
            "consequence_y_label_must_be_non_empty",
            "consequence_legend_title_must_be_non_empty",
            "effect_threshold_must_be_positive",
            "significance_threshold_must_be_positive",
            "driver_gene_order_must_be_non_empty",
            "driver_gene_labels_must_be_unique",
            "driver_gene_labels_must_be_subset_of_gene_order",
            "consequence_panel_order_must_be_non_empty",
            "consequence_panel_order_count_must_equal_three",
            "consequence_panel_ids_must_match_multiomic_layers",
            "consequence_panel_titles_must_be_non_empty",
            "consequence_points_must_be_non_empty",
            "consequence_point_panel_ids_must_match_declared_panels",
            "consequence_point_gene_labels_must_match_declared_driver_genes",
            "consequence_point_coordinates_must_be_complete_and_unique",
            "consequence_point_effect_values_must_be_finite",
            "consequence_point_significance_values_must_be_non_negative",
            "consequence_point_regulation_classes_must_use_supported_vocabulary",
        ),
    ),
    InputSchemaContract(
        input_schema_id="genomic_alteration_pathway_integrated_composite_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Genomic Alteration Pathway-Integrated Composite Panel",
        template_ids=_template_ids_for_input_schema("genomic_alteration_pathway_integrated_composite_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "y_label",
            "burden_axis_label",
            "frequency_axis_label",
            "alteration_legend_title",
            "gene_order",
            "sample_order",
            "annotation_tracks",
            "alteration_records",
            "consequence_x_label",
            "consequence_y_label",
            "consequence_legend_title",
            "effect_threshold",
            "significance_threshold",
            "driver_gene_order",
            "consequence_panel_order",
            "consequence_points",
            "pathway_x_label",
            "pathway_y_label",
            "pathway_effect_scale_label",
            "pathway_size_scale_label",
            "pathway_order",
            "pathway_panel_order",
            "pathway_points",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "gene_order": ("label",),
            "sample_order": ("sample_id",),
            "annotation_tracks": ("track_id", "track_label", "values"),
            "alteration_records": ("sample_id", "gene_label"),
            "driver_gene_order": ("label",),
            "consequence_panel_order": ("panel_id", "panel_title"),
            "consequence_points": ("panel_id", "gene_label", "effect_value", "significance_value", "regulation_class"),
            "pathway_order": ("label",),
            "pathway_panel_order": ("panel_id", "panel_title"),
            "pathway_points": ("panel_id", "pathway_label", "x_value", "effect_value", "size_value"),
        },
        nested_collection_required_fields={
            "annotation_tracks.values": ("sample_id", "category_label"),
        },
        additional_constraints=(
            "y_label_must_be_non_empty",
            "burden_axis_label_must_be_non_empty",
            "frequency_axis_label_must_be_non_empty",
            "alteration_legend_title_must_be_non_empty",
            "gene_order_must_be_non_empty",
            "gene_order_labels_must_be_unique",
            "sample_order_must_be_non_empty",
            "sample_ids_must_be_unique",
            "annotation_tracks_must_be_non_empty",
            "annotation_track_count_must_be_at_most_three",
            "annotation_track_ids_must_be_unique",
            "annotation_track_labels_must_be_non_empty",
            "annotation_track_sample_coverage_must_match_declared_sample_order",
            "annotation_track_category_labels_must_be_non_empty",
            "alteration_records_must_be_non_empty",
            "alteration_sample_ids_must_match_declared_sample_order",
            "alteration_gene_labels_must_match_declared_gene_order",
            "alteration_sample_gene_coordinates_must_be_unique",
            "alteration_record_must_define_mutation_or_cnv",
            "mutation_class_must_be_supported_when_present",
            "cnv_state_must_be_supported_when_present",
            "consequence_x_label_must_be_non_empty",
            "consequence_y_label_must_be_non_empty",
            "consequence_legend_title_must_be_non_empty",
            "effect_threshold_must_be_positive",
            "significance_threshold_must_be_positive",
            "driver_gene_order_must_be_non_empty",
            "driver_gene_labels_must_be_unique",
            "driver_gene_labels_must_be_subset_of_gene_order",
            "consequence_panel_order_must_be_non_empty",
            "consequence_panel_order_count_must_equal_three",
            "consequence_panel_ids_must_match_multiomic_layers",
            "consequence_panel_titles_must_be_non_empty",
            "consequence_points_must_be_non_empty",
            "consequence_point_panel_ids_must_match_declared_panels",
            "consequence_point_gene_labels_must_match_declared_driver_genes",
            "consequence_point_coordinates_must_be_complete_and_unique",
            "consequence_point_effect_values_must_be_finite",
            "consequence_point_significance_values_must_be_non_negative",
            "consequence_point_regulation_classes_must_use_supported_vocabulary",
            "pathway_x_label_must_be_non_empty",
            "pathway_y_label_must_be_non_empty",
            "pathway_effect_scale_label_must_be_non_empty",
            "pathway_size_scale_label_must_be_non_empty",
            "pathway_order_must_be_non_empty",
            "pathway_order_labels_must_be_unique",
            "pathway_panel_order_must_be_non_empty",
            "pathway_panel_order_count_must_equal_three",
            "pathway_panel_ids_must_match_multiomic_layers",
            "pathway_panel_titles_must_be_non_empty",
            "pathway_points_must_be_non_empty",
            "pathway_point_panel_ids_must_match_declared_panels",
            "pathway_point_labels_must_match_declared_pathways",
            "pathway_point_coordinates_must_be_complete_and_unique",
            "pathway_point_x_values_must_be_finite",
            "pathway_point_effect_values_must_be_finite",
            "pathway_point_size_values_must_be_non_negative",
        ),
    ),
    InputSchemaContract(
        input_schema_id="genomic_program_governance_summary_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Genomic Program Governance Summary Panel",
        template_ids=_template_ids_for_input_schema("genomic_program_governance_summary_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "evidence_panel_title",
            "summary_panel_title",
            "effect_scale_label",
            "support_scale_label",
            "layer_order",
            "programs",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "layer_order": ("layer_id", "layer_label"),
            "programs": (
                "program_id",
                "program_label",
                "lead_driver_label",
                "dominant_pathway_label",
                "pathway_hit_count",
                "priority_rank",
                "priority_band",
                "verdict",
                "action",
                "layer_supports",
            ),
        },
        collection_optional_fields={"programs": ("detail",)},
        nested_collection_required_fields={
            "programs.layer_supports": ("layer_id", "effect_value", "support_fraction"),
        },
        additional_constraints=(
            "evidence_panel_title_must_be_non_empty",
            "summary_panel_title_must_be_non_empty",
            "effect_scale_label_must_be_non_empty",
            "support_scale_label_must_be_non_empty",
            "layer_order_must_be_non_empty",
            "layer_order_count_must_equal_five",
            "layer_ids_must_match_supported_vocabulary",
            "layer_labels_must_be_non_empty",
            "programs_must_be_non_empty",
            "program_ids_must_be_unique",
            "program_labels_must_be_unique",
            "lead_driver_labels_must_be_non_empty",
            "dominant_pathway_labels_must_be_non_empty",
            "pathway_hit_counts_must_be_positive_integers",
            "priority_ranks_must_be_strictly_increasing",
            "priority_bands_must_be_supported",
            "verdicts_must_be_supported",
            "actions_must_be_non_empty",
            "program_detail_must_be_non_empty_when_present",
            "layer_supports_must_be_non_empty",
            "layer_supports_must_cover_declared_layers_exactly_once",
            "layer_support_effect_values_must_be_finite",
            "layer_support_fractions_must_be_probability",
        ),
    ),
)
