from __future__ import annotations

from tests.test_study_progress_mission_summary_cases.materialized_run_readback import (
    test_artifact_first_mission_summary_prefers_materialized_paper_mission_run,
    test_materialized_mission_summary_does_not_let_opl_closeout_override_stage_outcome,
)
from tests.test_study_progress_mission_summary_cases.governed_consumption_readback import (
    test_materialized_mission_summary_prefers_latest_governed_consumption_ledger,
    test_consumption_ledger_summary_uses_terminalized_stage_closure_readback,
    test_materialized_mission_summary_consumes_receipt_owner_consumption_ledger,
    test_typed_blocker_resolution_successor_supersedes_stale_wakeup_top_level,
    test_materialized_mission_summary_keeps_governed_consumption_current_when_terminal_residue_exists,
)
from tests.test_study_progress_mission_summary_cases.submission_owner_gate_readback import (
    test_submission_authority_owner_gate_removes_superseded_next_action,
    test_submission_authority_owner_gate_keeps_new_next_action_for_different_identity,
)
