from __future__ import annotations

from .core import InputSchemaContract, _template_ids_for_input_schema

_INPUT_SCHEMA_CONTRACTS_GENERAL_PUBLICATION: tuple[InputSchemaContract, ...] = (
    InputSchemaContract(
        input_schema_id="generalizability_subgroup_composite_inputs_v1",
        display_kind="evidence_figure",
        display_name="Generalizability and Subgroup Composite Panel",
        template_ids=_template_ids_for_input_schema("generalizability_subgroup_composite_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "metric_family",
            "primary_label",
            "overview_panel_title",
            "overview_x_label",
            "overview_rows",
            "subgroup_panel_title",
            "subgroup_x_label",
            "subgroup_reference_value",
            "subgroup_rows",
        ),
        display_optional_fields=("paper_role", "comparator_label"),
        collection_required_fields={
            "overview_rows": ("cohort_id", "cohort_label", "support_count", "metric_value"),
            "subgroup_rows": ("subgroup_id", "subgroup_label", "estimate", "lower", "upper"),
        },
        collection_optional_fields={
            "overview_rows": ("comparator_metric_value", "event_count"),
            "subgroup_rows": ("group_n",),
        },
        additional_constraints=(
            "metric_family_must_be_supported",
            "primary_label_must_be_non_empty",
            "overview_rows_must_be_non_empty",
            "overview_cohort_ids_must_be_unique",
            "overview_cohort_labels_must_be_unique",
            "overview_support_counts_must_be_non_negative",
            "overview_event_counts_must_be_non_negative_when_present",
            "overview_metric_values_must_be_finite",
            "overview_comparator_metric_values_must_be_finite_when_present",
            "overview_comparator_metric_values_must_be_present_for_all_rows_when_comparator_label_is_declared",
            "overview_comparator_metric_values_must_be_absent_without_comparator_label",
            "subgroup_reference_value_must_be_finite",
            "subgroup_rows_must_be_non_empty",
            "subgroup_ids_must_be_unique",
            "subgroup_labels_must_be_unique",
            "subgroup_values_must_be_finite",
            "subgroup_group_n_must_be_non_negative_when_present",
            "subgroup_rows_must_satisfy_lower_le_estimate_le_upper",
        ),
    ),
    InputSchemaContract(
        input_schema_id="cohort_flow_shell_inputs_v1",
        display_kind="illustration_shell",
        display_name="Cohort Flow Figure",
        template_ids=_template_ids_for_input_schema("cohort_flow_shell_inputs_v1"),
        required_top_level_fields=("schema_version", "shell_id", "display_id", "title", "steps"),
        optional_top_level_fields=("caption", "exclusions", "endpoint_inventory", "design_panels"),
        collection_required_fields={
            "steps": ("step_id", "label", "n"),
            "exclusions": ("exclusion_id", "from_step_id", "label", "n"),
            "endpoint_inventory": ("endpoint_id", "label", "event_n"),
            "design_panels": ("panel_id", "title", "layout_role", "lines"),
        },
        collection_optional_fields={
            "steps": ("detail",),
            "exclusions": ("detail",),
            "endpoint_inventory": ("detail",),
        },
        nested_collection_required_fields={"design_panels.lines": ("label",)},
        nested_collection_optional_fields={"design_panels.lines": ("detail",)},
        additional_constraints=(
            "steps_must_be_non_empty",
            "step_ids_must_be_unique",
            "step_label_must_be_non_empty",
            "step_n_must_be_integer",
            "exclusions_from_step_ids_must_reference_steps",
            "exclusion_ids_must_be_unique",
            "exclusion_n_must_be_integer",
            "endpoint_inventory_ids_must_be_unique",
            "endpoint_inventory_event_n_must_be_integer",
            "design_panel_ids_must_be_unique",
            "design_panel_layout_roles_must_be_supported_and_unique",
            "design_panel_lines_must_be_non_empty",
        ),
    ),
    InputSchemaContract(
        input_schema_id="submission_graphical_abstract_inputs_v1",
        display_kind="illustration_shell",
        display_name="Submission Graphical Abstract",
        template_ids=_template_ids_for_input_schema("submission_graphical_abstract_inputs_v1"),
        required_top_level_fields=("schema_version", "shell_id", "display_id", "catalog_id", "title", "caption", "panels"),
        optional_top_level_fields=("paper_role", "footer_pills"),
        collection_required_fields={"panels": ("panel_id", "panel_label", "title", "subtitle", "rows")},
        collection_optional_fields={"footer_pills": ("pill_id", "label", "style_role")},
        nested_collection_required_fields={
            "panels.rows": ("cards",),
            "panels.rows.cards": ("card_id", "title", "value"),
        },
        nested_collection_optional_fields={
            "panels.rows.cards": ("detail", "accent_role"),
            "footer_pills": ("panel_id",),
        },
        additional_constraints=(
            "graphical_abstract_panels_must_be_non_empty",
            "graphical_abstract_panel_ids_must_be_unique",
            "graphical_abstract_rows_must_be_non_empty",
            "graphical_abstract_cards_must_be_non_empty",
            "graphical_abstract_footer_pills_must_reference_known_panels_when_present",
        ),
    ),
    InputSchemaContract(
        input_schema_id="workflow_fact_sheet_panel_inputs_v1",
        display_kind="illustration_shell",
        display_name="Workflow Fact Sheet Panel",
        template_ids=_template_ids_for_input_schema("workflow_fact_sheet_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "shell_id", "display_id", "title", "sections"),
        optional_top_level_fields=("caption",),
        collection_required_fields={
            "sections": ("section_id", "panel_label", "title", "layout_role", "facts"),
        },
        nested_collection_required_fields={
            "sections.facts": ("fact_id", "label", "value"),
        },
        nested_collection_optional_fields={
            "sections.facts": ("detail",),
        },
        additional_constraints=(
            "sections_must_contain_exactly_four_items",
            "section_ids_must_be_unique",
            "section_panel_labels_must_be_unique",
            "section_layout_roles_must_match_four_panel_fact_sheet_grid",
            "section_facts_must_be_non_empty",
            "section_fact_ids_must_be_unique_within_section",
        ),
    ),
    InputSchemaContract(
        input_schema_id="design_evidence_composite_shell_inputs_v1",
        display_kind="illustration_shell",
        display_name="Design Evidence Composite Shell",
        template_ids=_template_ids_for_input_schema("design_evidence_composite_shell_inputs_v1"),
        required_top_level_fields=(
            "schema_version",
            "shell_id",
            "display_id",
            "title",
            "workflow_stages",
            "summary_panels",
        ),
        optional_top_level_fields=("caption",),
        collection_required_fields={
            "workflow_stages": ("stage_id", "title"),
            "summary_panels": ("panel_id", "panel_label", "title", "layout_role", "cards"),
        },
        nested_collection_required_fields={
            "summary_panels.cards": ("card_id", "label", "value"),
        },
        nested_collection_optional_fields={
            "workflow_stages": ("detail",),
            "summary_panels.cards": ("detail",),
        },
        additional_constraints=(
            "workflow_stages_must_contain_three_or_four_items",
            "workflow_stage_ids_must_be_unique",
            "summary_panels_must_contain_exactly_three_items",
            "summary_panel_ids_must_be_unique",
            "summary_panel_labels_must_be_unique",
            "summary_panel_layout_roles_must_match_three_panel_composite",
            "summary_panel_cards_must_be_non_empty",
            "summary_panel_card_ids_must_be_unique_within_panel",
        ),
    ),
    InputSchemaContract(
        input_schema_id="baseline_characteristics_schema_v1",
        display_kind="table_shell",
        display_name="Baseline Characteristics Table",
        template_ids=_template_ids_for_input_schema("baseline_characteristics_schema_v1"),
        required_top_level_fields=("schema_version", "table_shell_id", "display_id", "title", "groups", "variables"),
        optional_top_level_fields=("caption",),
        collection_required_fields={
            "groups": ("group_id", "label"),
            "variables": ("variable_id", "label", "values"),
        },
        additional_constraints=(
            "groups_must_be_non_empty",
            "variables_must_be_non_empty",
            "variable_values_length_must_match_groups",
        ),
    ),
    InputSchemaContract(
        input_schema_id="time_to_event_performance_summary_v1",
        display_kind="table_shell",
        display_name="Time-to-Event Performance Summary Table",
        template_ids=_template_ids_for_input_schema("time_to_event_performance_summary_v1"),
        required_top_level_fields=("schema_version", "table_shell_id", "display_id", "title", "columns", "rows"),
        optional_top_level_fields=("caption",),
        collection_required_fields={
            "columns": ("column_id", "label"),
            "rows": ("row_id", "label", "values"),
        },
        additional_constraints=(
            "columns_must_be_non_empty",
            "rows_must_be_non_empty",
            "row_values_length_must_match_columns",
        ),
    ),
    InputSchemaContract(
        input_schema_id="clinical_interpretation_summary_v1",
        display_kind="table_shell",
        display_name="Clinical Interpretation Summary Table",
        template_ids=_template_ids_for_input_schema("clinical_interpretation_summary_v1"),
        required_top_level_fields=("schema_version", "table_shell_id", "display_id", "title", "columns", "rows"),
        optional_top_level_fields=("caption",),
        collection_required_fields={
            "columns": ("column_id", "label"),
            "rows": ("row_id", "label", "values"),
        },
        additional_constraints=(
            "columns_must_be_non_empty",
            "rows_must_be_non_empty",
            "row_values_length_must_match_columns",
        ),
    ),
    InputSchemaContract(
        input_schema_id="performance_summary_table_generic_v1",
        display_kind="table_shell",
        display_name="Performance Summary Table (Generic)",
        template_ids=_template_ids_for_input_schema("performance_summary_table_generic_v1"),
        required_top_level_fields=("schema_version", "table_shell_id", "display_id", "title", "row_header_label", "columns", "rows"),
        optional_top_level_fields=("caption",),
        collection_required_fields={
            "columns": ("column_id", "label"),
            "rows": ("row_id", "label", "values"),
        },
        additional_constraints=(
            "row_header_label_must_be_non_empty",
            "columns_must_be_non_empty",
            "rows_must_be_non_empty",
            "row_values_length_must_match_columns",
        ),
    ),
    InputSchemaContract(
        input_schema_id="grouped_risk_event_summary_table_v1",
        display_kind="table_shell",
        display_name="Grouped Risk Event Summary Table",
        template_ids=_template_ids_for_input_schema("grouped_risk_event_summary_table_v1"),
        required_top_level_fields=(
            "schema_version",
            "table_shell_id",
            "display_id",
            "title",
            "surface_column_label",
            "stratum_column_label",
            "cases_column_label",
            "events_column_label",
            "risk_column_label",
            "rows",
        ),
        optional_top_level_fields=("caption",),
        collection_required_fields={
            "rows": ("row_id", "surface", "stratum", "cases", "events", "risk_display"),
        },
        additional_constraints=(
            "surface_column_label_must_be_non_empty",
            "stratum_column_label_must_be_non_empty",
            "cases_column_label_must_be_non_empty",
            "events_column_label_must_be_non_empty",
            "risk_column_label_must_be_non_empty",
            "rows_must_be_non_empty",
            "row_surface_must_be_non_empty",
            "row_stratum_must_be_non_empty",
            "row_cases_must_be_positive_integer",
            "row_events_must_be_integer_between_zero_and_cases",
            "row_risk_display_must_match_events_over_cases_percent_1dp",
        ),
    ),
)
