from __future__ import annotations

from .core import InputSchemaContract, _template_ids_for_input_schema

_INPUT_SCHEMA_CONTRACTS_EXPLANATIONS: tuple[InputSchemaContract, ...] = (
    InputSchemaContract(
        input_schema_id="shap_summary_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Summary Beeswarm",
        template_ids=_template_ids_for_input_schema("shap_summary_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "rows"),
        display_optional_fields=("paper_role",),
        collection_required_fields={"rows": ("feature", "points")},
        nested_collection_required_fields={"rows.points": ("shap_value", "feature_value")},
        additional_constraints=(
            "rows_must_be_non_empty",
            "row_feature_must_be_non_empty",
            "row_points_must_be_non_empty",
            "shap_values_must_be_finite",
            "feature_values_must_be_finite",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_bar_importance_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Bar Importance Panel",
        template_ids=_template_ids_for_input_schema("shap_bar_importance_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "bars"),
        display_optional_fields=("paper_role",),
        collection_required_fields={"bars": ("rank", "feature", "importance_value")},
        additional_constraints=(
            "bars_must_be_non_empty",
            "bar_features_must_be_unique",
            "bar_ranks_must_be_strictly_increasing",
            "bar_importance_values_must_be_non_negative_finite",
            "bar_importance_values_must_be_sorted_descending_by_rank",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_signed_importance_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Signed Importance Panel",
        template_ids=_template_ids_for_input_schema("shap_signed_importance_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "x_label",
            "negative_label",
            "positive_label",
            "bars",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={"bars": ("rank", "feature", "signed_importance_value")},
        additional_constraints=(
            "bars_must_be_non_empty",
            "bar_features_must_be_unique",
            "bar_ranks_must_be_strictly_increasing",
            "bar_signed_importance_values_must_be_finite_and_non_zero",
            "bar_signed_importance_values_must_be_sorted_by_absolute_magnitude_descending",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_multicohort_importance_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Multicohort Importance Panel",
        template_ids=_template_ids_for_input_schema("shap_multicohort_importance_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "cohort_label", "bars"),
        },
        nested_collection_required_fields={
            "panels.bars": ("rank", "feature", "importance_value"),
        },
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_not_exceed_three",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_cohort_labels_must_be_unique",
            "panel_bars_must_be_non_empty",
            "panel_bar_features_must_be_unique_within_panel",
            "panel_bar_ranks_must_be_strictly_increasing",
            "panel_bar_importance_values_must_be_non_negative_finite",
            "panel_bar_importance_values_must_be_sorted_descending_by_rank",
            "panel_feature_orders_must_match_across_panels",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_dependence_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Dependence Panel",
        template_ids=_template_ids_for_input_schema("shap_dependence_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "y_label", "colorbar_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "x_label", "feature", "interaction_feature", "points"),
        },
        nested_collection_required_fields={
            "panels.points": ("feature_value", "shap_value", "interaction_value"),
        },
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_features_must_be_unique",
            "panel_points_must_be_non_empty",
            "panel_point_values_must_be_finite",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_waterfall_local_explanation_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Waterfall Local Explanation Panel",
        template_ids=_template_ids_for_input_schema("shap_waterfall_local_explanation_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "case_label", "baseline_value", "predicted_value", "contributions"),
        },
        nested_collection_required_fields={"panels.contributions": ("feature", "shap_value")},
        nested_collection_optional_fields={"panels.contributions": ("feature_value_text",)},
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_not_exceed_three",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_case_labels_must_be_unique",
            "panel_values_must_be_finite",
            "panel_contributions_must_be_non_empty",
            "panel_contribution_features_must_be_unique_within_panel",
            "panel_contribution_values_must_be_finite_and_non_zero",
            "panel_prediction_value_must_equal_baseline_plus_contributions",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_force_like_summary_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Force-like Summary Panel",
        template_ids=_template_ids_for_input_schema("shap_force_like_summary_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "case_label", "baseline_value", "predicted_value", "contributions"),
        },
        nested_collection_required_fields={"panels.contributions": ("feature", "shap_value")},
        nested_collection_optional_fields={"panels.contributions": ("feature_value_text",)},
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_not_exceed_three",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_case_labels_must_be_unique",
            "panel_values_must_be_finite",
            "panel_contributions_must_be_non_empty",
            "panel_contribution_features_must_be_unique_within_panel",
            "panel_contribution_values_must_be_finite_and_non_zero",
            "panel_prediction_value_must_equal_baseline_plus_contributions",
            "panel_contributions_must_be_sorted_by_absolute_magnitude_descending",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_grouped_local_explanation_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Grouped Local Explanation Panel",
        template_ids=_template_ids_for_input_schema("shap_grouped_local_explanation_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "group_label", "baseline_value", "predicted_value", "contributions"),
        },
        nested_collection_required_fields={"panels.contributions": ("rank", "feature", "shap_value")},
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_not_exceed_three",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_group_labels_must_be_unique",
            "panel_values_must_be_finite",
            "panel_contributions_must_be_non_empty",
            "panel_contribution_ranks_must_be_strictly_increasing",
            "panel_contribution_features_must_be_unique_within_panel",
            "panel_contribution_values_must_be_finite_and_non_zero",
            "panel_prediction_value_must_equal_baseline_plus_contributions",
            "panel_feature_orders_must_match_across_panels",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_grouped_decision_path_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Grouped Decision Path Panel",
        template_ids=_template_ids_for_input_schema("shap_grouped_decision_path_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "panel_title",
            "x_label",
            "y_label",
            "legend_title",
            "baseline_value",
            "groups",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "groups": ("group_id", "group_label", "predicted_value", "contributions"),
        },
        nested_collection_required_fields={
            "groups.contributions": ("rank", "feature", "shap_value"),
        },
        additional_constraints=(
            "group_count_must_equal_two",
            "group_ids_must_be_unique",
            "group_labels_must_be_unique",
            "baseline_value_must_be_finite",
            "group_prediction_value_must_equal_baseline_plus_contributions",
            "group_contribution_ranks_must_be_strictly_increasing",
            "group_contribution_values_must_be_finite_and_non_zero",
            "group_feature_orders_must_match",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_multigroup_decision_path_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Multigroup Decision Path Panel",
        template_ids=_template_ids_for_input_schema("shap_multigroup_decision_path_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "panel_title",
            "x_label",
            "y_label",
            "legend_title",
            "baseline_value",
            "groups",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "groups": ("group_id", "group_label", "predicted_value", "contributions"),
        },
        nested_collection_required_fields={
            "groups.contributions": ("rank", "feature", "shap_value"),
        },
        additional_constraints=(
            "group_count_must_equal_three",
            "group_ids_must_be_unique",
            "group_labels_must_be_unique",
            "baseline_value_must_be_finite",
            "group_prediction_value_must_equal_baseline_plus_contributions",
            "group_contribution_ranks_must_be_strictly_increasing",
            "group_contribution_values_must_be_finite_and_non_zero",
            "group_feature_orders_must_match",
        ),
    ),
    InputSchemaContract(
        input_schema_id="partial_dependence_ice_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Partial Dependence and ICE Panel",
        template_ids=_template_ids_for_input_schema("partial_dependence_ice_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "y_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": (
                "panel_id",
                "panel_label",
                "title",
                "x_label",
                "feature",
                "reference_value",
                "reference_label",
                "pdp_curve",
                "ice_curves",
            ),
        },
        nested_collection_required_fields={
            "panels.pdp_curve": ("x", "y"),
            "panels.ice_curves": ("curve_id", "x", "y"),
        },
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_not_exceed_three",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_features_must_be_unique",
            "panel_reference_labels_must_be_non_empty",
            "panel_reference_values_must_be_finite",
            "panel_pdp_curve_must_have_matching_x_y_lengths",
            "panel_pdp_curve_x_must_be_strictly_increasing",
            "panel_pdp_curve_values_must_be_finite",
            "panel_ice_curves_must_be_non_empty",
            "panel_ice_curve_ids_must_be_unique_within_panel",
            "ice_curve_x_y_lengths_must_match",
            "ice_curve_x_grids_must_match_pdp_curve_x",
            "ice_curve_values_must_be_finite",
            "panel_reference_values_must_fall_within_pdp_curve_range",
        ),
    ),
    InputSchemaContract(
        input_schema_id="partial_dependence_interaction_contour_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Partial Dependence Interaction Contour Panel",
        template_ids=_template_ids_for_input_schema("partial_dependence_interaction_contour_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "colorbar_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": (
                "panel_id",
                "panel_label",
                "title",
                "x_label",
                "y_label",
                "x_feature",
                "y_feature",
                "reference_x_value",
                "reference_y_value",
                "reference_label",
                "x_grid",
                "y_grid",
                "response_grid",
                "observed_points",
            ),
        },
        nested_collection_required_fields={"panels.observed_points": ("point_id", "x", "y")},
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_not_exceed_two",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_feature_pairs_must_be_unique",
            "panel_reference_labels_must_be_non_empty",
            "panel_x_grids_must_be_strictly_increasing",
            "panel_y_grids_must_be_strictly_increasing",
            "panel_response_grids_must_match_declared_axes",
            "panel_response_values_must_be_finite",
            "panel_observed_points_must_be_non_empty",
            "panel_observed_point_ids_must_be_unique_within_panel",
            "panel_observed_points_must_be_finite",
            "panel_observed_points_must_fall_within_declared_grid_range",
            "panel_reference_point_must_fall_within_declared_grid_range",
        ),
    ),
    InputSchemaContract(
        input_schema_id="partial_dependence_interaction_slice_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Partial Dependence Interaction Slice Panel",
        template_ids=_template_ids_for_input_schema("partial_dependence_interaction_slice_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "y_label",
            "legend_title",
            "panels",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": (
                "panel_id",
                "panel_label",
                "title",
                "x_label",
                "x_feature",
                "slice_feature",
                "reference_value",
                "reference_label",
                "slice_curves",
            ),
        },
        nested_collection_required_fields={
            "panels.slice_curves": ("slice_id", "slice_label", "conditioning_value", "x", "y"),
        },
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_not_exceed_two",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_feature_pairs_must_be_unique",
            "panel_reference_labels_must_be_non_empty",
            "panel_reference_values_must_be_finite",
            "panel_slice_curves_must_have_at_least_two_entries",
            "panel_slice_curve_ids_must_be_unique_within_panel",
            "panel_slice_curve_labels_must_be_unique_within_panel",
            "panel_slice_curve_x_y_lengths_must_match",
            "panel_slice_curve_x_must_be_strictly_increasing",
            "panel_slice_curve_values_must_be_finite",
            "panel_slice_curve_x_grids_must_match_within_panel",
            "panel_reference_values_must_fall_within_slice_curve_range",
            "panel_slice_label_sets_must_match_across_panels",
        ),
    ),
    InputSchemaContract(
        input_schema_id="partial_dependence_subgroup_comparison_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Partial Dependence Subgroup Comparison Panel",
        template_ids=_template_ids_for_input_schema("partial_dependence_subgroup_comparison_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "y_label",
            "subgroup_panel_label",
            "subgroup_panel_title",
            "subgroup_x_label",
            "panels",
            "subgroup_rows",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": (
                "panel_id",
                "panel_label",
                "subgroup_label",
                "title",
                "x_label",
                "feature",
                "reference_value",
                "reference_label",
                "pdp_curve",
                "ice_curves",
            ),
            "subgroup_rows": ("row_id", "panel_id", "row_label", "estimate", "lower", "upper", "support_n"),
        },
        nested_collection_required_fields={
            "panels.pdp_curve": ("x", "y"),
            "panels.ice_curves": ("curve_id", "x", "y"),
        },
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_not_exceed_three",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_subgroup_labels_must_be_unique",
            "panel_reference_labels_must_be_non_empty",
            "panel_reference_values_must_be_finite",
            "panel_pdp_curve_must_have_matching_x_y_lengths",
            "panel_pdp_curve_x_must_be_strictly_increasing",
            "panel_pdp_curve_values_must_be_finite",
            "panel_ice_curves_must_be_non_empty",
            "panel_ice_curve_ids_must_be_unique_within_panel",
            "panel_ice_curve_x_y_lengths_must_match",
            "panel_ice_curve_x_grids_must_match_pdp_curve_x",
            "panel_ice_curve_values_must_be_finite",
            "panel_reference_values_must_fall_within_pdp_curve_range",
            "subgroup_rows_must_be_non_empty",
            "subgroup_panel_label_must_be_distinct_from_top_panel_labels",
            "subgroup_rows_must_match_panels_by_panel_id",
            "subgroup_row_ids_must_be_unique",
            "subgroup_row_labels_must_be_unique",
            "subgroup_row_intervals_must_wrap_estimate",
            "subgroup_row_support_n_must_be_positive",
        ),
    ),
    InputSchemaContract(
        input_schema_id="accumulated_local_effects_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Accumulated Local Effects Panel",
        template_ids=_template_ids_for_input_schema("accumulated_local_effects_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "y_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": (
                "panel_id",
                "panel_label",
                "title",
                "x_label",
                "feature",
                "reference_value",
                "reference_label",
                "ale_curve",
                "local_effect_bins",
            ),
        },
        nested_collection_required_fields={
            "panels.ale_curve": ("x", "y"),
            "panels.local_effect_bins": (
                "bin_id",
                "bin_left",
                "bin_right",
                "bin_center",
                "local_effect",
                "support_count",
            ),
        },
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_not_exceed_three",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_features_must_be_unique",
            "panel_reference_labels_must_be_non_empty",
            "panel_reference_values_must_be_finite",
            "panel_ale_curve_must_have_matching_x_y_lengths",
            "panel_ale_curve_x_must_be_strictly_increasing",
            "panel_ale_curve_values_must_be_finite",
            "panel_local_effect_bins_must_be_non_empty",
            "panel_local_effect_bin_ids_must_be_unique_within_panel",
            "panel_local_effect_bins_must_be_strictly_ordered_and_non_overlapping",
            "panel_local_effect_values_must_be_finite",
            "panel_local_effect_support_counts_must_be_positive",
            "panel_ale_curve_x_must_match_bin_centers",
            "panel_ale_curve_must_match_cumulative_local_effects",
            "panel_reference_values_must_fall_within_declared_bin_range",
        ),
    ),
    InputSchemaContract(
        input_schema_id="feature_response_support_domain_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Feature Response Support Domain Panel",
        template_ids=_template_ids_for_input_schema("feature_response_support_domain_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "y_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": (
                "panel_id",
                "panel_label",
                "title",
                "x_label",
                "feature",
                "reference_value",
                "reference_label",
                "response_curve",
                "support_segments",
            ),
        },
        nested_collection_required_fields={
            "panels.response_curve": ("x", "y"),
            "panels.support_segments": (
                "segment_id",
                "segment_label",
                "support_kind",
                "domain_start",
                "domain_end",
            ),
        },
        additional_constraints=(
            "panels_must_be_non_empty",
            "panel_count_must_be_between_two_and_three",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_features_must_be_unique",
            "panel_reference_labels_must_be_non_empty",
            "panel_reference_values_must_be_finite",
            "panel_response_curve_must_have_matching_x_y_lengths",
            "panel_response_curve_x_must_be_strictly_increasing",
            "panel_response_curve_values_must_be_finite",
            "panel_support_segments_must_be_non_empty",
            "panel_support_segment_ids_must_be_unique_within_panel",
            "panel_support_segment_labels_must_be_non_empty",
            "panel_support_segment_kinds_must_be_supported",
            "panel_support_segments_must_be_strictly_ordered_and_non_overlapping",
            "panel_support_segments_must_cover_curve_range",
            "panel_reference_values_must_fall_within_response_curve_range",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_grouped_local_support_domain_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Grouped Local Support-Domain Panel",
        template_ids=_template_ids_for_input_schema("shap_grouped_local_support_domain_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "grouped_local_x_label",
            "support_y_label",
            "support_legend_title",
            "local_panels",
            "support_panels",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "local_panels": (
                "panel_id",
                "panel_label",
                "title",
                "group_label",
                "baseline_value",
                "predicted_value",
                "contributions",
            ),
            "support_panels": (
                "panel_id",
                "panel_label",
                "title",
                "x_label",
                "feature",
                "reference_value",
                "reference_label",
                "response_curve",
                "support_segments",
            ),
        },
        nested_collection_required_fields={
            "local_panels.contributions": ("rank", "feature", "shap_value"),
            "support_panels.response_curve": ("x", "y"),
            "support_panels.support_segments": (
                "segment_id",
                "segment_label",
                "support_kind",
                "domain_start",
                "domain_end",
            ),
        },
        additional_constraints=(
            "local_panels_must_be_non_empty",
            "local_panel_count_must_be_between_two_and_three",
            "local_panel_ids_must_be_unique",
            "local_panel_labels_must_be_unique",
            "local_panel_group_labels_must_be_unique",
            "local_panel_values_must_be_finite",
            "local_panel_contributions_must_be_non_empty",
            "local_panel_contribution_ranks_must_be_strictly_increasing",
            "local_panel_contribution_features_must_be_unique_within_panel",
            "local_panel_contribution_values_must_be_finite_and_non_zero",
            "local_panel_prediction_value_must_equal_baseline_plus_contributions",
            "local_panel_feature_orders_must_match_across_panels",
            "support_panels_must_be_non_empty",
            "support_panel_count_must_equal_two",
            "support_panel_ids_must_be_unique",
            "support_panel_labels_must_be_unique_and_distinct_from_local_panel_labels",
            "support_panel_labels_must_be_distinct_from_local_panel_labels",
            "support_panel_features_must_be_unique",
            "support_panel_reference_labels_must_be_non_empty",
            "support_panel_reference_values_must_be_finite",
            "support_panel_response_curve_must_have_matching_x_y_lengths",
            "support_panel_response_curve_x_must_be_strictly_increasing",
            "support_panel_response_curve_values_must_be_finite",
            "support_panel_support_segments_must_be_non_empty",
            "support_panel_support_segment_ids_must_be_unique_within_panel",
            "support_panel_support_segment_kinds_must_be_supported",
            "support_panel_support_segments_must_be_strictly_ordered_and_non_overlapping",
            "support_panel_support_segments_must_cover_curve_range",
            "support_panel_reference_values_must_fall_within_response_curve_range",
            "support_panel_features_must_be_subset_of_local_feature_order",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_multigroup_decision_path_support_domain_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Multigroup Decision Path Support-Domain Panel",
        template_ids=_template_ids_for_input_schema("shap_multigroup_decision_path_support_domain_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "decision_panel_title",
            "decision_x_label",
            "decision_y_label",
            "decision_legend_title",
            "support_y_label",
            "support_legend_title",
            "baseline_value",
            "groups",
            "support_panels",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "groups": ("group_id", "group_label", "predicted_value", "contributions"),
            "support_panels": (
                "panel_id",
                "panel_label",
                "title",
                "x_label",
                "feature",
                "reference_value",
                "reference_label",
                "response_curve",
                "support_segments",
            ),
        },
        nested_collection_required_fields={
            "groups.contributions": ("rank", "feature", "shap_value"),
            "support_panels.response_curve": ("x", "y"),
            "support_panels.support_segments": (
                "segment_id",
                "segment_label",
                "support_kind",
                "domain_start",
                "domain_end",
            ),
        },
        additional_constraints=(
            "group_count_must_equal_three",
            "group_ids_must_be_unique",
            "group_labels_must_be_unique",
            "baseline_value_must_be_finite",
            "group_prediction_value_must_equal_baseline_plus_contributions",
            "group_contribution_ranks_must_be_strictly_increasing",
            "group_contribution_values_must_be_finite_and_non_zero",
            "group_feature_orders_must_match",
            "support_panel_count_must_equal_two",
            "support_panel_ids_must_be_unique",
            "support_panel_labels_must_be_unique",
            "support_panel_features_must_be_unique",
            "support_panel_reference_labels_must_be_non_empty",
            "support_panel_reference_values_must_be_finite",
            "support_panel_response_curve_must_have_matching_x_y_lengths",
            "support_panel_response_curve_x_must_be_strictly_increasing",
            "support_panel_response_curve_values_must_be_finite",
            "support_panel_support_segments_must_be_non_empty",
            "support_panel_support_segment_ids_must_be_unique_within_panel",
            "support_panel_support_segment_labels_must_be_non_empty",
            "support_panel_support_segment_kinds_must_be_supported",
            "support_panel_support_segments_must_be_strictly_ordered_and_non_overlapping",
            "support_panel_support_segments_must_cover_curve_range",
            "support_panel_reference_values_must_fall_within_response_curve_range",
            "support_panel_features_must_be_subset_of_group_feature_order",
            "support_panel_feature_order_must_follow_group_feature_order",
        ),
    ),
    InputSchemaContract(
        input_schema_id="shap_signed_importance_local_support_domain_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="SHAP Signed Importance Local Support-Domain Panel",
        template_ids=_template_ids_for_input_schema("shap_signed_importance_local_support_domain_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "support_y_label",
            "support_legend_title",
            "importance_panel",
            "local_panel",
            "support_panels",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "importance_panel.bars": ("rank", "feature", "signed_importance_value"),
            "local_panel.contributions": ("feature", "shap_value"),
            "support_panels": (
                "panel_id",
                "panel_label",
                "title",
                "x_label",
                "feature",
                "reference_value",
                "reference_label",
                "response_curve",
                "support_segments",
            ),
        },
        nested_collection_required_fields={
            "support_panels.response_curve": ("x", "y"),
            "support_panels.support_segments": (
                "segment_id",
                "segment_label",
                "support_kind",
                "domain_start",
                "domain_end",
            ),
        },
        additional_constraints=(
            "importance_panel_requires_panel_id_panel_label_title_x_label_and_direction_labels",
            "importance_bars_must_be_non_empty",
            "importance_bar_ranks_must_be_strictly_increasing",
            "importance_bar_features_must_be_unique",
            "importance_bar_values_must_be_finite_non_zero_and_sorted_by_descending_absolute_magnitude",
            "local_panel_requires_panel_id_panel_label_title_case_label_x_label_baseline_and_prediction",
            "local_panel_values_must_be_finite",
            "local_panel_contributions_must_be_non_empty",
            "local_panel_contribution_features_must_be_unique",
            "local_panel_prediction_value_must_equal_baseline_plus_contributions",
            "support_panel_count_must_equal_two",
            "support_panel_ids_must_be_unique",
            "support_panel_labels_must_be_unique_and_distinct_from_importance_and_local_labels",
            "support_panel_features_must_be_unique",
            "support_panel_reference_labels_must_be_non_empty",
            "support_panel_reference_values_must_be_finite",
            "support_panel_response_curve_must_have_matching_x_y_lengths",
            "support_panel_response_curve_x_must_be_strictly_increasing",
            "support_panel_response_curve_values_must_be_finite",
            "support_panel_support_segments_must_be_non_empty",
            "support_panel_support_segment_ids_must_be_unique_within_panel",
            "support_panel_support_segment_labels_must_be_non_empty",
            "support_panel_support_segment_kinds_must_be_supported",
            "support_panel_support_segments_must_be_strictly_ordered_and_non_overlapping",
            "support_panel_support_segments_must_cover_curve_range",
            "support_panel_reference_values_must_fall_within_response_curve_range",
            "local_panel_features_must_be_subset_of_global_feature_order",
            "local_panel_feature_order_must_follow_global_feature_order",
            "support_panel_features_must_be_subset_of_global_feature_order",
            "support_panel_feature_order_must_follow_global_feature_order",
        ),
    ),
)
