from __future__ import annotations

from .core import InputSchemaContract, _template_ids_for_input_schema

_INPUT_SCHEMA_CONTRACTS_TIME_TO_EVENT: tuple[InputSchemaContract, ...] = (
    InputSchemaContract(
        input_schema_id="accepted_descriptive_display_data_v1",
        display_kind="evidence_figure",
        display_name="Accepted Descriptive Display Data",
        template_ids=_template_ids_for_input_schema("accepted_descriptive_display_data_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "panels"),
        display_optional_fields=("paper_role", "x_label", "y_label"),
        collection_required_fields={
            "panels": ("panel_id", "title", "x_label", "y_label", "marks"),
        },
        collection_optional_fields={
            "panels": ("annotation",),
        },
        nested_collection_required_fields={
            "panels.marks": ("label", "value"),
        },
        nested_collection_optional_fields={
            "panels.marks": ("group", "comparison_value", "color", "annotation"),
        },
        additional_constraints=(
            "descriptive_displays_must_be_non_empty",
            "descriptive_display_ids_must_be_unique",
            "descriptive_panels_must_be_non_empty",
            "descriptive_panel_ids_must_be_unique_within_display",
            "descriptive_marks_must_be_non_empty",
            "descriptive_mark_labels_must_be_unique_within_panel",
            "descriptive_mark_values_must_be_finite_or_null_when_not_applicable",
        ),
    ),
    InputSchemaContract(
        input_schema_id="binary_prediction_curve_inputs_v1",
        display_kind="evidence_figure",
        display_name="Binary Prediction Curves",
        template_ids=_template_ids_for_input_schema("binary_prediction_curve_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "y_label", "series"),
        display_optional_fields=("paper_role", "reference_line", "time_horizon_months"),
        collection_required_fields={"series": ("label", "x", "y")},
        collection_optional_fields={"series": ("annotation",), "reference_line": ("label",)},
        nested_collection_required_fields={"reference_line": ("x", "y")},
        additional_constraints=(
            "series_must_be_non_empty",
            "series_x_y_lengths_must_match",
            "series_values_must_be_finite",
            "reference_line_x_y_lengths_must_match_when_present",
            "time_dependent_roc_horizon_requires_positive_time_horizon_months_when_selected",
        ),
    ),
    InputSchemaContract(
        input_schema_id="risk_layering_monotonic_inputs_v1",
        display_kind="evidence_figure",
        display_name="Monotonic Risk Layering Bars",
        template_ids=_template_ids_for_input_schema("risk_layering_monotonic_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "y_label",
            "left_panel_title",
            "left_x_label",
            "left_bars",
            "right_panel_title",
            "right_x_label",
            "right_bars",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "left_bars": ("label", "cases", "events", "risk"),
            "right_bars": ("label", "cases", "events", "risk"),
        },
        additional_constraints=(
            "left_bars_must_be_non_empty",
            "right_bars_must_be_non_empty",
            "bar_cases_must_be_positive",
            "bar_events_must_not_exceed_cases",
            "bar_risk_must_be_finite_probability",
            "bar_risk_must_match_events_over_cases",
            "left_bars_risk_must_be_monotonic_non_decreasing",
            "right_bars_risk_must_be_monotonic_non_decreasing",
        ),
    ),
    InputSchemaContract(
        input_schema_id="time_dependent_roc_comparison_inputs_v1",
        display_kind="evidence_figure",
        display_name="Time-Dependent ROC Comparison Panel",
        template_ids=_template_ids_for_input_schema("time_dependent_roc_comparison_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "y_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "analysis_window_label", "series"),
        },
        collection_optional_fields={
            "panels": ("annotation", "time_horizon_months", "reference_line"),
        },
        nested_collection_required_fields={
            "panels.series": ("label", "x", "y"),
            "panels.reference_line": ("x", "y"),
        },
        nested_collection_optional_fields={
            "panels.reference_line": ("label",),
        },
        additional_constraints=(
            "time_dependent_roc_comparison_panels_must_be_non_empty",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_analysis_window_labels_must_be_non_empty",
            "panel_series_must_be_non_empty",
            "panel_series_labels_must_be_unique_within_panel",
            "panel_series_label_sets_must_match_across_panels",
            "panel_series_x_y_lengths_must_match",
            "panel_series_values_must_be_finite",
            "panel_reference_line_x_y_lengths_must_match_when_present",
            "panel_time_horizon_months_must_be_positive_when_present",
        ),
    ),
    InputSchemaContract(
        input_schema_id="time_to_event_landmark_performance_inputs_v1",
        display_kind="evidence_figure",
        display_name="Landmark Performance Summary Panel (Time-to-Event)",
        template_ids=_template_ids_for_input_schema("time_to_event_landmark_performance_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "discrimination_panel_title",
            "discrimination_x_label",
            "error_panel_title",
            "error_x_label",
            "calibration_panel_title",
            "calibration_x_label",
            "landmark_summaries",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "landmark_summaries": (
                "window_label",
                "analysis_window_label",
                "landmark_months",
                "prediction_months",
                "c_index",
                "brier_score",
                "calibration_slope",
            )
        },
        collection_optional_fields={"landmark_summaries": ("annotation",)},
        additional_constraints=(
            "landmark_summaries_must_be_non_empty",
            "window_labels_must_be_unique",
            "analysis_window_labels_must_be_unique",
            "landmark_months_must_be_positive",
            "prediction_months_must_be_positive",
            "prediction_months_must_exceed_landmark_months",
            "c_index_values_must_be_finite_probability",
            "brier_score_values_must_be_finite_probability",
            "calibration_slope_values_must_be_finite",
        ),
    ),
    InputSchemaContract(
        input_schema_id="time_to_event_multihorizon_calibration_inputs_v1",
        display_kind="evidence_figure",
        display_name="Multi-Horizon Grouped Calibration Panel (Time-to-Event)",
        template_ids=_template_ids_for_input_schema("time_to_event_multihorizon_calibration_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "time_horizon_months", "calibration_summary"),
        },
        nested_collection_required_fields={
            "panels.calibration_summary": ("group_label", "group_order", "n", "events", "predicted_risk", "observed_risk"),
        },
        additional_constraints=(
            "multihorizon_calibration_panels_must_be_non_empty",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_time_horizon_months_must_be_positive",
            "panel_time_horizon_months_must_be_strictly_increasing",
            "panel_calibration_summary_must_be_non_empty",
            "panel_group_order_must_be_strictly_increasing",
            "panel_group_risks_must_be_finite_probability",
            "panel_group_events_must_not_exceed_group_size",
        ),
    ),
    InputSchemaContract(
        input_schema_id="time_to_event_threshold_governance_inputs_v1",
        display_kind="evidence_figure",
        display_name="Time-to-Event Threshold Governance Panel",
        template_ids=_template_ids_for_input_schema("time_to_event_threshold_governance_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "threshold_panel_title",
            "calibration_panel_title",
            "calibration_x_label",
            "threshold_summaries",
            "risk_group_summaries",
        ),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "threshold_summaries": (
                "threshold_label",
                "threshold",
                "sensitivity",
                "specificity",
                "net_benefit",
            ),
            "risk_group_summaries": (
                "group_label",
                "group_order",
                "n",
                "events",
                "predicted_risk",
                "observed_risk",
            ),
        },
        additional_constraints=(
            "threshold_summaries_must_be_non_empty",
            "threshold_labels_must_be_unique",
            "threshold_values_must_be_strictly_increasing_probability",
            "threshold_metrics_must_be_finite",
            "risk_group_summaries_must_be_non_empty",
            "risk_group_order_must_be_strictly_increasing",
            "risk_group_risks_must_be_finite_probability",
            "risk_group_events_must_not_exceed_group_size",
        ),
    ),
    InputSchemaContract(
        input_schema_id="binary_calibration_decision_curve_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Binary Calibration and Decision Curve Panel",
        template_ids=_template_ids_for_input_schema("binary_calibration_decision_curve_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "calibration_x_label",
            "calibration_y_label",
            "decision_x_label",
            "decision_y_label",
            "calibration_axis_window",
            "calibration_series",
            "decision_series",
            "decision_reference_lines",
            "decision_focus_window",
        ),
        display_optional_fields=("paper_role", "calibration_reference_line"),
        collection_required_fields={
            "calibration_series": ("label", "x", "y"),
            "decision_series": ("label", "x", "y"),
            "decision_reference_lines": ("label", "x", "y"),
        },
        collection_optional_fields={"calibration_reference_line": ("label",)},
        nested_collection_required_fields={
            "calibration_reference_line": ("x", "y"),
            "calibration_axis_window": ("xmin", "xmax", "ymin", "ymax"),
            "decision_focus_window": ("xmin", "xmax"),
        },
        additional_constraints=(
            "calibration_series_must_be_non_empty",
            "calibration_series_x_y_lengths_must_match",
            "decision_series_must_be_non_empty",
            "decision_series_x_y_lengths_must_match",
            "decision_reference_lines_must_be_non_empty",
            "decision_reference_lines_x_y_lengths_must_match",
            "calibration_axis_window_must_be_strictly_increasing",
            "decision_focus_window_must_be_strictly_increasing",
        ),
    ),
    InputSchemaContract(
        input_schema_id="model_complexity_audit_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Model Complexity Audit Panel",
        template_ids=_template_ids_for_input_schema("model_complexity_audit_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "metric_panels", "audit_panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "metric_panels": ("panel_id", "panel_label", "title", "x_label", "rows"),
            "audit_panels": ("panel_id", "panel_label", "title", "x_label", "rows"),
        },
        collection_optional_fields={
            "metric_panels": ("reference_value",),
            "audit_panels": ("reference_value",),
        },
        nested_collection_required_fields={
            "metric_panels.rows": ("label", "value"),
            "audit_panels.rows": ("label", "value"),
        },
        additional_constraints=(
            "metric_panels_must_be_non_empty",
            "audit_panels_must_be_non_empty",
            "panel_row_values_must_be_finite",
        ),
    ),
    InputSchemaContract(
        input_schema_id="time_to_event_grouped_inputs_v1",
        display_kind="evidence_figure",
        display_name="Time-to-Event Grouped Curves",
        template_ids=_template_ids_for_input_schema("time_to_event_grouped_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "y_label"),
        display_optional_fields=("paper_role", "annotation", "groups", "panel_a_title", "panel_b_title", "event_count_y_label"),
        collection_required_fields={"groups": ("label", "times", "values")},
        collection_optional_fields={
            "risk_group_summaries": (
                "label",
                "sample_size",
                "events_5y",
                "mean_predicted_risk_5y",
                "observed_km_risk_5y",
            )
        },
        additional_constraints=(
            "kaplan_meier_grouped_and_cumulative_incidence_grouped_require_non_empty_groups",
            "group_times_values_lengths_must_match_when_groups_present",
            "group_values_must_be_finite_when_groups_present",
            "time_to_event_risk_group_summary_requires_non_empty_risk_group_summaries_when_selected",
            "risk_group_summary_events_must_not_exceed_sample_size",
        ),
    ),
    InputSchemaContract(
        input_schema_id="time_to_event_stratified_cumulative_incidence_inputs_v1",
        display_kind="evidence_figure",
        display_name="Time-to-Event Stratified Cumulative Incidence Panel",
        template_ids=_template_ids_for_input_schema("time_to_event_stratified_cumulative_incidence_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "y_label", "panels"),
        display_optional_fields=("paper_role",),
        collection_required_fields={
            "panels": ("panel_id", "panel_label", "title", "groups"),
        },
        collection_optional_fields={
            "panels": ("annotation",),
        },
        nested_collection_required_fields={
            "panels.groups": ("label", "times", "values"),
        },
        additional_constraints=(
            "stratified_cumulative_incidence_panels_must_be_non_empty",
            "panel_ids_must_be_unique",
            "panel_labels_must_be_unique",
            "panel_group_labels_must_be_unique_within_panel",
            "panel_group_times_values_lengths_must_match",
            "panel_group_times_must_be_strictly_increasing",
            "panel_group_values_must_be_finite_probability",
            "panel_group_values_must_be_monotonic_non_decreasing",
        ),
    ),
    InputSchemaContract(
        input_schema_id="time_to_event_discrimination_calibration_inputs_v1",
        display_kind="evidence_figure",
        display_name="Time-to-Event Discrimination and Calibration Panel",
        template_ids=_template_ids_for_input_schema("time_to_event_discrimination_calibration_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "panel_a_title",
            "panel_b_title",
            "discrimination_x_label",
            "calibration_x_label",
            "calibration_y_label",
            "discrimination_points",
            "calibration_summary",
        ),
        display_optional_fields=("paper_role", "calibration_callout"),
        collection_required_fields={
            "discrimination_points": ("label", "c_index"),
            "calibration_summary": (
                "group_label",
                "group_order",
                "n",
                "events_5y",
                "predicted_risk_5y",
                "observed_risk_5y",
            ),
        },
        collection_optional_fields={
            "discrimination_points": ("annotation",),
        },
        nested_collection_required_fields={"calibration_callout": ("group_label", "predicted_risk_5y", "observed_risk_5y")},
        nested_collection_optional_fields={"calibration_callout": ("events_5y", "n")},
        additional_constraints=(
            "discrimination_points_must_be_non_empty",
            "discrimination_points_must_be_finite_c_index",
            "calibration_summary_must_be_non_empty",
            "calibration_group_order_must_be_strictly_increasing",
            "calibration_summary_risks_must_be_finite_probability",
            "calibration_summary_events_must_not_exceed_group_size",
            "calibration_callout_must_reference_group_label_when_present",
            "calibration_callout_must_match_referenced_group_when_present",
        ),
    ),
    InputSchemaContract(
        input_schema_id="time_to_event_decision_curve_inputs_v1",
        display_kind="evidence_figure",
        display_name="Time-to-Event Decision Curves",
        template_ids=_template_ids_for_input_schema("time_to_event_decision_curve_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "panel_a_title",
            "panel_b_title",
            "x_label",
            "y_label",
            "treated_fraction_y_label",
            "series",
            "treated_fraction_series",
        ),
        display_optional_fields=("paper_role", "reference_line", "time_horizon_months"),
        collection_required_fields={
            "series": ("label", "x", "y"),
            "treated_fraction_series": ("label", "x", "y"),
        },
        collection_optional_fields={"series": ("annotation",), "reference_line": ("label",)},
        nested_collection_required_fields={"reference_line": ("x", "y")},
        additional_constraints=(
            "series_must_be_non_empty",
            "series_x_y_lengths_must_match",
            "series_values_must_be_finite",
            "reference_line_x_y_lengths_must_match_when_present",
            "treated_fraction_series_x_y_lengths_must_match",
            "treated_fraction_values_must_be_finite",
            "publication_style_profile_required_at_materialization",
            "display_override_contract_may_adjust_layout_without_changing_data",
            "time_horizon_months_must_be_positive_when_declared",
        ),
    ),
)
