from __future__ import annotations

from .core import InputSchemaContract, _template_ids_for_input_schema

_INPUT_SCHEMA_CONTRACTS_DATA_GEOMETRY: tuple[InputSchemaContract, ...] = (
    InputSchemaContract(
        input_schema_id="embedding_grouped_inputs_v1",
        display_kind="evidence_figure",
        display_name="Grouped Embedding Scatter",
        template_ids=_template_ids_for_input_schema("embedding_grouped_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=("display_id", "template_id", "title", "caption", "x_label", "y_label", "points"),
        display_optional_fields=("paper_role",),
        collection_required_fields={"points": ("x", "y", "group")},
        additional_constraints=(
            "points_must_be_non_empty",
            "point_coordinates_must_be_finite",
            "point_group_must_be_non_empty",
        ),
    ),
    InputSchemaContract(
        input_schema_id="celltype_signature_heatmap_inputs_v1",
        display_kind="evidence_figure",
        display_name="Cell-Type Embedding and Signature Heatmap",
        template_ids=_template_ids_for_input_schema("celltype_signature_heatmap_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "embedding_panel_title",
            "embedding_x_label",
            "embedding_y_label",
            "embedding_points",
            "heatmap_panel_title",
            "heatmap_x_label",
            "heatmap_y_label",
            "score_method",
            "row_order",
            "column_order",
            "cells",
        ),
        display_optional_fields=("paper_role", "embedding_annotation", "heatmap_annotation"),
        collection_required_fields={
            "embedding_points": ("x", "y", "group"),
            "row_order": ("label",),
            "column_order": ("label",),
            "cells": ("x", "y", "value"),
        },
        additional_constraints=(
            "embedding_points_must_be_non_empty",
            "embedding_point_coordinates_must_be_finite",
            "embedding_point_group_must_be_non_empty",
            "score_method_must_be_non_empty",
            "cells_must_be_non_empty",
            "cell_coordinates_must_be_non_empty",
            "cell_values_must_be_finite",
            "row_order_labels_must_be_unique",
            "column_order_labels_must_be_unique",
            "declared_row_labels_must_match_cell_rows",
            "declared_column_labels_must_match_cell_columns",
            "declared_column_labels_must_match_embedding_groups",
            "declared_heatmap_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="single_cell_atlas_overview_inputs_v1",
        display_kind="evidence_figure",
        display_name="Single-Cell Atlas Overview Panel",
        template_ids=_template_ids_for_input_schema("single_cell_atlas_overview_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "embedding_panel_title",
            "embedding_x_label",
            "embedding_y_label",
            "embedding_points",
            "composition_panel_title",
            "composition_x_label",
            "composition_y_label",
            "composition_groups",
            "heatmap_panel_title",
            "heatmap_x_label",
            "heatmap_y_label",
            "score_method",
            "row_order",
            "column_order",
            "cells",
        ),
        display_optional_fields=("paper_role", "embedding_annotation", "composition_annotation", "heatmap_annotation"),
        collection_required_fields={
            "embedding_points": ("x", "y", "state_label"),
            "composition_groups": ("group_label", "group_order", "state_proportions"),
            "row_order": ("label",),
            "column_order": ("label",),
            "cells": ("x", "y", "value"),
        },
        collection_optional_fields={"embedding_points": ("group_label",)},
        nested_collection_required_fields={
            "composition_groups.state_proportions": ("state_label", "proportion"),
        },
        additional_constraints=(
            "embedding_points_must_be_non_empty",
            "embedding_point_coordinates_must_be_finite",
            "embedding_point_state_label_must_be_non_empty",
            "composition_groups_must_be_non_empty",
            "composition_group_labels_must_be_unique",
            "composition_group_order_must_be_strictly_increasing",
            "composition_group_state_proportions_must_be_non_empty",
            "composition_group_state_labels_must_match_declared_columns",
            "composition_group_proportions_must_be_finite_probability",
            "composition_group_proportions_must_sum_to_one",
            "score_method_must_be_non_empty",
            "cells_must_be_non_empty",
            "cell_coordinates_must_be_non_empty",
            "cell_values_must_be_finite",
            "row_order_labels_must_be_unique",
            "column_order_labels_must_be_unique",
            "declared_row_labels_must_match_cell_rows",
            "declared_column_labels_must_match_cell_columns",
            "declared_column_labels_must_match_embedding_states",
            "declared_heatmap_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="atlas_spatial_bridge_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Atlas-Spatial Bridge Panel",
        template_ids=_template_ids_for_input_schema("atlas_spatial_bridge_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "atlas_panel_title",
            "atlas_x_label",
            "atlas_y_label",
            "atlas_points",
            "spatial_panel_title",
            "spatial_x_label",
            "spatial_y_label",
            "spatial_points",
            "composition_panel_title",
            "composition_x_label",
            "composition_y_label",
            "composition_groups",
            "heatmap_panel_title",
            "heatmap_x_label",
            "heatmap_y_label",
            "score_method",
            "row_order",
            "column_order",
            "cells",
        ),
        display_optional_fields=(
            "paper_role",
            "atlas_annotation",
            "spatial_annotation",
            "composition_annotation",
            "heatmap_annotation",
        ),
        collection_required_fields={
            "atlas_points": ("x", "y", "state_label"),
            "spatial_points": ("x", "y", "state_label"),
            "composition_groups": ("group_label", "group_order", "state_proportions"),
            "row_order": ("label",),
            "column_order": ("label",),
            "cells": ("x", "y", "value"),
        },
        collection_optional_fields={
            "atlas_points": ("group_label",),
            "spatial_points": ("region_label",),
        },
        nested_collection_required_fields={"composition_groups.state_proportions": ("state_label", "proportion")},
        additional_constraints=(
            "atlas_points_must_be_non_empty",
            "atlas_point_coordinates_must_be_finite",
            "atlas_point_state_label_must_be_non_empty",
            "spatial_points_must_be_non_empty",
            "spatial_point_coordinates_must_be_finite",
            "spatial_point_state_label_must_be_non_empty",
            "composition_groups_must_be_non_empty",
            "composition_group_labels_must_be_unique",
            "composition_group_order_must_be_strictly_increasing",
            "composition_group_state_proportions_must_be_non_empty",
            "composition_group_state_labels_must_match_declared_columns",
            "composition_group_proportions_must_be_finite_probability",
            "composition_group_proportions_must_sum_to_one",
            "score_method_must_be_non_empty",
            "cells_must_be_non_empty",
            "cell_coordinates_must_be_non_empty",
            "cell_values_must_be_finite",
            "row_order_labels_must_be_unique",
            "column_order_labels_must_be_unique",
            "declared_row_labels_must_match_cell_rows",
            "declared_column_labels_must_match_cell_columns",
            "declared_column_labels_must_match_atlas_states",
            "declared_column_labels_must_match_spatial_states",
            "declared_heatmap_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="spatial_niche_map_inputs_v1",
        display_kind="evidence_figure",
        display_name="Spatial Niche Map Panel",
        template_ids=_template_ids_for_input_schema("spatial_niche_map_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "spatial_panel_title",
            "spatial_x_label",
            "spatial_y_label",
            "spatial_points",
            "composition_panel_title",
            "composition_x_label",
            "composition_y_label",
            "composition_groups",
            "heatmap_panel_title",
            "heatmap_x_label",
            "heatmap_y_label",
            "score_method",
            "row_order",
            "column_order",
            "cells",
        ),
        display_optional_fields=("paper_role", "spatial_annotation", "composition_annotation", "heatmap_annotation"),
        collection_required_fields={
            "spatial_points": ("x", "y", "niche_label"),
            "composition_groups": ("group_label", "group_order", "niche_proportions"),
            "row_order": ("label",),
            "column_order": ("label",),
            "cells": ("x", "y", "value"),
        },
        collection_optional_fields={"spatial_points": ("region_label",)},
        nested_collection_required_fields={
            "composition_groups.niche_proportions": ("niche_label", "proportion"),
        },
        additional_constraints=(
            "spatial_points_must_be_non_empty",
            "spatial_point_coordinates_must_be_finite",
            "spatial_point_niche_label_must_be_non_empty",
            "composition_groups_must_be_non_empty",
            "composition_group_labels_must_be_unique",
            "composition_group_order_must_be_strictly_increasing",
            "composition_group_niche_proportions_must_be_non_empty",
            "composition_group_niche_labels_must_match_declared_columns",
            "composition_group_proportions_must_be_finite_probability",
            "composition_group_proportions_must_sum_to_one",
            "score_method_must_be_non_empty",
            "cells_must_be_non_empty",
            "cell_coordinates_must_be_non_empty",
            "cell_values_must_be_finite",
            "row_order_labels_must_be_unique",
            "column_order_labels_must_be_unique",
            "declared_row_labels_must_match_cell_rows",
            "declared_column_labels_must_match_cell_columns",
            "declared_column_labels_must_match_spatial_niches",
            "declared_heatmap_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="trajectory_progression_inputs_v1",
        display_kind="evidence_figure",
        display_name="Trajectory Progression Panel",
        template_ids=_template_ids_for_input_schema("trajectory_progression_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "trajectory_panel_title",
            "trajectory_x_label",
            "trajectory_y_label",
            "trajectory_points",
            "composition_panel_title",
            "composition_x_label",
            "composition_y_label",
            "branch_order",
            "progression_bins",
            "heatmap_panel_title",
            "heatmap_x_label",
            "heatmap_y_label",
            "score_method",
            "row_order",
            "column_order",
            "cells",
        ),
        display_optional_fields=("paper_role", "trajectory_annotation", "composition_annotation", "heatmap_annotation"),
        collection_required_fields={
            "trajectory_points": ("x", "y", "branch_label", "state_label", "pseudotime"),
            "branch_order": ("label",),
            "progression_bins": ("bin_label", "bin_order", "pseudotime_start", "pseudotime_end", "branch_weights"),
            "row_order": ("label",),
            "column_order": ("label",),
            "cells": ("x", "y", "value"),
        },
        nested_collection_required_fields={
            "progression_bins.branch_weights": ("branch_label", "proportion"),
        },
        additional_constraints=(
            "trajectory_points_must_be_non_empty",
            "trajectory_point_coordinates_must_be_finite",
            "trajectory_point_branch_label_must_be_non_empty",
            "trajectory_point_state_label_must_be_non_empty",
            "trajectory_point_pseudotime_must_be_finite_probability",
            "branch_order_labels_must_be_unique",
            "branch_order_labels_must_match_trajectory_branches",
            "progression_bins_must_be_non_empty",
            "progression_bin_labels_must_be_unique",
            "progression_bin_order_must_be_strictly_increasing",
            "progression_bin_intervals_must_be_strictly_increasing",
            "progression_bin_branch_weights_must_be_non_empty",
            "progression_bin_branch_labels_must_match_declared_branch_order",
            "progression_bin_branch_weights_must_be_finite_probability",
            "progression_bin_branch_weights_must_sum_to_one",
            "score_method_must_be_non_empty",
            "cells_must_be_non_empty",
            "cell_coordinates_must_be_non_empty",
            "cell_values_must_be_finite",
            "row_order_labels_must_be_unique",
            "column_order_labels_must_be_unique",
            "declared_row_labels_must_match_cell_rows",
            "declared_column_labels_must_match_cell_columns",
            "declared_column_labels_must_match_progression_bins",
            "declared_heatmap_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="atlas_spatial_trajectory_storyboard_inputs_v1",
        display_kind="evidence_figure",
        display_name="Atlas-Spatial Trajectory Storyboard Panel",
        template_ids=_template_ids_for_input_schema("atlas_spatial_trajectory_storyboard_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "atlas_panel_title",
            "atlas_x_label",
            "atlas_y_label",
            "atlas_points",
            "spatial_panel_title",
            "spatial_x_label",
            "spatial_y_label",
            "spatial_points",
            "trajectory_panel_title",
            "trajectory_x_label",
            "trajectory_y_label",
            "trajectory_points",
            "composition_panel_title",
            "composition_x_label",
            "composition_y_label",
            "composition_groups",
            "heatmap_panel_title",
            "heatmap_x_label",
            "heatmap_y_label",
            "score_method",
            "state_order",
            "branch_order",
            "progression_bins",
            "row_order",
            "column_order",
            "cells",
        ),
        display_optional_fields=(
            "paper_role",
            "atlas_annotation",
            "spatial_annotation",
            "trajectory_annotation",
            "composition_annotation",
            "heatmap_annotation",
        ),
        collection_required_fields={
            "atlas_points": ("x", "y", "state_label"),
            "spatial_points": ("x", "y", "state_label"),
            "trajectory_points": ("x", "y", "branch_label", "state_label", "pseudotime"),
            "composition_groups": ("group_label", "group_order", "state_proportions"),
            "state_order": ("label",),
            "branch_order": ("label",),
            "progression_bins": ("bin_label", "bin_order", "pseudotime_start", "pseudotime_end", "branch_weights"),
            "row_order": ("label",),
            "column_order": ("label",),
            "cells": ("x", "y", "value"),
        },
        collection_optional_fields={
            "spatial_points": ("region_label",),
        },
        nested_collection_required_fields={
            "composition_groups.state_proportions": ("state_label", "proportion"),
            "progression_bins.branch_weights": ("branch_label", "proportion"),
        },
        additional_constraints=(
            "atlas_points_must_be_non_empty",
            "atlas_point_coordinates_must_be_finite",
            "atlas_point_state_label_must_be_non_empty",
            "spatial_points_must_be_non_empty",
            "spatial_point_coordinates_must_be_finite",
            "spatial_point_state_label_must_be_non_empty",
            "trajectory_points_must_be_non_empty",
            "trajectory_point_coordinates_must_be_finite",
            "trajectory_point_state_label_must_be_non_empty",
            "trajectory_point_pseudotime_must_be_probability",
            "trajectory_point_branch_label_must_be_non_empty",
            "composition_groups_must_be_non_empty",
            "composition_group_labels_must_be_unique",
            "composition_group_order_must_be_strictly_increasing",
            "composition_group_state_proportions_must_be_non_empty",
            "composition_group_state_labels_must_match_declared_states",
            "composition_group_proportions_must_be_finite_probability",
            "composition_group_proportions_must_sum_to_one",
            "state_order_labels_must_be_unique",
            "branch_order_labels_must_be_unique",
            "progression_bins_must_be_non_empty",
            "progression_bin_labels_must_be_unique",
            "progression_bin_order_must_be_strictly_increasing",
            "progression_bin_intervals_must_be_strictly_increasing",
            "progression_bin_branch_weights_must_be_non_empty",
            "progression_bin_branch_labels_must_match_declared_branches",
            "progression_bin_branch_weights_must_sum_to_one",
            "score_method_must_be_non_empty",
            "cells_must_be_non_empty",
            "cell_coordinates_must_be_non_empty",
            "cell_values_must_be_finite",
            "row_order_labels_must_be_unique",
            "column_order_labels_must_be_unique",
            "declared_state_labels_must_match_atlas_states",
            "declared_state_labels_must_match_spatial_states",
            "declared_state_labels_must_match_trajectory_states",
            "declared_branch_labels_must_match_trajectory_branches",
            "declared_row_labels_must_match_cell_rows",
            "declared_column_labels_must_match_cell_columns",
            "declared_column_labels_must_match_progression_bins",
            "declared_heatmap_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="atlas_spatial_trajectory_density_coverage_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Atlas-Spatial Trajectory Density Coverage Panel",
        template_ids=_template_ids_for_input_schema("atlas_spatial_trajectory_density_coverage_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "atlas_panel_title",
            "atlas_x_label",
            "atlas_y_label",
            "atlas_points",
            "spatial_panel_title",
            "spatial_x_label",
            "spatial_y_label",
            "spatial_points",
            "trajectory_panel_title",
            "trajectory_x_label",
            "trajectory_y_label",
            "trajectory_points",
            "support_panel_title",
            "support_x_label",
            "support_y_label",
            "support_scale_label",
            "state_order",
            "context_order",
            "support_cells",
        ),
        display_optional_fields=(
            "paper_role",
            "atlas_annotation",
            "spatial_annotation",
            "trajectory_annotation",
            "support_annotation",
        ),
        collection_required_fields={
            "atlas_points": ("x", "y", "state_label"),
            "spatial_points": ("x", "y", "state_label", "region_label"),
            "trajectory_points": ("x", "y", "branch_label", "state_label", "pseudotime"),
            "state_order": ("label",),
            "context_order": ("label", "context_kind"),
            "support_cells": ("x", "y", "value"),
        },
        additional_constraints=(
            "atlas_points_must_be_non_empty",
            "atlas_point_coordinates_must_be_finite",
            "atlas_point_state_label_must_be_non_empty",
            "spatial_points_must_be_non_empty",
            "spatial_point_coordinates_must_be_finite",
            "spatial_point_state_label_must_be_non_empty",
            "spatial_point_region_label_must_be_non_empty",
            "trajectory_points_must_be_non_empty",
            "trajectory_point_coordinates_must_be_finite",
            "trajectory_point_branch_label_must_be_non_empty",
            "trajectory_point_state_label_must_be_non_empty",
            "trajectory_point_pseudotime_must_be_finite_probability",
            "support_scale_label_must_be_non_empty",
            "state_order_labels_must_be_unique",
            "context_order_labels_must_be_unique",
            "context_order_kinds_must_be_supported_and_unique",
            "context_order_kinds_must_cover_all_required_contexts",
            "support_cells_must_be_non_empty",
            "support_cell_coordinates_must_be_non_empty",
            "support_cell_values_must_be_finite_probability",
            "declared_state_labels_must_match_atlas_states",
            "declared_state_labels_must_match_spatial_states",
            "declared_state_labels_must_match_trajectory_states",
            "declared_state_labels_must_match_support_rows",
            "declared_context_labels_must_match_support_columns",
            "declared_support_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="atlas_spatial_trajectory_context_support_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Atlas-Spatial Trajectory Context Support Panel",
        template_ids=_template_ids_for_input_schema("atlas_spatial_trajectory_context_support_panel_inputs_v1"),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "atlas_panel_title",
            "atlas_x_label",
            "atlas_y_label",
            "atlas_points",
            "spatial_panel_title",
            "spatial_x_label",
            "spatial_y_label",
            "spatial_points",
            "trajectory_panel_title",
            "trajectory_x_label",
            "trajectory_y_label",
            "trajectory_points",
            "composition_panel_title",
            "composition_x_label",
            "composition_y_label",
            "composition_groups",
            "heatmap_panel_title",
            "heatmap_x_label",
            "heatmap_y_label",
            "score_method",
            "state_order",
            "branch_order",
            "progression_bins",
            "row_order",
            "column_order",
            "cells",
            "support_panel_title",
            "support_x_label",
            "support_y_label",
            "support_scale_label",
            "context_order",
            "support_cells",
        ),
        display_optional_fields=(
            "paper_role",
            "atlas_annotation",
            "spatial_annotation",
            "trajectory_annotation",
            "composition_annotation",
            "heatmap_annotation",
            "support_annotation",
        ),
        collection_required_fields={
            "atlas_points": ("x", "y", "state_label"),
            "spatial_points": ("x", "y", "state_label", "region_label"),
            "trajectory_points": ("x", "y", "branch_label", "state_label", "pseudotime"),
            "composition_groups": ("group_label", "group_order", "state_proportions"),
            "state_order": ("label",),
            "branch_order": ("label",),
            "progression_bins": ("bin_label", "bin_order", "pseudotime_start", "pseudotime_end", "branch_weights"),
            "row_order": ("label",),
            "column_order": ("label",),
            "cells": ("x", "y", "value"),
            "context_order": ("label", "context_kind"),
            "support_cells": ("x", "y", "value"),
        },
        nested_collection_required_fields={
            "composition_groups.state_proportions": ("state_label", "proportion"),
            "progression_bins.branch_weights": ("branch_label", "proportion"),
        },
        additional_constraints=(
            "atlas_points_must_be_non_empty",
            "atlas_point_coordinates_must_be_finite",
            "atlas_point_state_label_must_be_non_empty",
            "spatial_points_must_be_non_empty",
            "spatial_point_coordinates_must_be_finite",
            "spatial_point_state_label_must_be_non_empty",
            "spatial_point_region_label_must_be_non_empty",
            "trajectory_points_must_be_non_empty",
            "trajectory_point_coordinates_must_be_finite",
            "trajectory_point_state_label_must_be_non_empty",
            "trajectory_point_pseudotime_must_be_probability",
            "trajectory_point_branch_label_must_be_non_empty",
            "composition_groups_must_be_non_empty",
            "composition_group_labels_must_be_unique",
            "composition_group_order_must_be_strictly_increasing",
            "composition_group_state_proportions_must_be_non_empty",
            "composition_group_state_labels_must_match_declared_states",
            "composition_group_proportions_must_be_finite_probability",
            "composition_group_proportions_must_sum_to_one",
            "state_order_labels_must_be_unique",
            "branch_order_labels_must_be_unique",
            "progression_bins_must_be_non_empty",
            "progression_bin_labels_must_be_unique",
            "progression_bin_order_must_be_strictly_increasing",
            "progression_bin_intervals_must_be_strictly_increasing",
            "progression_bin_branch_weights_must_be_non_empty",
            "progression_bin_branch_labels_must_match_declared_branches",
            "progression_bin_branch_weights_must_sum_to_one",
            "score_method_must_be_non_empty",
            "cells_must_be_non_empty",
            "cell_coordinates_must_be_non_empty",
            "cell_values_must_be_finite",
            "row_order_labels_must_be_unique",
            "column_order_labels_must_be_unique",
            "declared_row_labels_must_match_cell_rows",
            "declared_column_labels_must_match_cell_columns",
            "declared_column_labels_must_match_progression_bins",
            "declared_heatmap_grid_must_be_complete_and_unique",
            "support_scale_label_must_be_non_empty",
            "context_order_labels_must_be_unique",
            "context_order_kinds_must_be_supported_and_unique",
            "context_order_kinds_must_cover_all_required_contexts",
            "support_cells_must_be_non_empty",
            "support_cell_coordinates_must_be_non_empty",
            "support_cell_values_must_be_finite_probability",
            "declared_state_labels_must_match_atlas_states",
            "declared_state_labels_must_match_spatial_states",
            "declared_state_labels_must_match_trajectory_states",
            "declared_state_labels_must_match_support_rows",
            "declared_context_labels_must_match_support_columns",
            "declared_support_grid_must_be_complete_and_unique",
        ),
    ),
    InputSchemaContract(
        input_schema_id="atlas_spatial_trajectory_multimanifold_context_support_panel_inputs_v1",
        display_kind="evidence_figure",
        display_name="Atlas-Spatial Trajectory Multimanifold Context Support Panel",
        template_ids=_template_ids_for_input_schema(
            "atlas_spatial_trajectory_multimanifold_context_support_panel_inputs_v1"
        ),
        required_top_level_fields=("schema_version", "input_schema_id", "displays"),
        display_required_fields=(
            "display_id",
            "template_id",
            "title",
            "caption",
            "atlas_manifold_panels",
            "spatial_panel_title",
            "spatial_x_label",
            "spatial_y_label",
            "spatial_points",
            "trajectory_panel_title",
            "trajectory_x_label",
            "trajectory_y_label",
            "trajectory_points",
            "composition_panel_title",
            "composition_x_label",
            "composition_y_label",
            "composition_groups",
            "heatmap_panel_title",
            "heatmap_x_label",
            "heatmap_y_label",
            "score_method",
            "state_order",
            "branch_order",
            "progression_bins",
            "row_order",
            "column_order",
            "cells",
            "support_panel_title",
            "support_x_label",
            "support_y_label",
            "support_scale_label",
            "context_order",
            "support_cells",
        ),
        display_optional_fields=(
            "paper_role",
            "spatial_annotation",
            "trajectory_annotation",
            "composition_annotation",
            "heatmap_annotation",
            "support_annotation",
        ),
        collection_required_fields={
            "atlas_manifold_panels": ("panel_id", "panel_label", "panel_title", "manifold_method", "x_label", "y_label", "points"),
            "spatial_points": ("x", "y", "state_label", "region_label"),
            "trajectory_points": ("x", "y", "branch_label", "state_label", "pseudotime"),
            "composition_groups": ("group_label", "group_order", "state_proportions"),
            "state_order": ("label",),
            "branch_order": ("label",),
            "progression_bins": ("bin_label", "bin_order", "pseudotime_start", "pseudotime_end", "branch_weights"),
            "row_order": ("label",),
            "column_order": ("label",),
            "cells": ("x", "y", "value"),
            "context_order": ("label", "context_kind"),
            "support_cells": ("x", "y", "value"),
        },
        nested_collection_required_fields={
            "atlas_manifold_panels.points": ("x", "y", "state_label"),
            "composition_groups.state_proportions": ("state_label", "proportion"),
            "progression_bins.branch_weights": ("branch_label", "proportion"),
        },
        additional_constraints=(
            "atlas_manifold_panels_must_contain_exactly_two_panels",
            "atlas_manifold_panel_ids_must_be_unique",
            "atlas_manifold_panel_labels_must_be_unique",
            "atlas_manifold_methods_must_be_supported_and_unique",
            "atlas_manifold_panel_titles_must_be_non_empty",
            "atlas_manifold_axis_labels_must_be_non_empty",
            "atlas_manifold_points_must_be_non_empty",
            "atlas_manifold_point_coordinates_must_be_finite",
            "atlas_manifold_point_state_label_must_be_non_empty",
            "spatial_points_must_be_non_empty",
            "spatial_point_coordinates_must_be_finite",
            "spatial_point_state_label_must_be_non_empty",
            "spatial_point_region_label_must_be_non_empty",
            "trajectory_points_must_be_non_empty",
            "trajectory_point_coordinates_must_be_finite",
            "trajectory_point_state_label_must_be_non_empty",
            "trajectory_point_pseudotime_must_be_probability",
            "trajectory_point_branch_label_must_be_non_empty",
            "composition_groups_must_be_non_empty",
            "composition_group_labels_must_be_unique",
            "composition_group_order_must_be_strictly_increasing",
            "composition_group_state_proportions_must_be_non_empty",
            "composition_group_state_labels_must_match_declared_states",
            "composition_group_proportions_must_be_finite_probability",
            "composition_group_proportions_must_sum_to_one",
            "branch_order_labels_must_be_unique",
            "progression_bins_must_be_non_empty",
            "progression_bin_labels_must_be_unique",
            "progression_bin_order_must_be_strictly_increasing",
            "progression_bin_intervals_must_be_strictly_increasing",
            "progression_bin_branch_weights_must_be_non_empty",
            "progression_bin_branch_labels_must_match_declared_branches",
            "progression_bin_branch_weights_must_be_finite_probability",
            "progression_bin_branch_weights_must_sum_to_one",
            "row_order_labels_must_be_unique",
            "column_order_labels_must_be_unique",
            "matrix_cells_must_be_non_empty",
            "matrix_cell_coordinates_must_be_non_empty",
            "matrix_cell_values_must_be_finite",
            "declared_row_labels_must_match_matrix_rows",
            "declared_column_labels_must_match_matrix_columns",
            "declared_matrix_grid_must_be_complete_and_unique",
            "state_order_labels_must_be_unique",
            "context_order_labels_must_be_unique",
            "context_order_kinds_must_be_supported_and_unique",
            "context_order_kinds_must_cover_all_required_contexts",
            "support_cells_must_be_non_empty",
            "support_cell_coordinates_must_be_non_empty",
            "support_cell_values_must_be_finite_probability",
            "declared_state_labels_must_match_all_atlas_manifold_states",
            "declared_state_labels_must_match_spatial_states",
            "declared_state_labels_must_match_trajectory_states",
            "declared_state_labels_must_match_support_rows",
            "declared_context_labels_must_match_support_columns",
            "declared_support_grid_must_be_complete_and_unique",
            "declared_column_labels_must_match_progression_bins",
        ),
    ),
)
