from __future__ import annotations

from .contracts_data_geometry import _INPUT_SCHEMA_CONTRACTS_DATA_GEOMETRY
from .contracts_effects import _INPUT_SCHEMA_CONTRACTS_EFFECTS
from .contracts_explanations import _INPUT_SCHEMA_CONTRACTS_EXPLANATIONS
from .contracts_general_publication import _INPUT_SCHEMA_CONTRACTS_GENERAL_PUBLICATION
from .contracts_omics import _INPUT_SCHEMA_CONTRACTS_OMICS
from .contracts_time_to_event import _INPUT_SCHEMA_CONTRACTS_TIME_TO_EVENT

INPUT_SCHEMA_CONTRACT_FAMILIES = (
    _INPUT_SCHEMA_CONTRACTS_TIME_TO_EVENT,
    _INPUT_SCHEMA_CONTRACTS_DATA_GEOMETRY,
    _INPUT_SCHEMA_CONTRACTS_OMICS,
    _INPUT_SCHEMA_CONTRACTS_EFFECTS,
    _INPUT_SCHEMA_CONTRACTS_EXPLANATIONS,
    _INPUT_SCHEMA_CONTRACTS_GENERAL_PUBLICATION,
)
