from __future__ import annotations

import filecmp
import shutil

from .shared_base import Any, Path, dump_json, load_json, resolve_relpath, utc_now


_BODY_AUTHORITY_CURRENT_BODY_PAPER_REL = (
    "artifacts/stage_outputs/_body_authority/paper_authority_cutover/current_body/paper"
)

_DELIVERY_REQUIRED_SOURCE_RELS = (
    "evidence_ledger.json",
    "review/review_ledger.json",
)


def _current_body_paper_root(*, paper_root: Path) -> Path:
    resolved = paper_root.resolve()
    current_body_parts = Path(_BODY_AUTHORITY_CURRENT_BODY_PAPER_REL).parts
    if tuple(resolved.parts[-len(current_body_parts) :]) == current_body_parts:
        return resolved
    return resolved.parent / _BODY_AUTHORITY_CURRENT_BODY_PAPER_REL


def _copy_if_source_changed(
    *,
    source_root: Path,
    paper_root: Path,
    rel_path: str,
) -> Path | None:
    source_path = source_root / rel_path
    if not source_path.exists():
        return None
    target_path = paper_root / rel_path
    if target_path.exists():
        if filecmp.cmp(source_path, target_path, shallow=False):
            return None
        try:
            if target_path.stat().st_mtime_ns > source_path.stat().st_mtime_ns:
                return None
        except OSError:
            pass
    target_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_path, target_path)
    return target_path


def _relpath_from_paper(path: Path, *, paper_root: Path) -> str:
    return f"paper/{path.resolve().relative_to(paper_root.resolve()).as_posix()}"


def _first_existing_current_body_compile_report(*, source_root: Path) -> Path | None:
    for rel_path in ("build/compile_report.json", "compile_report.json"):
        candidate = source_root / rel_path
        if candidate.exists():
            return candidate
    return None


def _compile_report_has_current_source_locator(payload: dict[str, Any]) -> bool:
    return any(
        isinstance(payload.get(key), str) and str(payload.get(key)).strip()
        for key in ("source_markdown_path", "source_markdown", "entry_path")
    )


def _source_path_values(payload: dict[str, Any]) -> list[str]:
    values: list[str] = []
    for key in ("source_markdown_path", "source_markdown", "entry_path", "pdf_path", "output_pdf"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            values.append(value.strip())
    return values


def _hydrate_source_paths_from_compile_report(
    *,
    source_root: Path,
    paper_root: Path,
    compile_report: dict[str, Any],
) -> list[Path]:
    hydrated: list[Path] = []
    for value in _source_path_values(compile_report):
        if not value.startswith("paper/"):
            continue
        rel_path = value.removeprefix("paper/")
        copied_path = _copy_if_source_changed(
            source_root=source_root,
            paper_root=paper_root,
            rel_path=rel_path,
        )
        if copied_path is not None:
            hydrated.append(copied_path)
    return hydrated


def _hydrate_delivery_required_sources(
    *,
    source_root: Path,
    paper_root: Path,
) -> list[Path]:
    hydrated: list[Path] = []
    for rel_path in _DELIVERY_REQUIRED_SOURCE_RELS:
        copied_path = _copy_if_source_changed(
            source_root=source_root,
            paper_root=paper_root,
            rel_path=rel_path,
        )
        if copied_path is not None:
            hydrated.append(copied_path)
    return hydrated


def _build_compile_report_from_current_draft(*, paper_root: Path) -> dict[str, Any] | None:
    draft_path = paper_root / "draft.md"
    if not draft_path.exists():
        return None
    return {
        "schema_version": 1,
        "status": "current_draft_compile_source_hydrated",
        "created_at": utc_now(),
        "source_markdown_path": "paper/draft.md",
        "source_markdown_hydration": {
            "status": "current_paper_root_draft_used",
            "source": "paper/draft.md",
        },
        "output_pdf": "paper/paper.pdf",
        "notes": [
            "Generated by submission-minimal source hydration so package export rebuilds PDF from the current paper draft."
        ],
    }


def _source_markdown_values(payload: dict[str, Any]) -> list[str]:
    values: list[str] = []
    for key in ("source_markdown_path", "source_markdown", "entry_path"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            values.append(value.strip())
    return values


def _source_points_to_current_draft(payload: dict[str, Any]) -> bool:
    return any(
        value in {"draft.md", "paper/draft.md"} or value.endswith("/paper/draft.md")
        for value in _source_markdown_values(payload)
    )


def _compile_report_needs_current_draft_refresh(
    *,
    paper_root: Path,
    compile_report_path: Path,
    bundle_manifest: dict[str, Any],
) -> bool:
    draft_path = paper_root / "draft.md"
    if not draft_path.exists():
        return False
    if not compile_report_path.exists():
        return True
    try:
        compile_report = load_json(compile_report_path)
    except (OSError, ValueError):
        compile_report = {}
    try:
        draft_mtime = draft_path.stat().st_mtime
        compile_report_mtime = compile_report_path.stat().st_mtime
    except OSError:
        return True
    explicit_draft_path = bundle_manifest.get("draft_path")
    if (
        _compile_report_has_current_source_locator(compile_report)
        and not _source_points_to_current_draft(compile_report)
        and isinstance(explicit_draft_path, str)
        and explicit_draft_path.strip()
    ):
        return False
    if _source_points_to_current_draft(compile_report) and compile_report_mtime >= draft_mtime:
        return False
    return draft_mtime > compile_report_mtime


def hydrate_submission_package_sources_from_current_body(
    *,
    paper_root: Path,
    bundle_manifest: dict[str, Any],
) -> dict[str, Any]:
    resolved_paper_root = Path(paper_root).expanduser().resolve()
    workspace_root = resolved_paper_root.parent
    source_root = _current_body_paper_root(paper_root=resolved_paper_root)
    target_compile_report_path = resolved_paper_root / "build" / "compile_report.json"
    hydrated_files: list[Path] = []
    source_compile_report_path: Path | None = None
    source_compile_report_status = "not_used"
    target_compile_report_existed = target_compile_report_path.exists()

    if source_root.exists():
        hydrated_files.extend(
            _hydrate_delivery_required_sources(
                source_root=source_root,
                paper_root=resolved_paper_root,
            )
        )
        source_compile_report_path = _first_existing_current_body_compile_report(source_root=source_root)
        if source_compile_report_path is not None:
            source_compile_report = load_json(source_compile_report_path)
            if _compile_report_has_current_source_locator(source_compile_report):
                source_compile_report_status = "hydrated_from_current_body"
                rel_path = source_compile_report_path.relative_to(source_root).as_posix()
                copied_path = _copy_if_source_changed(
                    source_root=source_root,
                    paper_root=resolved_paper_root,
                    rel_path=rel_path,
                )
                if copied_path is not None:
                    hydrated_files.append(copied_path)
                if rel_path != "build/compile_report.json":
                    target_compile_report_path.parent.mkdir(parents=True, exist_ok=True)
                    dump_json(target_compile_report_path, source_compile_report)
                    hydrated_files.append(target_compile_report_path)
                hydrated_files.extend(
                    _hydrate_source_paths_from_compile_report(
                        source_root=source_root,
                        paper_root=resolved_paper_root,
                        compile_report=source_compile_report,
                    )
                )
            else:
                source_compile_report_status = "ignored_no_current_source_locator"

    if _compile_report_needs_current_draft_refresh(
        paper_root=resolved_paper_root,
        compile_report_path=target_compile_report_path,
        bundle_manifest=bundle_manifest,
    ):
        generated_compile_report = _build_compile_report_from_current_draft(paper_root=resolved_paper_root)
        if generated_compile_report is not None:
            dump_json(target_compile_report_path, generated_compile_report)
            hydrated_files.append(target_compile_report_path)
            source_compile_report_status = (
                "refreshed_from_current_draft"
                if target_compile_report_existed or source_compile_report_status != "not_used"
                else "generated_from_current_draft"
            )

    bundle_inputs = bundle_manifest.get("bundle_inputs")
    compile_report_ref = None
    if isinstance(bundle_inputs, dict):
        compile_report_ref = bundle_inputs.get("compile_report_path")
    if compile_report_ref is None:
        compile_report_ref = bundle_manifest.get("compile_report_path")
    resolved_compile_report = (
        resolve_relpath(workspace_root, str(compile_report_ref))
        if isinstance(compile_report_ref, str) and compile_report_ref.strip()
        else target_compile_report_path
    )
    return {
        "status": "hydrated" if hydrated_files else "current",
        "source_root": str(source_root),
        "source_compile_report_path": str(source_compile_report_path) if source_compile_report_path else None,
        "source_compile_report_status": source_compile_report_status,
        "compile_report_path": str(resolved_compile_report.resolve()),
        "hydrated_files": [
            _relpath_from_paper(path, paper_root=resolved_paper_root)
            for path in sorted(set(hydrated_files))
        ],
    }


__all__ = [
    "hydrate_submission_package_sources_from_current_body",
]
