from __future__ import annotations

from typing import Any


CORE_R_DISPLAY_PAYLOADS: dict[str, dict[str, Any]] = {
    "roc_curve_binary": {
        "display_id": "Figure2",
        "template_id": "roc_curve_binary",
        "title": "ROC curve",
        "caption": "Binary or horizon-specific discrimination.",
        "x_label": "1 - Specificity",
        "y_label": "Sensitivity",
        "reference_line": {"x": [0.0, 1.0], "y": [0.0, 1.0], "label": "Chance"},
        "series": [
            {
                "label": "MAS model",
                "x": [round(i / 79, 4) for i in range(80)],
                "y": [round(1 - (1 - i / 79) ** 2.5, 4) for i in range(80)],
                "annotation": "AUC 0.86",
            },
            {
                "label": "Clinical model",
                "x": [round(i / 79, 4) for i in range(80)],
                "y": [round(1 - (1 - i / 79) ** 1.55, 4) for i in range(80)],
                "annotation": "AUC 0.74",
            },
        ],
    },
    "pr_curve_binary": {
        "display_id": "Figure3",
        "template_id": "pr_curve_binary",
        "title": "Precision-recall curve",
        "caption": "For imbalanced binary outcomes.",
        "x_label": "Recall",
        "y_label": "Precision",
        "reference_line": {"x": [0.0, 1.0], "y": [0.22, 0.22], "label": "Prevalence"},
        "series": [
            {
                "label": "MAS model",
                "x": [round(i / 89, 4) for i in range(90)],
                "y": [round(0.35 + 0.62 * (1 - i / 89) ** 0.65, 4) for i in range(90)],
            },
            {
                "label": "Clinical baseline",
                "x": [round(i / 89, 4) for i in range(90)],
                "y": [round(0.25 + 0.52 * (1 - i / 89) ** 0.90, 4) for i in range(90)],
            },
        ],
    },
    "calibration_curve_binary": {
        "display_id": "Figure4",
        "template_id": "calibration_curve_binary",
        "title": "Calibration curve",
        "caption": "Predicted probability vs observed risk.",
        "x_label": "Predicted risk",
        "y_label": "Observed risk",
        "reference_line": {"x": [0.0, 1.0], "y": [0.0, 1.0], "label": "Ideal"},
        "points": [
            {"predicted": 0.05, "observed": 0.03, "lower": 0.00, "upper": 0.13},
            {"predicted": 0.15, "observed": 0.16, "lower": 0.07, "upper": 0.23},
            {"predicted": 0.25, "observed": 0.28, "lower": 0.17, "upper": 0.33},
            {"predicted": 0.35, "observed": 0.34, "lower": 0.27, "upper": 0.43},
            {"predicted": 0.45, "observed": 0.47, "lower": 0.37, "upper": 0.53},
            {"predicted": 0.55, "observed": 0.55, "lower": 0.47, "upper": 0.63},
            {"predicted": 0.65, "observed": 0.69, "lower": 0.57, "upper": 0.73},
            {"predicted": 0.75, "observed": 0.73, "lower": 0.67, "upper": 0.83},
            {"predicted": 0.85, "observed": 0.86, "lower": 0.77, "upper": 0.93},
            {"predicted": 0.95, "observed": 0.98, "lower": 0.87, "upper": 1.00},
        ],
    },
    "time_dependent_roc_horizon": {
        "display_id": "Figure8",
        "template_id": "time_dependent_roc_horizon",
        "title": "Time-dependent ROC",
        "caption": "AUC by landmark horizon.",
        "x_label": "1 - Specificity",
        "y_label": "Sensitivity",
        "reference_line": {"x": [0.0, 1.0], "y": [0.0, 1.0], "label": "Chance"},
        "series": [
            {
                "label": "12 months",
                "x": [round(i / 69, 4) for i in range(70)],
                "y": [round(1 - (1 - i / 69) ** 2.1, 4) for i in range(70)],
                "annotation": "AUC = 0.80",
            },
            {
                "label": "36 months",
                "x": [round(i / 69, 4) for i in range(70)],
                "y": [round(1 - (1 - i / 69) ** 2.5, 4) for i in range(70)],
                "annotation": "AUC = 0.83",
            },
            {
                "label": "60 months",
                "x": [round(i / 69, 4) for i in range(70)],
                "y": [round(1 - (1 - i / 69) ** 2.0, 4) for i in range(70)],
                "annotation": "AUC = 0.79",
            },
        ],
    },
    "cumulative_incidence_grouped": {
        "display_id": "Figure7",
        "template_id": "cumulative_incidence_grouped",
        "title": "Cumulative incidence curve",
        "caption": "Grouped time-to-event incidence.",
        "x_label": "Time, months",
        "y_label": "Cumulative incidence",
        "groups": [
            {
                "label": "High Risk",
                "times": [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
                "values": [0.00, 0.08, 0.13, 0.20, 0.27, 0.33, 0.39, 0.43, 0.47, 0.52, 0.56, 0.60, 0.63],
            },
            {
                "label": "Low Risk",
                "times": [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
                "values": [0.00, 0.04, 0.07, 0.11, 0.15, 0.18, 0.22, 0.25, 0.29, 0.32, 0.35, 0.38, 0.41],
            },
        ],
    },
    "forest_effect_main": {
        "display_id": "Figure12",
        "template_id": "forest_effect_main",
        "title": "Forest plot",
        "caption": "Effect estimates with 95% CI.",
        "x_label": "Hazard ratio (log scale)",
        "reference_value": 1.0,
        "rows": [
            {"label": "Risk score high", "estimate": 2.10, "lower": 1.42, "upper": 3.12, "p_value": "0.001"},
            {"label": "cT stage III-IV", "estimate": 1.65, "lower": 1.10, "upper": 2.49, "p_value": "0.018"},
            {"label": "N positive", "estimate": 1.48, "lower": 1.02, "upper": 2.15, "p_value": "0.040"},
            {"label": "Age >= 65", "estimate": 1.12, "lower": 0.82, "upper": 1.55, "p_value": "0.48"},
            {"label": "Left-sided", "estimate": 0.82, "lower": 0.60, "upper": 1.14, "p_value": "0.24"},
        ],
    },
    "center_transportability_governance_summary_panel": {
        "display_id": "Figure17",
        "template_id": "center_transportability_governance_summary_panel",
        "title": "Center transportability governance summary",
        "caption": "Center-level external transportability action summary.",
        "metric_family": "c_index",
        "metric_panel_title": "Cohort discrimination",
        "metric_x_label": "C-index",
        "metric_reference_value": 0.74,
        "batch_shift_threshold": 0.04,
        "slope_acceptance_lower": 0.85,
        "slope_acceptance_upper": 1.15,
        "oe_ratio_acceptance_lower": 0.85,
        "oe_ratio_acceptance_upper": 1.15,
        "summary_panel_title": "Transportability action",
        "centers": [
            {
                "center_id": "derivation",
                "center_label": "Derivation lock",
                "cohort_role": "derivation_reference",
                "support_count": 24100,
                "event_count": 2260,
                "metric_estimate": 0.75,
                "metric_lower": 0.73,
                "metric_upper": 0.77,
                "max_shift": 0.02,
                "slope": 1.00,
                "oe_ratio": 1.00,
                "verdict": "stable",
                "action": "Use as reference",
            },
            {
                "center_id": "external_a",
                "center_label": "External A",
                "cohort_role": "external_validation",
                "support_count": 19840,
                "event_count": 1810,
                "metric_estimate": 0.74,
                "metric_lower": 0.72,
                "metric_upper": 0.76,
                "max_shift": 0.03,
                "slope": 0.96,
                "oe_ratio": 1.04,
                "verdict": "stable",
                "action": "Proceed with monitoring",
            },
            {
                "center_id": "transport_b",
                "center_label": "Transport B",
                "cohort_role": "transport_target",
                "support_count": 16320,
                "event_count": 1490,
                "metric_estimate": 0.72,
                "metric_lower": 0.70,
                "metric_upper": 0.75,
                "max_shift": 0.05,
                "slope": 0.90,
                "oe_ratio": 1.10,
                "verdict": "monitor",
                "action": "Monitor calibration drift",
            },
        ],
    },
    "heatmap_group_comparison": {
        "display_id": "Figure18",
        "template_id": "heatmap_group_comparison",
        "title": "ComplexHeatmap annotated matrix",
        "caption": "RiskGroup annotated matrix.",
        "x_label": "",
        "y_label": "",
        "metric_name": "Z-score",
        "row_order": [{"label": item} for item in [f"Hallmark {letter}" for letter in "ABCDEFGH"]],
        "column_order": [{"label": item} for item in ["S1", "S2", "S3", "S4", "S5", "S6"]],
        "column_annotations": [{"label": "RiskGroup", "values": ["Low", "Low", "Low", "High", "High", "High"]}],
        "cells": [
            {"x": sample, "y": hallmark, "value": value}
            for hallmark, values in [
                ("Hallmark A", [-0.96, -1.09, 0.20, -0.15, 0.32, -0.05]),
                ("Hallmark B", [-0.29, 1.27, -0.74, -0.96, -0.73, 0.17]),
                ("Hallmark C", [0.26, -0.44, 0.96, 0.59, -0.66, 0.68]),
                ("Hallmark D", [-1.15, -1.05, -0.38, -0.47, 0.27, 0.31]),
                ("Hallmark E", [0.20, -0.25, -0.36, -0.36, 0.60, 0.39]),
                ("Hallmark F", [0.03, -0.06, -0.27, -0.50, -0.38, -1.15]),
                ("Hallmark G", [1.03, -0.14, 0.74, 0.65, 0.17, 0.58]),
                ("Hallmark H", [1.14, -0.69, 0.49, 0.35, 0.29, 0.57]),
            ]
            for sample, value in zip(["S1", "S2", "S3", "S4", "S5", "S6"], values, strict=True)
        ],
    },
}


__all__ = ["CORE_R_DISPLAY_PAYLOADS"]
