from tests.submission_minimal_cases.package_core_and_authority_cases.core_materialization import (
    test_create_submission_minimal_package_creates_output_directory_and_copies_pdf,
    test_create_submission_minimal_package_uses_delivery_layout_v2,
    test_create_submission_minimal_package_route_gate_blocks_materialization,
    test_create_submission_minimal_package_materializes_audit_package_when_authority_snapshot_missing,
    test_create_submission_minimal_package_materializes_audit_package_for_submission_human_gate,
    test_create_submission_minimal_package_writes_manifest_and_docx_path,
    test_create_submission_minimal_package_preserves_existing_package_when_materialization_fails,
    test_create_submission_minimal_package_defaults_to_ama_citation_style,
    test_create_submission_minimal_package_copies_figures_and_tables,
    test_create_submission_minimal_package_uses_existing_figure_exports_when_catalog_lists_missing_alternative,
    test_create_submission_minimal_package_accepts_current_figure_and_table_catalog_shape,
)
from tests.submission_minimal_cases.package_core_and_authority_cases.authority_and_sources import (
    test_create_submission_minimal_package_prefers_current_compile_source_and_refreshes_review,
    test_general_medical_submission_source_alias_is_authority_note,
    test_describe_submission_minimal_authority_detects_content_change_but_ignores_mtime,
    test_create_submission_minimal_package_canonicalizes_authoritative_worktree_source_paths,
    test_create_submission_minimal_package_supports_stage_native_current_body_source,
    test_create_submission_minimal_package_accepts_materialized_submission_source,
    test_submission_authority_ignores_post_gate_evidence_ledger_refresh,
    test_create_submission_minimal_package_wires_excluded_roots_to_compiled_source_resolvers,
    test_describe_submission_minimal_authority_flags_legacy_manifest_when_source_is_newer,
    test_resolve_compiled_pdf_path_uses_present_compiled_pdf_asset_when_report_lacks_pdf_path,
    test_create_submission_minimal_package_rebuilds_pdf_when_compile_report_lacks_pdf_candidate,
    test_submission_source_signature_changes_with_renderer_contract,
)
from tests.submission_minimal_cases.shared import (
    make_paper_workspace,
    remove_authority_snapshots,
)
