from __future__ import annotations

from .shared import display_layout_qc, display_pack_lock, display_pack_runtime, display_registry, get_pack_id, get_template_short_id, publication_display_contract
from .shared import _INPUT_FILENAME_BY_SCHEMA_ID, _TABLE_INPUT_FILENAME_BY_SCHEMA_ID, _ILLUSTRATION_INPUT_FILENAME_BY_SCHEMA_ID, _ILLUSTRATION_OUTPUT_STEM_BY_TEMPLATE_SHORT_ID, _ILLUSTRATION_DEFAULT_TEXT_BY_TEMPLATE_SHORT_ID, _TABLE_OUTPUT_CONFIG_BY_TEMPLATE_SHORT_ID, _REPO_ROOT, _resolve_illustration_shell_paper_role, utc_now, load_json, dump_json, write_text, _paper_relative_path, _build_render_context, _require_namespaced_registry_id, _read_bool_override, _normalize_figure_catalog_id, _normalize_table_catalog_id, _resolve_figure_catalog_id, _resolve_table_catalog_id, _replace_catalog_entry, _collect_referenced_generated_surface_paths, _prune_unreferenced_generated_surface_outputs, _build_paper_surface_readmes, _require_non_empty_string, _require_numeric_list, _require_numeric_value, _require_probability_value, _require_strictly_increasing_numeric_list, _require_non_negative_int, _COHORT_FLOW_DESIGN_PANEL_ROLE_ALIASES, _format_percent_1dp, _evidence_payload_path, _illustration_payload_path, _table_payload_path
from .r_source import _R_EVIDENCE_RENDERER_SOURCE
from .validation_tables import _validate_cohort_flow_payload, _validate_submission_graphical_abstract_payload, _validate_baseline_table_payload, _validate_column_table_payload, _validate_performance_summary_table_generic_payload, _validate_grouped_risk_event_summary_table_payload, _validate_reference_line_payload, _validate_axis_window_payload, _validate_curve_series_payload, _validate_single_curve_series_payload, _validate_audit_panel_collection, _validate_labeled_order_payload, _validate_panel_order_payload, _validate_sample_order_payload
from .validation_curves_primary import _validate_time_to_event_decision_curve_display_payload, _validate_binary_curve_display_payload, _validate_time_dependent_roc_comparison_display_payload, _validate_risk_layering_bar_payload, _validate_risk_layering_display_payload, _validate_binary_calibration_decision_curve_display_payload
from .validation_curves_extended import _validate_model_complexity_audit_display_payload, _validate_time_to_event_landmark_performance_display_payload, _validate_time_to_event_threshold_governance_display_payload, _validate_time_to_event_multihorizon_calibration_display_payload, _validate_time_to_event_display_payload, _validate_time_to_event_stratified_cumulative_incidence_display_payload, _validate_time_to_event_discrimination_calibration_display_payload
from .validation_atlas_primary import _validate_embedding_display_payload, _validate_celltype_signature_heatmap_display_payload, _validate_single_cell_atlas_overview_display_payload, _validate_atlas_spatial_bridge_display_payload
from .validation_atlas_trajectory import _validate_spatial_niche_map_display_payload, _validate_trajectory_progression_display_payload
from .validation_atlas_storyboards import _validate_atlas_spatial_trajectory_storyboard_display_payload, _validate_atlas_spatial_trajectory_density_coverage_display_payload, _validate_atlas_spatial_trajectory_context_support_display_payload, _validate_atlas_manifold_panels_payload, _validate_atlas_spatial_trajectory_multimanifold_context_support_display_payload
from .validation_omics_heatmaps import _validate_heatmap_display_payload, _validate_performance_heatmap_display_payload, _validate_confusion_matrix_heatmap_binary_display_payload, _validate_clustered_heatmap_display_payload, _validate_gsva_ssgsea_heatmap_display_payload
from .validation_omics_panels import _validate_pathway_enrichment_dotplot_panel_display_payload, _validate_celltype_marker_dotplot_panel_display_payload, _validate_oncoplot_mutation_landscape_panel_display_payload, _validate_cnv_recurrence_summary_panel_display_payload
from .validation_omics_genomic import _validate_genomic_alteration_landscape_panel_display_payload, _validate_genomic_alteration_consequence_panel_display_payload, _validate_genomic_alteration_multiomic_consequence_panel_display_payload, _validate_genomic_alteration_pathway_integrated_composite_panel_display_payload, _validate_genomic_program_governance_summary_panel_display_payload, _validate_omics_volcano_panel_display_payload
from .validation_effects import _validate_forest_display_payload, _validate_compact_effect_estimate_panel_display_payload, _validate_coefficient_path_panel_display_payload, _validate_broader_heterogeneity_summary_panel_display_payload, _validate_interaction_effect_summary_panel_display_payload
from .validation_shap_summary import _validate_shap_summary_display_payload, _validate_shap_dependence_panel_display_payload, _validate_shap_waterfall_local_explanation_panel_display_payload, _validate_shap_force_like_summary_panel_display_payload, _normalize_shap_grouped_local_panels, _validate_shap_grouped_local_explanation_panel_display_payload
from .validation_shap_paths import _validate_shap_grouped_decision_path_panel_display_payload, _validate_shap_multigroup_decision_path_panel_display_payload
from .validation_response_primary import _validate_partial_dependence_ice_panel_display_payload, _validate_partial_dependence_interaction_contour_panel_display_payload
from .validation_shap_importance import _validate_shap_bar_importance_display_payload, _validate_shap_signed_importance_panel_display_payload, _validate_shap_multicohort_importance_panel_display_payload
from .validation_response_secondary import _validate_partial_dependence_interaction_slice_panel_display_payload, _validate_partial_dependence_subgroup_comparison_panel_display_payload, _validate_accumulated_local_effects_panel_display_payload
from .validation_support_domain import _normalize_feature_response_support_panels, _validate_feature_response_support_domain_panel_display_payload, _validate_shap_grouped_local_support_domain_panel_display_payload, _validate_shap_multigroup_decision_path_support_domain_panel_display_payload, _validate_shap_signed_importance_local_support_domain_panel_display_payload
from .validation_generalizability import _validate_multicenter_generalizability_display_payload, _validate_generalizability_subgroup_composite_display_payload, _validate_center_transportability_governance_summary_panel_display_payload
from .payload_loader import _load_evidence_display_payload
from .illustrations import _FlowTextLine, _FlowNodeSpec, _GraphvizNodeBox, _GraphvizLayout, _flow_font_path, _flow_font_properties, _measure_flow_text_width_pt, _wrap_flow_text_to_width, _wrap_figure_title_to_width, _flow_html_label_for_node, _run_graphviz_layout, _flow_box_to_normalized, _flow_union_box, _render_cohort_flow_figure, _build_submission_graphical_abstract_arrow_lane_spec, _choose_submission_graphical_abstract_arrow_lane, _choose_shared_submission_graphical_abstract_arrow_lane, _render_submission_graphical_abstract, _write_rectangular_table_outputs, _write_table_outputs
from .geometry import _bbox_to_layout_box, _data_box_to_layout_box, _data_point_to_figure_xy, _clip_line_segment_to_axes_window, _clip_reference_line_to_axes_window, _normalize_reference_line_to_device_space, _normalize_reference_line_collection_to_device_space, _build_python_shap_layout_sidecar
from .renderers import _load_layout_sidecar_or_raise, _render_r_evidence_figure, _centered_offsets, _prepare_python_render_output_paths, _prepare_python_illustration_output_paths, _prepare_table_shell_output_paths, _apply_publication_axes_style, _build_single_panel_layout_sidecar, _render_python_evidence_figure
from .materialize import _iter_display_surface_entries, materialize_display_surface

__all__ = [
    "_INPUT_FILENAME_BY_SCHEMA_ID",
    "_TABLE_INPUT_FILENAME_BY_SCHEMA_ID",
    "_ILLUSTRATION_INPUT_FILENAME_BY_SCHEMA_ID",
    "_ILLUSTRATION_OUTPUT_STEM_BY_TEMPLATE_SHORT_ID",
    "_ILLUSTRATION_DEFAULT_TEXT_BY_TEMPLATE_SHORT_ID",
    "_TABLE_OUTPUT_CONFIG_BY_TEMPLATE_SHORT_ID",
    "_REPO_ROOT",
    "_resolve_illustration_shell_paper_role",
    "_R_EVIDENCE_RENDERER_SOURCE",
    "utc_now",
    "load_json",
    "dump_json",
    "write_text",
    "_paper_relative_path",
    "_build_render_context",
    "_require_namespaced_registry_id",
    "_read_bool_override",
    "_normalize_figure_catalog_id",
    "_normalize_table_catalog_id",
    "_resolve_figure_catalog_id",
    "_resolve_table_catalog_id",
    "_replace_catalog_entry",
    "_collect_referenced_generated_surface_paths",
    "_prune_unreferenced_generated_surface_outputs",
    "_build_paper_surface_readmes",
    "_require_non_empty_string",
    "_require_numeric_list",
    "_require_numeric_value",
    "_require_probability_value",
    "_require_strictly_increasing_numeric_list",
    "_require_non_negative_int",
    "_COHORT_FLOW_DESIGN_PANEL_ROLE_ALIASES",
    "_validate_cohort_flow_payload",
    "_validate_submission_graphical_abstract_payload",
    "_validate_baseline_table_payload",
    "_validate_column_table_payload",
    "_format_percent_1dp",
    "_validate_performance_summary_table_generic_payload",
    "_validate_grouped_risk_event_summary_table_payload",
    "_validate_reference_line_payload",
    "_validate_axis_window_payload",
    "_validate_time_to_event_decision_curve_display_payload",
    "_evidence_payload_path",
    "_illustration_payload_path",
    "_table_payload_path",
    "_validate_curve_series_payload",
    "_validate_single_curve_series_payload",
    "_validate_binary_curve_display_payload",
    "_validate_time_dependent_roc_comparison_display_payload",
    "_validate_risk_layering_bar_payload",
    "_validate_risk_layering_display_payload",
    "_validate_binary_calibration_decision_curve_display_payload",
    "_validate_audit_panel_collection",
    "_validate_model_complexity_audit_display_payload",
    "_validate_time_to_event_landmark_performance_display_payload",
    "_validate_time_to_event_threshold_governance_display_payload",
    "_validate_time_to_event_multihorizon_calibration_display_payload",
    "_validate_time_to_event_display_payload",
    "_validate_time_to_event_stratified_cumulative_incidence_display_payload",
    "_validate_time_to_event_discrimination_calibration_display_payload",
    "_validate_embedding_display_payload",
    "_validate_celltype_signature_heatmap_display_payload",
    "_validate_single_cell_atlas_overview_display_payload",
    "_validate_atlas_spatial_bridge_display_payload",
    "_validate_spatial_niche_map_display_payload",
    "_validate_trajectory_progression_display_payload",
    "_validate_atlas_spatial_trajectory_storyboard_display_payload",
    "_validate_atlas_spatial_trajectory_density_coverage_display_payload",
    "_validate_atlas_spatial_trajectory_context_support_display_payload",
    "_validate_atlas_manifold_panels_payload",
    "_validate_atlas_spatial_trajectory_multimanifold_context_support_display_payload",
    "_validate_heatmap_display_payload",
    "_validate_performance_heatmap_display_payload",
    "_validate_confusion_matrix_heatmap_binary_display_payload",
    "_validate_labeled_order_payload",
    "_validate_clustered_heatmap_display_payload",
    "_validate_gsva_ssgsea_heatmap_display_payload",
    "_validate_panel_order_payload",
    "_validate_sample_order_payload",
    "_validate_pathway_enrichment_dotplot_panel_display_payload",
    "_validate_celltype_marker_dotplot_panel_display_payload",
    "_validate_oncoplot_mutation_landscape_panel_display_payload",
    "_validate_cnv_recurrence_summary_panel_display_payload",
    "_validate_genomic_alteration_landscape_panel_display_payload",
    "_validate_genomic_alteration_consequence_panel_display_payload",
    "_validate_genomic_alteration_multiomic_consequence_panel_display_payload",
    "_validate_genomic_alteration_pathway_integrated_composite_panel_display_payload",
    "_validate_genomic_program_governance_summary_panel_display_payload",
    "_validate_omics_volcano_panel_display_payload",
    "_validate_forest_display_payload",
    "_validate_compact_effect_estimate_panel_display_payload",
    "_validate_coefficient_path_panel_display_payload",
    "_validate_broader_heterogeneity_summary_panel_display_payload",
    "_validate_interaction_effect_summary_panel_display_payload",
    "_validate_shap_summary_display_payload",
    "_validate_shap_dependence_panel_display_payload",
    "_validate_shap_waterfall_local_explanation_panel_display_payload",
    "_validate_shap_force_like_summary_panel_display_payload",
    "_normalize_shap_grouped_local_panels",
    "_validate_shap_grouped_local_explanation_panel_display_payload",
    "_validate_shap_grouped_decision_path_panel_display_payload",
    "_validate_shap_multigroup_decision_path_panel_display_payload",
    "_validate_partial_dependence_ice_panel_display_payload",
    "_validate_partial_dependence_interaction_contour_panel_display_payload",
    "_validate_shap_bar_importance_display_payload",
    "_validate_shap_signed_importance_panel_display_payload",
    "_validate_shap_multicohort_importance_panel_display_payload",
    "_validate_partial_dependence_interaction_slice_panel_display_payload",
    "_validate_partial_dependence_subgroup_comparison_panel_display_payload",
    "_validate_accumulated_local_effects_panel_display_payload",
    "_normalize_feature_response_support_panels",
    "_validate_feature_response_support_domain_panel_display_payload",
    "_validate_shap_grouped_local_support_domain_panel_display_payload",
    "_validate_shap_multigroup_decision_path_support_domain_panel_display_payload",
    "_validate_shap_signed_importance_local_support_domain_panel_display_payload",
    "_validate_multicenter_generalizability_display_payload",
    "_validate_generalizability_subgroup_composite_display_payload",
    "_validate_center_transportability_governance_summary_panel_display_payload",
    "_load_evidence_display_payload",
    "_FlowTextLine",
    "_FlowNodeSpec",
    "_GraphvizNodeBox",
    "_GraphvizLayout",
    "_flow_font_path",
    "_flow_font_properties",
    "_measure_flow_text_width_pt",
    "_wrap_flow_text_to_width",
    "_wrap_figure_title_to_width",
    "_flow_html_label_for_node",
    "_run_graphviz_layout",
    "_flow_box_to_normalized",
    "_flow_union_box",
    "_render_cohort_flow_figure",
    "_build_submission_graphical_abstract_arrow_lane_spec",
    "_choose_submission_graphical_abstract_arrow_lane",
    "_choose_shared_submission_graphical_abstract_arrow_lane",
    "_render_submission_graphical_abstract",
    "_write_rectangular_table_outputs",
    "_write_table_outputs",
    "_bbox_to_layout_box",
    "_data_box_to_layout_box",
    "_data_point_to_figure_xy",
    "_clip_line_segment_to_axes_window",
    "_clip_reference_line_to_axes_window",
    "_normalize_reference_line_to_device_space",
    "_normalize_reference_line_collection_to_device_space",
    "_build_python_shap_layout_sidecar",
    "_load_layout_sidecar_or_raise",
    "_render_r_evidence_figure",
    "_centered_offsets",
    "_prepare_python_render_output_paths",
    "_prepare_python_illustration_output_paths",
    "_prepare_table_shell_output_paths",
    "_apply_publication_axes_style",
    "_build_single_panel_layout_sidecar",
    "_render_python_evidence_figure",
    "_iter_display_surface_entries",
    "materialize_display_surface",
    "display_layout_qc",
    "display_pack_lock",
    "display_pack_runtime",
    "display_registry",
    "publication_display_contract",
    "get_pack_id",
    "get_template_short_id",
]
