from __future__ import annotations


INPUT_FILENAME_BY_SCHEMA_ID: dict[str, str] = {
    "binary_prediction_curve_inputs_v1": "binary_prediction_curve_inputs.json",
    "time_dependent_roc_comparison_inputs_v1": "time_dependent_roc_comparison_inputs.json",
    "time_to_event_landmark_performance_inputs_v1": "time_to_event_landmark_performance_inputs.json",
    "time_to_event_threshold_governance_inputs_v1": "time_to_event_threshold_governance_inputs.json",
    "time_to_event_multihorizon_calibration_inputs_v1": "time_to_event_multihorizon_calibration_inputs.json",
    "time_to_event_grouped_inputs_v1": "time_to_event_grouped_inputs.json",
    "time_to_event_stratified_cumulative_incidence_inputs_v1": "time_to_event_stratified_cumulative_incidence_inputs.json",
    "time_to_event_discrimination_calibration_inputs_v1": "time_to_event_discrimination_calibration_inputs.json",
    "time_to_event_decision_curve_inputs_v1": "time_to_event_decision_curve_inputs.json",
    "risk_layering_monotonic_inputs_v1": "risk_layering_monotonic_inputs.json",
    "binary_calibration_decision_curve_panel_inputs_v1": "binary_calibration_decision_curve_panel_inputs.json",
    "model_complexity_audit_panel_inputs_v1": "model_complexity_audit_panel_inputs.json",
    "embedding_grouped_inputs_v1": "embedding_grouped_inputs.json",
    "celltype_signature_heatmap_inputs_v1": "celltype_signature_heatmap_inputs.json",
    "single_cell_atlas_overview_inputs_v1": "single_cell_atlas_overview_inputs.json",
    "atlas_spatial_bridge_panel_inputs_v1": "atlas_spatial_bridge_panel_inputs.json",
    "spatial_niche_map_inputs_v1": "spatial_niche_map_inputs.json",
    "trajectory_progression_inputs_v1": "trajectory_progression_inputs.json",
    "atlas_spatial_trajectory_storyboard_inputs_v1": "atlas_spatial_trajectory_storyboard_inputs.json",
    "atlas_spatial_trajectory_density_coverage_panel_inputs_v1": "atlas_spatial_trajectory_density_coverage_panel_inputs.json",
    "atlas_spatial_trajectory_context_support_panel_inputs_v1": "atlas_spatial_trajectory_context_support_panel_inputs.json",
    "omics_volcano_panel_inputs_v1": "omics_volcano_panel_inputs.json",
    "heatmap_group_comparison_inputs_v1": "heatmap_group_comparison_inputs.json",
    "performance_heatmap_inputs_v1": "performance_heatmap_inputs.json",
    "correlation_heatmap_inputs_v1": "correlation_heatmap_inputs.json",
    "clustered_heatmap_inputs_v1": "clustered_heatmap_inputs.json",
    "gsva_ssgsea_heatmap_inputs_v1": "gsva_ssgsea_heatmap_inputs.json",
    "pathway_enrichment_dotplot_panel_inputs_v1": "pathway_enrichment_dotplot_panel_inputs.json",
    "oncoplot_mutation_landscape_panel_inputs_v1": "oncoplot_mutation_landscape_panel_inputs.json",
    "cnv_recurrence_summary_panel_inputs_v1": "cnv_recurrence_summary_panel_inputs.json",
    "genomic_alteration_landscape_panel_inputs_v1": "genomic_alteration_landscape_panel_inputs.json",
    "genomic_alteration_consequence_panel_inputs_v1": "genomic_alteration_consequence_panel_inputs.json",
    "forest_effect_inputs_v1": "forest_effect_inputs.json",
    "generalizability_subgroup_composite_inputs_v1": "generalizability_subgroup_composite_inputs.json",
    "compact_effect_estimate_panel_inputs_v1": "compact_effect_estimate_panel_inputs.json",
    "coefficient_path_panel_inputs_v1": "coefficient_path_panel_inputs.json",
    "broader_heterogeneity_summary_panel_inputs_v1": "broader_heterogeneity_summary_panel_inputs.json",
    "center_transportability_governance_summary_panel_inputs_v1": "center_transportability_governance_summary_panel_inputs.json",
    "shap_summary_inputs_v1": "shap_summary_inputs.json",
    "shap_bar_importance_inputs_v1": "shap_bar_importance_inputs.json",
    "shap_signed_importance_panel_inputs_v1": "shap_signed_importance_panel_inputs.json",
    "shap_multicohort_importance_panel_inputs_v1": "shap_multicohort_importance_panel_inputs.json",
    "shap_dependence_panel_inputs_v1": "shap_dependence_panel_inputs.json",
    "shap_waterfall_local_explanation_panel_inputs_v1": "shap_waterfall_local_explanation_panel_inputs.json",
    "shap_force_like_summary_panel_inputs_v1": "shap_force_like_summary_panel_inputs.json",
    "shap_grouped_local_explanation_panel_inputs_v1": "shap_grouped_local_explanation_panel_inputs.json",
    "shap_grouped_decision_path_panel_inputs_v1": "shap_grouped_decision_path_panel_inputs.json",
    "shap_multigroup_decision_path_panel_inputs_v1": "shap_multigroup_decision_path_panel_inputs.json",
    "partial_dependence_ice_panel_inputs_v1": "partial_dependence_ice_panel_inputs.json",
    "partial_dependence_interaction_contour_panel_inputs_v1": "partial_dependence_interaction_contour_panel_inputs.json",
    "partial_dependence_interaction_slice_panel_inputs_v1": "partial_dependence_interaction_slice_panel_inputs.json",
    "partial_dependence_subgroup_comparison_panel_inputs_v1": "partial_dependence_subgroup_comparison_panel_inputs.json",
    "accumulated_local_effects_panel_inputs_v1": "accumulated_local_effects_panel_inputs.json",
    "feature_response_support_domain_panel_inputs_v1": "feature_response_support_domain_panel_inputs.json",
    "shap_grouped_local_support_domain_panel_inputs_v1": "shap_grouped_local_support_domain_panel_inputs.json",
    "multicenter_generalizability_inputs_v1": "multicenter_generalizability_inputs.json",
    "workflow_fact_sheet_panel_inputs_v1": "workflow_fact_sheet_panel.json",
    "design_evidence_composite_shell_inputs_v1": "design_evidence_composite_shell.json",
    "baseline_missingness_qc_panel_inputs_v1": "baseline_missingness_qc_panel.json",
    "center_coverage_batch_transportability_panel_inputs_v1": "center_coverage_batch_transportability_panel.json",
    "transportability_recalibration_governance_panel_inputs_v1": "transportability_recalibration_governance_panel.json",
}


TABLE_INPUT_FILENAME_BY_SCHEMA_ID: dict[str, str] = {
    "baseline_characteristics_schema_v1": "baseline_characteristics_schema.json",
    "time_to_event_performance_summary_v1": "time_to_event_performance_summary.json",
    "clinical_interpretation_summary_v1": "clinical_interpretation_summary.json",
    "performance_summary_table_generic_v1": "performance_summary_table_generic.json",
    "grouped_risk_event_summary_table_v1": "grouped_risk_event_summary_table.json",
}
