from __future__ import annotations


REVIEWER_TEMPLATE_CONCERNS = {
    "observational_real_world": {
        "missingness_plan": "Missing data could distort denominators, exposure ascertainment, endpoint capture, or site comparability.",
        "sample_size_precision_plan": "The real-world estimate needs denominator, event-count, and interval precision support before reviewer-facing interpretation.",
        "external_validation_plan": "A transportability claim needs temporal, site-held-out, or registry-held-out evidence; otherwise the manuscript must state an internal claim boundary.",
        "subgroup_plan": "Subgroup language must be prespecified, clinically meaningful, and supported by interpretable uncertainty.",
        "multiplicity_guardrail": "Repeated endpoints, exposures, and subgroup contrasts need a declared primary family and multiplicity interpretation rule.",
        "clinical_utility_plan": "The estimate must map to absolute risk, guideline relevance, a decision threshold, or a care-pathway consequence.",
        "endpoint_time_window": "Endpoint semantics require locked index date, lookback, ascertainment window, and follow-up closure before reviewer clearance.",
        "sensitivity_plan": "Robustness to confounding, coding drift, missingness, time-window variation, and site support must be auditable.",
    },
    "prediction_external_validation": {
        "missingness_plan": "Predictor missingness, unavailable features, and deployment-time missingness behavior must be reviewer-visible.",
        "sample_size_precision_plan": "Performance claims need effective sample size, events, calibration precision, and uncertainty rather than nominal significance.",
        "external_validation_plan": "Generalizable prediction or validation claims require locked external, temporal, or site-held-out validation and calibration evidence.",
        "subgroup_plan": "Clinically important strata need discrimination, calibration, and threshold-performance support with uncertainty.",
        "multiplicity_guardrail": "Model metrics, threshold scans, subgroup checks, and recalibration attempts must be separated from the locked primary claim.",
        "clinical_utility_plan": "Performance metrics need intended-use, threshold, calibration, and net-benefit or decision-impact evidence.",
        "endpoint_time_window": "Prediction origin, lookback, prediction horizon, outcome window, and censoring must match the target-use claim.",
        "sensitivity_plan": "Optimism, calibration drift, threshold sensitivity, missing predictors, and outcome-definition robustness must be tested.",
    },
    "subtype_triage": {
        "missingness_plan": "Subtype-defining variables, gray-zone markers, reference-standard gaps, and indeterminate outcomes need explicit handling.",
        "sample_size_precision_plan": "Subtype or gray-zone claims need support, stability, threshold precision, and minimum interpretable slice size.",
        "external_validation_plan": "Durable subtype labels or triage thresholds need held-out, temporal, bootstrap, or external stability evidence.",
        "subgroup_plan": "Subtype and triage interpretations must map to prespecified clinical strata and avoid unsupported post-hoc naming.",
        "multiplicity_guardrail": "Discovery, characterization, threshold searching, and confirmatory contrasts need separate reviewer-visible boundaries.",
        "clinical_utility_plan": "Subtype names or triage rules must change diagnostic, prognostic, treatment-pattern, or workflow interpretation.",
        "endpoint_time_window": "Phenotype measurement, index assessment, reference-standard timing, decision window, and outcome follow-up must be locked.",
        "sensitivity_plan": "Algorithm, feature set, scaling, threshold perturbation, reference-standard uncertainty, and site support must be stress-tested.",
    },
    "ai_clinical_task": {
        "missingness_plan": "Missing modalities, annotation gaps, prompt/context absence, and abstention behavior must be explicit.",
        "sample_size_precision_plan": "AI task performance needs task-instance counts, patient-level independence, annotation support, and uncertainty.",
        "external_validation_plan": "Broad AI clinical task claims need locked external, temporal, site, or reader-environment validation.",
        "subgroup_plan": "Fairness, device, site, demographic, and severity slices need support and clinically interpretable error profiles.",
        "multiplicity_guardrail": "Prompt/model iteration must be separated from locked evaluation and repeated task or subgroup comparisons.",
        "clinical_utility_plan": "Aggregate accuracy must be tied to workflow impact, error severity, human-AI interaction, and clinical actionability.",
        "endpoint_time_window": "Task input time, clinical decision point, reference label timing, and follow-up outcome window must be locked.",
        "sensitivity_plan": "Model version, prompt/context variation, annotation disagreement, site shift, subgroup performance, and abstention rules must be checked.",
    },
}

ARCHETYPE_DISCIPLINE: dict[str, dict[str, str]] = {
    "observational_real_world": {
        "reporting_guideline": "STROBE with RECORD overlay when electronic health records or registry linkage are used.",
        "missingness_plan": "Quantify missingness by cohort, endpoint, exposure, and site; prespecify complete-case, imputation, and missing-indicator sensitivity checks.",
        "sample_size_precision_plan": "State available cohort size, event counts, subgroup support, and precision targets using confidence intervals or detectable effect ranges.",
        "external_validation_plan": "Use temporally separated, site-held-out, or registry-held-out checks when a transportability claim is made; otherwise declare the claim as internal only.",
        "subgroup_plan": "Prespecify clinically meaningful strata and minimum support thresholds before subgroup interpretation.",
        "multiplicity_guardrail": "Separate primary endpoints from exploratory contrasts and apply family-wise, false-discovery, or estimation-focused interpretation rules.",
        "clinical_utility_plan": "Tie effect estimates to absolute risk, decision threshold, care pathway, or guideline-relevant clinical action.",
        "endpoint_time_window": "Define index date, exposure lookback, outcome ascertainment window, and censoring or follow-up closure.",
        "sensitivity_plan": "Run prespecified robustness checks for confounding, coding drift, missingness, time-window variation, and site support.",
        "failure_conditions": "Block promotion when endpoint semantics, denominator support, missingness, confounding control, or external support cannot sustain the target claim.",
    },
    "prediction_model": {
        "reporting_guideline": "TRIPOD with TRIPOD+AI extension when model development uses AI or machine-learning components.",
        "missingness_plan": "Describe missing predictor handling, imputation, unavailable-feature routing, and deployment-time missingness behavior.",
        "sample_size_precision_plan": "Report events per parameter or effective sample size, calibration precision, confidence intervals, and optimism-correction assumptions.",
        "external_validation_plan": "Require external, temporal, or site-held-out validation before any generalizable performance or clinical deployment claim.",
        "subgroup_plan": "Prespecify subgroup discrimination, calibration, and threshold-performance checks for clinically important strata.",
        "multiplicity_guardrail": "Freeze primary model metrics and subgroup families before analysis; label feature fishing and threshold scans as exploratory.",
        "clinical_utility_plan": "Pair performance metrics with calibration, net benefit, decision thresholds, and intended-use consequences.",
        "endpoint_time_window": "Define prediction origin, feature lookback, prediction horizon, outcome window, and censoring treatment.",
        "sensitivity_plan": "Check optimism, calibration drift, threshold sensitivity, missing predictors, and alternative outcome definitions.",
        "failure_conditions": "Block promotion when validation, calibration, endpoint horizon, subgroup support, or intended-use utility is unresolved.",
    },
    "external_validation": {
        "reporting_guideline": "TRIPOD external validation reporting with transportability and calibration update details.",
        "missingness_plan": "Compare missingness between derivation and validation settings and state how validation-time absent variables are handled.",
        "sample_size_precision_plan": "Report validation sample size, event count, calibration precision, and uncertainty around discrimination and net-benefit estimates.",
        "external_validation_plan": "Treat validation cohort independence, case-mix shift, and recalibration policy as mandatory primary evidence surfaces.",
        "subgroup_plan": "Prespecify subgroup validation slices only where validation support is sufficient for interpretable uncertainty.",
        "multiplicity_guardrail": "Keep recalibration, threshold tuning, and subgroup scans separate from the primary validation claim.",
        "clinical_utility_plan": "Assess whether validation performance preserves the intended clinical action and threshold behavior.",
        "endpoint_time_window": "Lock validation index, prediction horizon, outcome ascertainment, and follow-up closure to match the target-use claim.",
        "sensitivity_plan": "Test calibration drift, case-mix shift, threshold transportability, and recalibration alternatives.",
        "failure_conditions": "Block promotion when independence, transportability, calibration, or validation precision is insufficient.",
    },
    "subtype_reconstruction": {
        "reporting_guideline": "STROBE with transparent unsupervised-learning and phenotype-definition reporting.",
        "missingness_plan": "Profile missingness for subtype-defining variables and specify inclusion, imputation, and variable-retention rules.",
        "sample_size_precision_plan": "State subtype support, cluster stability precision, site balance, and minimum interpretable subgroup size.",
        "external_validation_plan": "Require site-held-out, bootstrap, temporal, or external-cohort stability evidence before naming durable clinical subtypes.",
        "subgroup_plan": "Map subtypes to clinically interpretable strata, treatment patterns, and outcome gradients without post-hoc overclaiming.",
        "multiplicity_guardrail": "Separate subtype discovery from confirmatory characterization and control repeated characterization contrasts.",
        "clinical_utility_plan": "Tie subtype labels to diagnostic, prognostic, treatment-pattern, or care-pathway interpretability.",
        "endpoint_time_window": "Define phenotype measurement window, temporal ordering, and outcome follow-up windows used for subtype characterization.",
        "sensitivity_plan": "Check algorithm choice, feature set, scaling, missingness, site holdout, and subtype assignment stability.",
        "failure_conditions": "Block promotion when subtype stability, clinical naming, site support, or characterization evidence is weak.",
    },
    "gray_zone_triage": {
        "reporting_guideline": "STARD or TRIPOD as appropriate for diagnostic, prognostic, or triage-threshold framing.",
        "missingness_plan": "State how unavailable gray-zone markers, reference-standard gaps, and indeterminate outcomes are handled.",
        "sample_size_precision_plan": "Report gray-zone support, event or reference-standard counts, and threshold precision around decision boundaries.",
        "external_validation_plan": "Require temporally or clinically distinct validation before changing triage thresholds or claiming transportable gray-zone rules.",
        "subgroup_plan": "Prespecify clinically relevant threshold-performance slices and prohibit unsupported threshold claims in small strata.",
        "multiplicity_guardrail": "Lock candidate thresholds and gray-zone definitions before exploitation; mark threshold searches as exploratory.",
        "clinical_utility_plan": "Quantify downstream triage consequences, false positive/negative tradeoffs, and decision-curve or net-benefit evidence.",
        "endpoint_time_window": "Define index assessment, triage decision window, reference-standard timing, and outcome ascertainment interval.",
        "sensitivity_plan": "Check threshold perturbation, reference-standard uncertainty, missing markers, and subgroup threshold robustness.",
        "failure_conditions": "Block promotion when threshold stability, clinical tradeoff, validation, or reference-standard quality is unresolved.",
    },
    "ai_clinical_task": {
        "reporting_guideline": "TRIPOD+AI, CONSORT-AI, SPIRIT-AI, or DECIDE-AI according to task maturity and evaluation design.",
        "missingness_plan": "Document missing input modalities, annotation gaps, prompt/context absence, and deployment-time abstention or fallback behavior.",
        "sample_size_precision_plan": "Report task instances, patient-level independence, annotation support, uncertainty, and clinically meaningful performance precision.",
        "external_validation_plan": "Require locked external, temporal, site, or reader-environment validation before broad AI clinical task claims.",
        "subgroup_plan": "Prespecify fairness, site, device, demographic, and clinical-severity slices with minimum support and interpretability thresholds.",
        "multiplicity_guardrail": "Separate prompt/model iteration from locked evaluation and adjust or label repeated task and subgroup comparisons.",
        "clinical_utility_plan": "Evaluate effect on clinical workflow, error severity, human-AI interaction, and actionability beyond aggregate accuracy.",
        "endpoint_time_window": "Define task input time, clinical decision point, reference label timing, and follow-up outcome window.",
        "sensitivity_plan": "Check model version, prompt/context variation, annotation disagreement, site shift, subgroup performance, and abstention rules.",
        "failure_conditions": "Block promotion when locked evaluation, external validation, subgroup safety, clinical utility, or model-version traceability is missing.",
    },
}


__all__ = ["ARCHETYPE_DISCIPLINE", "REVIEWER_TEMPLATE_CONCERNS"]
