from __future__ import annotations

from pathlib import Path

from med_autoscience.policies import medical_publication_surface as medical_surface_policy
from med_autoscience.publication_profiles import (
    GENERAL_MEDICAL_JOURNAL_PROFILE,
    is_supported_publication_profile,
    normalize_publication_profile,
)
from med_autoscience.study_charter import read_study_charter, resolve_study_charter_ref
from med_autoscience.runtime_protocol.topology import resolve_paper_root_context

from .delivery_context import (
    FORMAL_PAPER_DELIVERY_RELATIVE_PATHS,
    SYNC_STAGES,
    _build_ledger_contract_linkage,
    _normalized_path,
    _resolve_delivery_context,
    _resolve_study_owned_paper_context,
    build_authority_source_relative_root,
    build_charter_contract_linkage,
    build_submission_source_root,
    can_sync_study_delivery,
    resolve_finalize_resume_packet_source,
)
from .delivery_io import (
    clear_directory_contents,
    copy_file,
    copy_tree,
    create_staging_root,
    dump_json,
    remove_directory,
    remap_staging_file_records,
    remap_staging_path_string,
    replace_directory_atomically,
    reset_directory,
    utc_now,
    write_text,
    build_zip_from_directory,
)
from .delivery_rendering import (
    FRONT_MATTER_LABELS,
    METADATA_CLOSEOUT_LABELS,
    _humanize_metadata_closeout_item,
    _humanize_submission_field,
    _is_pending_submission_item,
    _submission_delivery_stale_reason_label,
    build_artifacts_finalize_readme,
    build_artifacts_root_readme,
    build_current_package_readme,
    build_delivery_surface_roles,
    build_general_delivery_readme,
    build_manuscript_root_readme,
    build_preview_general_delivery_readme,
    build_promoted_delivery_readme,
    build_submission_package_audit_preview_readme,
    build_submission_package_readme,
    build_submission_todo_from_manifest,
    build_unavailable_general_delivery_readme,
    build_unavailable_submission_package_readme,
    ensure_manuscript_root_readme,
)

__all__ = [
    "SYNC_STAGES",
    "FORMAL_PAPER_DELIVERY_RELATIVE_PATHS",
    "utc_now",
    "dump_json",
    "_normalized_path",
    "_build_ledger_contract_linkage",
    "build_charter_contract_linkage",
    "write_text",
    "reset_directory",
    "remove_directory",
    "create_staging_root",
    "remap_staging_path_string",
    "remap_staging_file_records",
    "replace_directory_atomically",
    "clear_directory_contents",
    "can_sync_study_delivery",
    "_resolve_study_owned_paper_context",
    "_resolve_delivery_context",
    "copy_file",
    "copy_tree",
    "build_submission_source_root",
    "build_submission_package_readme",
    "build_general_delivery_readme",
    "_submission_delivery_stale_reason_label",
    "build_unavailable_general_delivery_readme",
    "build_preview_general_delivery_readme",
    "build_manuscript_root_readme",
    "build_artifacts_root_readme",
    "build_artifacts_finalize_readme",
    "build_unavailable_submission_package_readme",
    "build_submission_package_audit_preview_readme",
    "build_delivery_surface_roles",
    "build_promoted_delivery_readme",
    "ensure_manuscript_root_readme",
    "resolve_finalize_resume_packet_source",
    "build_zip_from_directory",
    "build_authority_source_relative_root",
    "FRONT_MATTER_LABELS",
    "METADATA_CLOSEOUT_LABELS",
    "_humanize_submission_field",
    "_humanize_metadata_closeout_item",
    "_is_pending_submission_item",
    "build_submission_todo_from_manifest",
    "build_current_package_readme",
    "Path",
    "medical_surface_policy",
    "GENERAL_MEDICAL_JOURNAL_PROFILE",
    "is_supported_publication_profile",
    "normalize_publication_profile",
    "read_study_charter",
    "resolve_study_charter_ref",
    "resolve_paper_root_context",
]
