from __future__ import annotations

import math
from typing import Any

from .boxes import (
    _all_boxes,
    _boxes_of_type,
    _boxes_overlap,
    _box_within_box,
    _box_within_device,
    _check_boxes_within_device,
    _check_colorbar_panel_overlap,
    _check_composite_panel_label_anchors,
    _check_curve_like_layout,
    _check_legend_panel_overlap,
    _check_pairwise_non_overlap,
    _check_required_box_types,
    _curve_x_axis_titles,
    _curve_y_axis_titles,
    _first_box_of_type,
    _layout_override_flag,
    _panel_label_token,
    _point_within_box,
    _primary_panel,
)
from .core import (
    ENGINE_ID,
    Box,
    Device,
    LayoutSidecar,
    _issue,
    _require_mapping,
    _require_non_empty_text,
    _require_numeric,
    _utc_now,
)
from .curve_metrics import (
    _check_curve_metrics,
    _check_curve_series_collection,
    _check_reference_line_collection_within_device,
    _check_reference_line_within_device,
    _check_risk_layering_bar_metrics,
    _check_time_dependent_roc_comparison_panel_metrics,
    _check_time_to_event_discrimination_calibration_metrics,
)
from .matrix_metrics import _check_audit_panel_collection_metrics, _matrix_cell_lookup
from .normalize import _normalize_layout_sidecar, _subset_layout_sidecar

__all__ = [
    "Any",
    "ENGINE_ID",
    "Box",
    "Device",
    "LayoutSidecar",
    "_all_boxes",
    "_boxes_of_type",
    "_boxes_overlap",
    "_box_within_box",
    "_box_within_device",
    "_check_audit_panel_collection_metrics",
    "_check_boxes_within_device",
    "_check_colorbar_panel_overlap",
    "_check_composite_panel_label_anchors",
    "_check_curve_like_layout",
    "_check_curve_metrics",
    "_check_curve_series_collection",
    "_check_legend_panel_overlap",
    "_check_pairwise_non_overlap",
    "_check_reference_line_collection_within_device",
    "_check_reference_line_within_device",
    "_check_required_box_types",
    "_check_risk_layering_bar_metrics",
    "_check_time_dependent_roc_comparison_panel_metrics",
    "_check_time_to_event_discrimination_calibration_metrics",
    "_curve_x_axis_titles",
    "_curve_y_axis_titles",
    "_first_box_of_type",
    "_issue",
    "_layout_override_flag",
    "_matrix_cell_lookup",
    "_normalize_layout_sidecar",
    "_panel_label_token",
    "_point_within_box",
    "_primary_panel",
    "_require_mapping",
    "_require_non_empty_text",
    "_require_numeric",
    "_subset_layout_sidecar",
    "_utc_now",
    "math",
]
