from __future__ import annotations


def render_workspace_agents(*, workspace_name: str) -> str:
    return (
        f"# {workspace_name} Workspace Rules\n\n"
        "适用范围：当前 workspace 根目录及所有子目录。\n\n"
        "这个文件由 `medautosci init-workspace` 自动生成，用于声明当前 workspace 的本地约束、MAS 入口语义与基座回灌要求。\n"
        "平台默认的 controller-first 与 automation-ready 运行语义统一维护在 "
        "[`WORKSPACE_AUTOSCIENCE_RULES.md`](WORKSPACE_AUTOSCIENCE_RULES.md)。\n\n"
        "## 交流与工具\n\n"
        "- 先给结论，再补必要上下文；表达保持直接、专业、信息密度高。\n"
        "- 对于是/否问题先给判断；比较型问题先给推荐结论；复杂任务先拆清边界、依赖和验收口径。\n"
        "- 对于不冲突、可并行的任务，优先使用 subagent 提高效率。\n"
        "- 浏览网页优先使用 `agent-browser`。\n"
        "- 涉及 PDF、图片、Office、网页内容提取时，优先使用官方 `mineru-document-extractor`。\n\n"
        "## 本地执行约束\n\n"
        "- 修改任何代码、配置、数据契约或文档前，先读取相关文件与上下文，确认真实生效位置、调用链路和约束。\n"
        "- 保持变更范围最小、可审查、可回退；不改无关文件，不覆盖用户已有本地修改。\n"
        "- 优先做直接、可验证、可维护的根因解法；不为了省事掩盖真实约束。\n"
        "- 避免采用降级处理、兜底方案、临时补丁、启发式方法、局部稳定化手段，以及非严谨通用算法的后处理补救措施。\n"
        "- 能复用既有 controller、contract、schema 和 workspace pattern 就不新起平行抽象。\n"
        "- 在声称已完成、已修复或已通过前，必须运行与变更范围匹配的验证，并报告真实命令与结果。\n\n"
        "## MAS 入口约束\n\n"
        "- 进入当前 workspace 前，先读取本文件、`README.md`、`WORKSPACE_AUTOSCIENCE_RULES.md` 与相关 study 文档。\n"
        "- 研究任务的创建、恢复、门禁判断和状态读取统一走 `MedAutoScience` controller / CLI / overlay skill。\n"
        "- 默认通过 `ops/medautoscience/bin/show-profile`、`ops/medautoscience/bin/bootstrap`、"
        "`ops/medautoscience/bin/enter-study` 与 `ops/medautoscience/bin/watch-runtime` 调用 MAS 工作流。\n"
        "- `ops/med-deepscientist/` 是 runtime 状态和运维脚本目录；研究治理入口归属 MAS。\n\n"
        "## 用户论文修改请求处理\n\n"
        "- 用户通过 Codex 对论文提出修改、审稿意见、补分析或改表图要求时，先把请求作为 MAS/MDS study revision intake 处理，而不是默认直接编辑 `manuscript/current_package/`。\n"
        "- 动手前必须查询对应 study 的 `study-runtime-status`，确认 live runtime、`execution_owner_guard`、`supervisor_only` 与 publication gate 状态；runtime 接管中时只做监督，除非已经显式暂停或接管。\n"
        "- 若 runtime stopped、bundle-stage 已解锁或用户明确要求紧急前台修订，允许直接修改 study 文件，但必须同时留下 MAS/MDS 可接手的 durable handoff，写清数据源、脚本入口、输出表图、改动范围、claim guardrails、canonical source 是否已回灌和下一步 owner。\n"
        "- `manuscript/current_package/` 是 human-facing projection，不是唯一权威源；任何未同步回 controller-authorized `paper/` 或 runtime worktree 的人工修订，都必须在 README、TODO 或 REVISION_HANDOFF 中显式标注，避免后续自动同步覆盖。\n\n"
        "## 研究边界\n\n"
        "- 这是病种/课题级 research workspace，负责管理共享数据底座、数据契约、历史证据、运行入口和多个未来论文方向。\n"
        "- `study` 是论文交付单元，一篇准备投稿的论文对应一个 `study`。\n"
        "- 同一篇论文里的模型对比、方法竞争、敏感性分析、解释性分析，必须留在同一个 `study` 内。\n"
        "- 只有当研究问题、终点定义、论文叙事或投稿目标真正分叉，才允许新建下一个 `study`。\n\n"
        "## Workspace 边界\n\n"
        "- 当前 workspace 的 `AGENTS.md` 只约束 Codex 进入本目录后的工作方式、MAS 入口选择和本地文件边界。\n"
        "- 研究设计、统计方法、投稿判断、publication gate 与 study 质量判断归属 MAS / MDS 的 controller、overlay skill、contract 与 study 文档。\n"
        "- `refs/`、历史记录或人工材料只作为 workspace 证据来源；是否升级为正式 contract 由 MAS / MDS 的对应流程判断。\n\n"
        "## 基座回灌约束\n\n"
        "- 在论文、study 或 workspace 执行过程中，如果遇到的 bug 属于流程问题、运行时问题、controller / contract 问题、overlay 问题、prompt / skill 问题，或依赖环境本身的问题，必须回到对应依赖仓进行正式修复。\n"
        "- 优先在 `med-autoscience` 与 `med-deepscientist` repo 中完成基座层修复，再回到当前 workspace 验证修复后的行为。\n"
        "- 基座层修复需要在对应依赖仓开独立 worktree 实施和验证，完成后吸收回主线并清理 worktree、临时分支与临时状态。\n"
        "- 回灌提交前必须检查当前 GitHub 登录账号；如果登录账号是 `gaofeng21cn`，可以直接提交并推送到对应 repo；否则只能向对应 GitHub repo 提交 PR。\n"
        "- 当前工作目录中的修复只用于辅助定位问题或验证根因；基座缺陷需要通过依赖仓修复与回灌收口。\n"
    )
