from __future__ import annotations

import argparse

from med_autoscience.cli_public_surface import GROUPED_COMMAND_PROGS
from med_autoscience.cli_parts.runtime_storage_commands import register_runtime_storage_parsers
from med_autoscience.figure_routes import supported_required_route_help


def build_parser(*, study_cycle_profiler) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="medautosci")
    subparsers = parser.add_subparsers(dest="command", required=True)

    doctor_parser = subparsers.add_parser("doctor")
    doctor_parser.add_argument("--profile", required=True)

    show_profile_parser = subparsers.add_parser("show-profile")
    show_profile_parser.add_argument("--profile", required=True)
    show_profile_parser.add_argument("--format", choices=("text", "json"), default="text")

    mainline_status_parser = subparsers.add_parser("mainline-status")
    mainline_status_parser.add_argument("--format", choices=("text", "json"), default="text")

    mainline_phase_parser = subparsers.add_parser("mainline-phase")
    mainline_phase_parser.add_argument("--phase", default="current")
    mainline_phase_parser.add_argument("--format", choices=("text", "json"), default="text")

    subparsers.add_parser("show-agent-entry-modes")

    sync_agent_entry_assets_parser = subparsers.add_parser("sync-agent-entry-assets")
    sync_agent_entry_assets_parser.add_argument("--repo-root", default=".")

    preflight_parser = subparsers.add_parser("preflight-changes")
    preflight_sources = preflight_parser.add_mutually_exclusive_group(required=True)
    preflight_sources.add_argument("--files", nargs="+")
    preflight_sources.add_argument("--staged", action="store_true")
    preflight_sources.add_argument("--base-ref", type=str)
    preflight_parser.add_argument("--format", choices=("text", "json"), default="text")

    watch_parser = subparsers.add_parser("watch")
    watch_parser.add_argument("--quest-root", type=str)
    watch_parser.add_argument("--runtime-root", type=str)
    watch_parser.add_argument("--profile", type=str)
    watch_parser.add_argument("--ensure-study-runtimes", action="store_true")
    watch_parser.add_argument("--apply", action="store_true")
    watch_parser.add_argument("--loop", action="store_true")
    watch_parser.add_argument("--interval-seconds", type=int, default=300)
    watch_parser.add_argument("--max-ticks", type=int)

    runtime_supervision_status_parser = subparsers.add_parser("runtime-supervision-status")
    runtime_supervision_status_parser.add_argument("--profile", required=True)
    runtime_supervision_status_parser.add_argument("--interval-seconds", type=int, default=300)

    runtime_ensure_supervision_parser = subparsers.add_parser("runtime-ensure-supervision")
    runtime_ensure_supervision_parser.add_argument("--profile", required=True)
    runtime_ensure_supervision_parser.add_argument("--interval-seconds", type=int, default=300)
    runtime_ensure_supervision_parser.add_argument("--no-trigger-now", action="store_true")

    runtime_remove_supervision_parser = subparsers.add_parser("runtime-remove-supervision")
    runtime_remove_supervision_parser.add_argument("--profile", required=True)
    runtime_remove_supervision_parser.add_argument("--interval-seconds", type=int, default=300)

    register_runtime_storage_parsers(subparsers)

    init_data_assets_parser = subparsers.add_parser("init-data-assets")
    init_data_assets_parser.add_argument("--workspace-root", required=True)

    data_assets_status_parser = subparsers.add_parser("data-assets-status")
    data_assets_status_parser.add_argument("--workspace-root", required=True)
    init_portfolio_memory_parser = subparsers.add_parser("init-portfolio-memory")
    init_portfolio_memory_parser.add_argument("--workspace-root", required=True)
    portfolio_memory_status_parser = subparsers.add_parser("portfolio-memory-status")
    portfolio_memory_status_parser.add_argument("--workspace-root", required=True)
    init_workspace_literature_parser = subparsers.add_parser("init-workspace-literature")
    init_workspace_literature_parser.add_argument("--workspace-root", required=True)
    workspace_literature_status_parser = subparsers.add_parser("workspace-literature-status")
    workspace_literature_status_parser.add_argument("--workspace-root", required=True)
    prepare_external_research_parser = subparsers.add_parser("prepare-external-research")
    prepare_external_research_parser.add_argument("--workspace-root", required=True)
    prepare_external_research_parser.add_argument("--as-of-date", type=str)
    external_research_status_parser = subparsers.add_parser("external-research-status")
    external_research_status_parser.add_argument("--workspace-root", required=True)
    assess_data_asset_impact_parser = subparsers.add_parser("assess-data-asset-impact")
    assess_data_asset_impact_parser.add_argument("--workspace-root", required=True)
    validate_public_registry_parser = subparsers.add_parser("validate-public-registry")
    validate_public_registry_parser.add_argument("--workspace-root", required=True)
    startup_data_readiness_parser = subparsers.add_parser("startup-data-readiness")
    startup_data_readiness_parser.add_argument("--workspace-root", required=True)
    apply_data_asset_update_parser = subparsers.add_parser("apply-data-asset-update")
    apply_data_asset_update_parser.add_argument("--workspace-root", required=True)
    apply_data_asset_update_parser.add_argument("--payload-file", type=str)
    apply_data_asset_update_parser.add_argument("--payload-json", type=str)

    diff_private_release_parser = subparsers.add_parser("diff-private-release")
    diff_private_release_parser.add_argument("--workspace-root", required=True)
    diff_private_release_parser.add_argument("--family-id", required=True)
    diff_private_release_parser.add_argument("--from-version", required=True)
    diff_private_release_parser.add_argument("--to-version", required=True)

    data_asset_gate_parser = subparsers.add_parser("data-asset-gate")
    data_asset_gate_parser.add_argument("--quest-root", required=True)
    data_asset_gate_parser.add_argument("--apply", action="store_true")

    tooluniverse_status_parser = subparsers.add_parser("tooluniverse-status")
    tooluniverse_status_parser.add_argument("--workspace-root", type=str)
    tooluniverse_status_parser.add_argument("--tooluniverse-root", type=str)

    export_parser = subparsers.add_parser("export-submission-minimal")
    export_parser.add_argument("--paper-root", required=True)
    export_parser.add_argument("--publication-profile", default="general_medical_journal")
    export_parser.add_argument("--citation-style", default="auto")

    display_surface_parser = subparsers.add_parser("materialize-display-surface")
    display_surface_parser.add_argument("--paper-root", required=True)

    display_pack_surface_sync_parser = subparsers.add_parser("sync-display-pack-surface")
    display_pack_surface_sync_parser.add_argument("--paper-root", required=True)

    time_to_event_direct_migration_parser = subparsers.add_parser("time-to-event-direct-migration")
    time_to_event_direct_migration_parser.add_argument("--study-root", required=True)
    time_to_event_direct_migration_parser.add_argument("--paper-root", required=True)

    resolve_submission_targets_parser = subparsers.add_parser("resolve-submission-targets")
    resolve_submission_targets_parser.add_argument("--profile", type=str)
    resolve_submission_targets_parser.add_argument("--study-root", type=str)
    resolve_submission_targets_parser.add_argument("--quest-root", type=str)

    resolve_journal_shortlist_parser = subparsers.add_parser("resolve-journal-shortlist")
    resolve_journal_shortlist_parser.add_argument("--study-root", required=True, type=str)

    resolve_journal_requirements_parser = subparsers.add_parser("resolve-journal-requirements")
    resolve_journal_requirements_parser.add_argument("--study-root", required=True, type=str)
    resolve_journal_requirements_parser.add_argument("--journal-name", type=str)
    resolve_journal_requirements_parser.add_argument("--journal-slug", type=str)
    resolve_journal_requirements_parser.add_argument("--official-guidelines-url", required=True, type=str)
    resolve_journal_requirements_parser.add_argument("--publication-profile", type=str)
    resolve_journal_requirements_parser.add_argument("--requirements-file", type=str)
    resolve_journal_requirements_parser.add_argument("--requirements-json", type=str)

    materialize_journal_package_parser = subparsers.add_parser("materialize-journal-package")
    materialize_journal_package_parser.add_argument("--paper-root", required=True, type=str)
    materialize_journal_package_parser.add_argument("--study-root", required=True, type=str)
    materialize_journal_package_parser.add_argument("--journal-slug", required=True, type=str)
    materialize_journal_package_parser.add_argument("--publication-profile", type=str)
    materialize_journal_package_parser.add_argument("--confirmed-target", action="store_true")

    resolve_reference_papers_parser = subparsers.add_parser("resolve-reference-papers")
    resolve_reference_papers_parser.add_argument("--quest-root", required=True)

    recommend_aris_sidecar_parser = subparsers.add_parser("recommend-aris-sidecar")
    recommend_aris_sidecar_parser.add_argument("--quest-root", required=True)
    recommend_aris_sidecar_parser.add_argument("--payload-file", type=str)
    recommend_aris_sidecar_parser.add_argument("--payload-json", type=str)

    provision_aris_sidecar_parser = subparsers.add_parser("provision-aris-sidecar")
    provision_aris_sidecar_parser.add_argument("--quest-root", required=True)
    provision_aris_sidecar_parser.add_argument("--payload-file", type=str)
    provision_aris_sidecar_parser.add_argument("--payload-json", type=str)

    import_aris_sidecar_parser = subparsers.add_parser("import-aris-sidecar")
    import_aris_sidecar_parser.add_argument("--quest-root", required=True)

    recommend_sidecar_parser = subparsers.add_parser("recommend-sidecar")
    recommend_sidecar_parser.add_argument("--provider", required=True)
    recommend_sidecar_parser.add_argument("--quest-root", required=True)
    recommend_sidecar_parser.add_argument("--payload-file", type=str)
    recommend_sidecar_parser.add_argument("--payload-json", type=str)
    recommend_sidecar_parser.add_argument("--instance-id", type=str)

    provision_sidecar_parser = subparsers.add_parser("provision-sidecar")
    provision_sidecar_parser.add_argument("--provider", required=True)
    provision_sidecar_parser.add_argument("--quest-root", required=True)
    provision_sidecar_parser.add_argument("--payload-file", type=str)
    provision_sidecar_parser.add_argument("--payload-json", type=str)
    provision_sidecar_parser.add_argument("--instance-id", type=str)

    import_sidecar_parser = subparsers.add_parser("import-sidecar")
    import_sidecar_parser.add_argument("--provider", required=True)
    import_sidecar_parser.add_argument("--quest-root", required=True)
    import_sidecar_parser.add_argument("--instance-id", type=str)

    export_submission_targets_parser = subparsers.add_parser("export-submission-targets")
    export_submission_targets_parser.add_argument("--paper-root", type=str)
    export_submission_targets_parser.add_argument("--profile", type=str)
    export_submission_targets_parser.add_argument("--study-root", type=str)
    export_submission_targets_parser.add_argument("--quest-root", type=str)

    gate_parser = subparsers.add_parser("publication-gate")
    gate_parser.add_argument("--quest-root", required=True)
    gate_parser.add_argument("--apply", action="store_true")

    medical_literature_audit_parser = subparsers.add_parser("medical-literature-audit")
    medical_literature_audit_parser.add_argument("--quest-root", required=True)
    medical_literature_audit_parser.add_argument("--apply", action="store_true")

    medical_reporting_audit_parser = subparsers.add_parser("medical-reporting-audit")
    medical_reporting_audit_parser.add_argument("--quest-root", required=True)
    medical_reporting_audit_parser.add_argument("--apply", action="store_true")

    surface_parser = subparsers.add_parser("medical-publication-surface")
    surface_parser.add_argument("--quest-root", required=True)
    surface_parser.add_argument("--apply", action="store_true")
    surface_parser.add_argument("--daemon-url", default="http://127.0.0.1:20999")

    figure_loop_guard_parser = subparsers.add_parser("figure-loop-guard")
    figure_loop_guard_parser.add_argument("--quest-root", required=True)
    figure_loop_guard_parser.add_argument("--apply", action="store_true")
    figure_loop_guard_parser.add_argument("--outbox-path", type=str)
    figure_loop_guard_parser.add_argument("--daemon-url", type=str)
    figure_loop_guard_parser.add_argument("--accepted-figure", action="append", default=[])
    figure_loop_guard_parser.add_argument("--figure-ticket", action="append", default=[])
    figure_loop_guard_parser.add_argument("--required-route", action="append", default=[], help=supported_required_route_help())
    figure_loop_guard_parser.add_argument("--min-figure-mentions", type=int, default=12)
    figure_loop_guard_parser.add_argument("--min-reference-count", type=int, default=12)
    figure_loop_guard_parser.add_argument("--recent-window", type=int, default=120)
    figure_loop_guard_parser.add_argument("--source", default="medautosci-figure-loop-guard")

    delivery_parser = subparsers.add_parser("sync-study-delivery")
    delivery_parser.add_argument("--paper-root", required=True)
    delivery_parser.add_argument("--stage", choices=("submission_minimal", "finalize"), required=True)
    delivery_parser.add_argument("--publication-profile", default="general_medical_journal")
    delivery_parser.add_argument("--promote-to-final", action="store_true")

    overlay_status_parser = subparsers.add_parser("overlay-status")
    overlay_status_parser.add_argument("--quest-root", type=str)
    overlay_status_parser.add_argument("--profile", type=str)

    install_overlay_parser = subparsers.add_parser("install-medical-overlay")
    install_overlay_parser.add_argument("--quest-root", type=str)
    install_overlay_parser.add_argument("--profile", type=str)

    reapply_overlay_parser = subparsers.add_parser("reapply-medical-overlay")
    reapply_overlay_parser.add_argument("--quest-root", type=str)
    reapply_overlay_parser.add_argument("--profile", type=str)

    subparsers.add_parser("ensure-study-runtime-analysis-bundle")

    ensure_study_runtime_parser = subparsers.add_parser("ensure-study-runtime")
    ensure_study_runtime_parser.add_argument("--profile", required=True)
    ensure_study_runtime_parser.add_argument("--study-id", type=str)
    ensure_study_runtime_parser.add_argument("--study-root", type=str)
    ensure_study_runtime_parser.add_argument("--entry-mode", type=str)
    ensure_study_runtime_parser.add_argument("--allow-stopped-relaunch", action="store_true")
    ensure_study_runtime_parser.add_argument("--force", action="store_true")
    study_runtime_status_parser = subparsers.add_parser("study-runtime-status")
    study_runtime_status_parser.add_argument("--profile", required=True)
    study_runtime_status_parser.add_argument("--study-id", type=str)
    study_runtime_status_parser.add_argument("--study-root", type=str)
    study_runtime_status_parser.add_argument("--entry-mode", type=str)
    study_progress_parser = subparsers.add_parser("study-progress")
    study_progress_parser.add_argument("--profile", required=True)
    study_progress_parser.add_argument("--study-id", type=str)
    study_progress_parser.add_argument("--study-root", type=str)
    study_progress_parser.add_argument("--entry-mode", type=str)
    study_progress_parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    study_cycle_profiler.add_cli_parser(subparsers)
    quality_repair_batch_parser = subparsers.add_parser("quality-repair-batch")
    quality_repair_batch_parser.add_argument("--profile", required=True)
    quality_repair_batch_parser.add_argument("--study-id", type=str)
    quality_repair_batch_parser.add_argument("--study-root", type=str)
    quality_repair_batch_parser.add_argument("--quest-id", type=str)
    ai_reviewer_eval_parser = subparsers.add_parser("materialize-ai-reviewer-publication-eval")
    ai_reviewer_eval_parser.add_argument("--profile", required=True)
    ai_reviewer_eval_parser.add_argument("--study-id", type=str)
    ai_reviewer_eval_parser.add_argument("--study-root", type=str)
    ai_reviewer_eval_parser.add_argument("--entry-mode", type=str)
    ai_reviewer_eval_parser.add_argument("--payload-file", type=str)
    ai_reviewer_eval_parser.add_argument("--payload-json", type=str)
    workspace_cockpit_parser = subparsers.add_parser("workspace-cockpit")
    workspace_cockpit_parser.add_argument("--profile", required=True)
    workspace_cockpit_parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    study_cycle_profiler.add_workspace_cli_parser(subparsers)
    product_frontdesk_parser = subparsers.add_parser("product-frontdesk")
    product_frontdesk_parser.add_argument("--profile", required=True)
    product_frontdesk_parser.add_argument("--format", choices=("markdown", "json"), default="markdown")

    product_preflight_parser = subparsers.add_parser("product-preflight")
    product_preflight_parser.add_argument("--profile", required=True)
    product_preflight_parser.add_argument("--format", choices=("markdown", "json"), default="markdown")

    product_start_parser = subparsers.add_parser("product-start")
    product_start_parser.add_argument("--profile", required=True)
    product_start_parser.add_argument("--format", choices=("markdown", "json"), default="markdown")

    product_entry_manifest_parser = subparsers.add_parser("product-entry-manifest")
    product_entry_manifest_parser.add_argument("--profile", required=True)
    product_entry_manifest_parser.add_argument("--format", choices=("markdown", "json"), default="markdown")

    skill_catalog_parser = subparsers.add_parser("skill-catalog")
    skill_catalog_parser.add_argument("--profile", required=True)
    skill_catalog_parser.add_argument("--format", choices=("markdown", "json"), default="markdown")

    build_product_entry_parser = subparsers.add_parser("build-product-entry")
    build_product_entry_parser.add_argument("--profile", required=True)
    build_product_entry_parser.add_argument("--study-id", type=str)
    build_product_entry_parser.add_argument("--study-root", type=str)
    build_product_entry_parser.add_argument("--entry-mode", choices=("direct", "opl-handoff"), default="direct")
    build_product_entry_parser.add_argument("--format", choices=("markdown", "json"), default="markdown")

    launch_study_parser = subparsers.add_parser("launch-study")
    launch_study_parser.add_argument("--profile", required=True)
    launch_study_parser.add_argument("--study-id", type=str)
    launch_study_parser.add_argument("--study-root", type=str)
    launch_study_parser.add_argument("--entry-mode", type=str)
    launch_study_parser.add_argument("--allow-stopped-relaunch", action="store_true")
    launch_study_parser.add_argument("--force", action="store_true")
    launch_study_parser.add_argument("--format", choices=("markdown", "json"), default="markdown")

    submit_study_task_parser = subparsers.add_parser("submit-study-task")
    submit_study_task_parser.add_argument("--profile", required=True)
    submit_study_task_parser.add_argument("--study-id", type=str)
    submit_study_task_parser.add_argument("--study-root", type=str)
    submit_study_task_parser.add_argument("--task-intent", required=True)
    submit_study_task_parser.add_argument("--entry-mode", type=str)
    submit_study_task_parser.add_argument("--journal-target", type=str)
    submit_study_task_parser.add_argument("--constraint", action="append", default=[])
    submit_study_task_parser.add_argument("--evidence-boundary", action="append", default=[])
    submit_study_task_parser.add_argument("--trusted-input", action="append", default=[])
    submit_study_task_parser.add_argument("--reference-paper", action="append", default=[])
    submit_study_task_parser.add_argument("--first-cycle-output", action="append", default=[])
    submit_study_task_parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    bootstrap_parser = subparsers.add_parser("bootstrap")
    bootstrap_parser.add_argument("--profile", required=True)
    init_workspace_parser = subparsers.add_parser("init-workspace")
    init_workspace_parser.add_argument("--workspace-root", required=True)
    init_workspace_parser.add_argument("--workspace-name", required=True)
    init_workspace_parser.add_argument("--default-publication-profile", default="general_medical_journal")
    init_workspace_parser.add_argument("--default-citation-style", default="AMA")
    init_workspace_parser.add_argument("--hermes-agent-repo-root")
    init_workspace_parser.add_argument("--hermes-home-root")
    init_workspace_parser.add_argument("--dry-run", action="store_true")
    init_workspace_parser.add_argument("--force", action="store_true")
    init_workspace_parser.add_argument("--no-git", action="store_true")

    backend_upgrade_check_parser = subparsers.add_parser("backend-upgrade-check")
    backend_upgrade_check_parser.add_argument("--profile", required=True)
    backend_upgrade_check_parser.add_argument("--refresh", action="store_true")

    hermes_runtime_check_parser = subparsers.add_parser("hermes-runtime-check")
    hermes_runtime_check_parser.add_argument("--profile")
    hermes_runtime_check_parser.add_argument("--hermes-agent-repo-root")
    hermes_runtime_check_parser.add_argument("--hermes-home-root")
    for command_name, prog in GROUPED_COMMAND_PROGS.items():
        choice = subparsers.choices.get(command_name)
        if choice is not None:
            choice.prog = prog
    return parser
