from __future__ import annotations

from tests.test_cli_cases.paper_mission_commands_cases.stage_closure_terminalizer_cases.test_source_selection_cases.domain_transition_direct import (
    test_terminalize_stage_prefers_domain_transition_direct_closeout_over_old_consumption,
    test_terminalize_stage_prefers_domain_transition_direct_closeout_without_materialized_mission,
)
from tests.test_cli_cases.paper_mission_commands_cases.stage_closure_terminalizer_cases.test_source_selection_cases.route_back_source_precedence import (
    test_terminalize_stage_route_back_autodiscovery_reads_nested_attempt_packets,
    test_terminalize_stage_prefers_latest_route_back_packet_over_old_live_write_closeout,
    test_terminalize_stage_prefers_current_transaction_stage_closure_over_stale_direct,
    test_terminalize_stage_prefers_newer_workspace_stage_packet_over_matching_source_closeout,
    test_terminalize_stage_prefers_route_back_identity_when_closeout_packet_fields_are_sparse,
    test_terminalize_stage_prefers_richer_followthrough_closeout_over_newer_sparse_packet,
    test_terminalize_stage_prefers_route_back_with_owner_gate_context_over_newer_plain_packet,
)
